### ISSUE TITLE
Count the number of expressed transcripts 

### ISSUE THREAD

**Issue by bprabin** [trinityrnaseq/trinityrnaseq#101]
I ran the kallisto by following the manual provided an got all 3 output files. After that i used the abundance.txt file to count the number of expressed transcripts by using the following script..
/data/trinityrnaseq-2.1.1/util/misc/count_matrix_features_given_MIN_TPM_threshold.pl /data/Prabin_trinity/abundance.tsv
Then I got output for gene counts as a function of minimum TPM value as follow in table
neg_min_tpm              num_features
-177001                           1
-167389                           2

-201                                478288

I got neg_min_tpm value upto -201 ,but should be upto 0 to make a further analysis of expressed genes. Can anyone help me the solve this issue... please...

**Comment by brianjohnhaas** [comment]
Hi,

The script is meant to run on a matrix of TPM expression values.  If you're
going to run it on the single abundance output file, create a mini-matrix
by extracting the columns corresponding to the transcript names and the TPM
column, and run it on that.

 ie.

     cat abundance.tsv | cut -f1,5 > mini.matrix

$TRINITY_HOME/util/misc/count_matrix_features_given_MIN_TPM_threshold.pl
mini.matrix


best,

~brian

On Tue, Feb 9, 2016 at 7:05 AM, bprabin <notifications@github.com> wrote:

> I ran the kallisto by following the manual provided an got all 3 output
> files. After that i used the abundance.txt file to count the number of
> expressed transcripts by using the following script..
> /data/trinityrnaseq-2.1.1/util/misc/count_matrix_features_given_MIN_TPM_threshold.pl
> /data/Prabin_trinity/abundance.tsv
> Then I got output for gene counts as a function of minimum TPM value as
> follow in table
> neg_min_tpm num_features
> -177001 1
> -167389 2
>
> -201 478288
>
> I got neg_min_tpm value upto -201 ,but should be upto 0 to make a further
> analysis of expressed genes. Can anyone help me the solve this issue...
> please...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/101>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by bprabin** [comment]
thank you for your reply.
I tried it but
prabinb@biolab:~> /data/Prabin_trinity/abundance.tsv | cut -f1,5 > mini.matrix
-bash: /data/Prabin_trinity/abundance.tsv: Permission denied

**Comment by brianjohnhaas** [comment]
you need to 'cat' the file (see original command suggested)

best,

~b

On Tue, Feb 9, 2016 at 8:03 AM, bprabin <notifications@github.com> wrote:

> thank you for your reply.
> I tried it but
> prabinb@biolab:~> /data/Prabin_trinity/abundance.tsv | cut -f1,5 >
> mini.matrix
> -bash: /data/Prabin_trinity/abundance.tsv: Permission denied
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/101#issuecomment-181855333>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by bprabin** [comment]
very very very thank you. This really works..
