### ISSUE TITLE
-bash: get_longest_isoform_seq_per_trinity_gene.pl: command not found

### ISSUE THREAD

**Issue by Hannah-lmax** [trinityrnaseq/trinityrnaseq#1013]
Hi,

I downloaded trinity by conda and successfully used Trinity, but I can't use get_longest_isoform_seq_per_trinity_gene.pl.
The error is 
-bash: get_longest_isoform_seq_per_trinity_gene.pl: command not found

can anyone help me?

**Comment by brianjohnhaas** [comment]
That script can be found under:

trinityrnaseq/util/misc/get_longest_isoform_seq_per_trinity_gene.pl




On Tue, May 18, 2021 at 11:12 AM Hannah-lmax ***@***.***>
wrote:
>
> Hi,
>
> I downloaded trinity by conda and successfully used Trinity, but I can't
use get_longest_isoform_seq_per_trinity_gene.pl.
> The error is
> -bash: get_longest_isoform_seq_per_trinity_gene.pl: command not found
>
> can anyone help me?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by Hannah-lmax** [comment]
I got it! Thanks!
