### ISSUE TITLE
Run GOSeq/Goplot - error in EC.genelist file

### ISSUE THREAD

**Issue by rafinhacp** [trinityrnaseq/trinityrnaseq#1034]
Hello all,

I've been working with Trinity (v2.8.4) to do assemblies and downstream analysis of transcriptomes. I've reached a point in which I have to run GOSeq/Goplot to do the GO terms enrichment analysis. 

I'm working with different datasets (in one of them, the differential gene expression analysis was done with Deseq2 and for the other one I used limma/voom). For both datasets I used the following pipeline:

##Extract GO terms from xls report
/Users/Trinotate-Trinotate-v3.2.1/util/extract_GO_assignments_from_Trinotate_xls.pl --Trinotate_xls trinotate_annotation_report.xls \
-G --include_ancestral_terms > go_annotations.txt

##Create file with lengths of genes:
#Create a file containing transcript lengths:
nohup /home/sw/TRINITY_v2.8.4/trinityrnaseq-Trinity-v2.8.4/util/misc/fasta_seq_length.pl  /media/raid/transcriptomes/data/trinity/Trinity.fasta > Trinity.fasta.seq_lens &

#Use the above to generate the gene lengths file:
nohup /home/sw/TRINITY_v2.8.4/trinityrnaseq-Trinity-v2.8.4/util/misc/TPM_weighted_gene_length.py  \
--gene_trans_map /media/raid/transcrptomes/data/trinity/Trinity.fasta.gene_trans_map \
--trans_lengths Trinity.fasta.seq_lens \
--TPM_matrix /media/raid/transcriptomes/data/matrix_rsem/RSEM.isoform.TMM.EXPR.matrix > Trinity.gene_lengths.txt &

##Run the enrichment analysis on DE
nohup /home/sw/TRINITY_v2.8.4/trinityrnaseq-Trinity-v2.8.4/Analysis/DifferentialExpression/analyze_diff_expr.pl \
--matrix /media/raid/transcriptomes/data/matrix_rsem/RSEM.gene.TMM.EXPR.matrix \
-P 1e-2 \
-C 2 \
--max_DE_genes_per_comparison 5000 \
--output GO \
--samples /media/raid/transcriptomes/data/assembly.txt \
--examine_GO_enrichment --GO_annots /media/raid/transcriptomes/data/GOSeq/go_annotations.txt --gene_lengths /media/raid/transcriptomes/data/GOSeq/Trinity.gene_lengths.txt > logGoEnrich.txt 2>&1 &

##Generate graphs of GO enrichment:
nohup /home/sw/TRINITY_v2.8.4/trinityrnaseq-Trinity-v2.8.4/Analysis/DifferentialExpression/prep_n_run_GOplot.pl \
--GO_annots /media/raid/transcriptomes/data/GOSeq/go_annotations.txt \
--DE_subset RSEM.gene.counts.matrix.cond_A1_vs_cond_B1.DESeq2.DE_results.P1e-2_C2.DE.subset
--DE_GO_enriched RSEM.gene.counts.matrix.cond_A1_vs_cond_B1.DESeq2.DE_results.P1e-2_C2.DE.subset.GOseq.enriched \
--tmpdir tmpdir_GOplots \
--pdf_filename GOgraphs.pdf > logGOgraphs.txt 2>&1 &

Then, I noticed that the last step (Generate graphs of GO enrichment with the prep_n_run_GOplot.pl script) was not working for data for which DGE had been performed with deseq2. I noticed that the EC.genelist file was very odd and when I checked, I realized that the values in the columns "log2FC" and "adjusted -p-values" were not the actual logFC and adjusted p-value, they were the "baseMeanA" and the "log2FoldChange". But the EC.genelist file generated for the data analyses with limma/voom worked perfectly (I also tested this in other datasets, either analyzed with limma/voom or deseq2, and I got the same error in all the deseq2 ones).

I have no experience coding and I'm not familiar with perl. But I think that the script is written in a way that it always pulls the 4th and the 7th column from the "RSEM.gene.counts.matrix.cond_A1_vs_cond_B1.DESeq2.DE_results.P1e-2_C2.DE.subset" file,  to generate the EC.genelist file. But this only works with limma/voom output, where the logFC and the adjusted p-value will be in the 4th and 7th column, respectively. For the deseq2 analysis, the 7th and the 11th column are the ones that have the logFC and the adjusted p-value (the 4th and the 7th columns of the deseq2 output are the "baseMeanA" and the "log2FoldChange").

I solved this by generating the EC.david and EC.genelist with an R script available here: https://www.r-bloggers.com/2018/11/r-script-prep-for-goplot-from-trinity/
This script can be used for any DE output, as the columns are selected by the name. So all you have to do is to change the column name you wanna select, based on the package you used for DE.

My understanding is that GOSeq-Goplot is something new on Trinity and support is sort of limited. So I decided to report this here, in case it is interesting for Trinity developers to change the prep_n_run_GOplot.pl in the future (assuming I got the error right) and for other people facing the same problem to be able to solve it quicker than I did. Hope it helps.

**Comment by brianjohnhaas** [comment]
Thanks for this!  please keep this open and I'll revisit it to patch an upcoming release
