### ISSUE TITLE
Problem in installing edgeR in R enviornment after updating from version 3.4.4 to 3.6.3

### ISSUE THREAD

**Issue by dipsaha** [trinityrnaseq/trinityrnaseq#1043]
Hi,

I am using a workstation with Ubuntu 14.04 LTS as OS. Due to problem in running edgeR visualization, I was forced to update from R v. 3.4.4 to 3.6.3 recently. I tried to completely remove old version of R with its dependencies and reinstalled the new version (3.6.3) of R available for my OS. 
Cmds:
sudo apt-get remove r-base-core
sudo apt-get remove r-base
sudo apt-get purge r-base r-base-core r-*
sudo apt-get autoremove

sudo apt-get update
sudo apt-get install r-base
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.10")

Checked : 
BiocManager::valid() 

'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cloud.r-project.org

[1] TRUE

Following this I tried to install edgeR and packages 
BiocManager::install(c("edgeR", "limma", "DESeq2", "ctc", "Biobase", "gplots", "ape", "argparse"))

Most of the packages were installed but some of them were repeatedly giving error reports.

Warning messages I received as:

Warning messages:
1: In .inet_warning(msg) :
  installation of package ‘fastmap’ had non-zero exit status
2: In .inet_warning(msg) :
  installation of package ‘isoband’ had non-zero exit status
3: In .inet_warning(msg) :
  installation of package ‘Rcpp’ had non-zero exit status
4: In .inet_warning(msg) :
  installation of package ‘cachem’ had non-zero exit status
5: In .inet_warning(msg) :
  installation of package ‘RcppArmadillo’ had non-zero exit status
6: In .inet_warning(msg) :
  installation of package ‘edgeR’ had non-zero exit status
7: In .inet_warning(msg) : installation of package ‘ape’ had non-zero exit status
8: In .inet_warning(msg) :
  installation of package ‘memoise’ had non-zero exit status
9: In .inet_warning(msg) :
  installation of package ‘BiocParallel’ had non-zero exit status
10: In .inet_warning(msg) :
  installation of package ‘RSQLite’ had non-zero exit status
11: In .inet_warning(msg) :
  installation of package ‘DelayedArray’ had non-zero exit status
12: In .inet_warning(msg) :
  installation of package ‘AnnotationDbi’ had non-zero exit status
13: In .inet_warning(msg) :
  installation of package ‘SummarizedExperiment’ had non-zero exit status
14: In .inet_warning(msg) :
  installation of package ‘ggplot2’ had non-zero exit status
15: In .inet_warning(msg) :
  installation of package ‘annotate’ had non-zero exit status
16: In .inet_warning(msg) :
  installation of package ‘viridis’ had non-zero exit status
17: In .inet_warning(msg) :
  installation of package ‘genefilter’ had non-zero exit status
18: In .inet_warning(msg) :
  installation of package ‘geneplotter’ had non-zero exit status
19: In .inet_warning(msg) :
  installation of package ‘Hmisc’ had non-zero exit status
20: In .inet_warning(msg) :
  installation of package ‘DESeq2’ had non-zero exit status 

Sample of one of the error message with the not installed packages is:

-----------------------------------------------------------------------------------------------
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^
/usr/local/include/except.h:15:16: error: ‘struct Except_Frame_T’ has a previous declaration as ‘struct Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                ^
/usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type
   Except_Frame_T prev;
                  ^
make: *** [ipcmutex.o] Error 1
ERROR: compilation failed for package ‘BiocParallel’

I have googled this issue for several times but hardly could get any steps to tackle this issue. This may not be the problem with the edgeR or other programs linked to Trinity. It seems there are some broken packages linked to the file in /usr/local/include/except.h. I am stuck in the DEG analysis step and clueless to get it rectified thus seek your help.

Your help in this regard is highly solicited.
~Dip Saha

**Comment by brianjohnhaas** [comment]
If you can use our docker or singularity image, it comes with everything you need already installed.
