### ISSUE TITLE
"Error, no length found for X hit" in analyze_blastPlus_tophit_coverage.pl 

### ISSUE THREAD

**Issue by homiec17** [trinityrnaseq/trinityrnaseq#105]
I generated a protein blast database using the referenced Swisprot.fasta and ran a blastx search with my assembled-transcriptome, as described. When I try to run analyze_blastPlus_tophit_coverage.pl with the resultant blastx output, I repeatedly get the message "Error, no length found for" name_of_transcript "with hit: $VAR1={".... The subject ID (hit) changes every time I try to run the script. The output file has a header but is otherwise blank. Can you help?

**Comment by brianjohnhaas** [comment]
That's very strange.  Can you state the command you're running along with parameters?

Thx

-Brian
(by iPhone)

**Comment by homiec17** [comment]
Hi Brian. This is what I've tried:

**Comment by homiec17** [comment]
Sorry - that last email got sent too quickly. The command run and resultant
error are below. I've also attached my BLAST output. Please let me know if
I can provide anything else. Thanks!

elyac@eisenlab1:~$
trinityrnaseq-2.1.1/util/analyze_blastPlus_topHit_coverage.pl
Entomophthora/Transcriptome/Trinity/blastx.outfmt6
Entomophthora/Transcriptome/Trinity/Trinity.fasta BLAST/uniprot_sprot.fasta

Error, no length found for tr|Q5I8R6|Q5I8R6_9FUNG, with hit: $VAR1 = {

          'db_id' => 'tr|Q5I8R6|Q5I8R6_9FUNG',

          'percent_id' => '40.18',

          'query_match_len' => 939,

          'evalue' => '6e-64',

          'line' => 'TRINITY_DN77_c0_g1_i1 tr|Q5I8R6|Q5I8R6_9FUNG 40.18 331
18010 988 50 22 352 6e-64 229',

          'query_id' => 'TRINITY_DN77_c0_g1_i1',

          'db_match_len' => 331,

          'query_start' => 988,

          'query_end' => 50,

          'db_start' => 22,

          'bitscore' => ' 229',

          'db_end' => 352

        };

**Comment by brianjohnhaas** [comment]
Weird

If you grep Q5I8R6_9FUNG from the database what do you see?

-Brian
(by iPhone)

**Comment by homiec17** [comment]
Nothing comes up. Nor do I get anything with "Q5I8R6" or "9FUNG".

**Comment by brianjohnhaas** [comment]
Hmm...  How do you have a blast hit to it if it's not in the database?  😜

Are you sure the database you searched using blast is the same one you're running the full length analysis with?   I've seen mixups happen before and that would explain this.

Best,

-Brian
(by iPhone)

**Comment by homiec17** [comment]
Hi Brian. Yea, that's what occurred to me right after I sent you the last
email. I'm puzzled as to how that could have happened, but grepping the
offending subjects to the trembl database clearly shows that they're in
there. I'm so sorry for wasting your time. Thanks for your help.

**Comment by brianjohnhaas** [comment]
No worries.  Best of luck!

~b

On Sat, Feb 27, 2016 at 11:34 AM, homiec17 <notifications@github.com> wrote:

> Hi Brian. Yea, that's what occurred to me right after I sent you the last
> email. I'm puzzled as to how that could have happened, but grepping the
> offending subjects to the trembl database clearly shows that they're in
> there. I'm so sorry for wasting your time. Thanks for your help.
>
> On Fri, Feb 26, 2016 at 6:51 PM, Brian Haas <notifications@github.com>
>
> wrote:
>
> > Hmm... How do you have a blast hit to it if it's not in the database? 😜
> >
> > Are you sure the database you searched using blast is the same one you're
> > running the full length analysis with? I've seen mixups happen before and
> > that would explain this.
> >
> > Best,
> >
> > -Brian
> > (by iPhone)
> >
> >
> >
> > > On Feb 26, 2016, at 8:47 PM, homiec17 <notifications@github.com>
> wrote:
> > >
> > > Nothing comes up. Nor do I get anything with "Q5I8R6" or "9FUNG".
> > >
> > > On Fri, Feb 26, 2016 at 4:09 PM, Brian Haas <notifications@github.com>
> > > wrote:
> > >
> > > > Weird
> > > >
> > > > If you grep Q5I8R6_9FUNG from the database what do you see?
> > > >
> > > > -Brian
> > > > (by iPhone)
> > > >
> > > >
> > > >
> > > > > On Feb 26, 2016, at 6:15 PM, homiec17 <notifications@github.com>
> > wrote:
> > > > >
> > > > > Sorry - that last email got sent too quickly. The command run and
> > > > resultant
> > > > > error are below. I've also attached my BLAST output. Please let me
> > know
> > > > if
> > > > > I can provide anything else. Thanks!
> > > > >
> > > > > elyac@eisenlab1:~$
> > > > > trinityrnaseq-2.1.1/util/analyze_blastPlus_topHit_coverage.pl
> > > > > Entomophthora/Transcriptome/Trinity/blastx.outfmt6
> > > > > Entomophthora/Transcriptome/Trinity/Trinity.fasta
> > > > BLAST/uniprot_sprot.fasta
> > > > >
> > > > > Error, no length found for tr|Q5I8R6|Q5I8R6_9FUNG, with hit: $VAR1
> =
> > {
> > > > >
> > > > > 'db_id' => 'tr|Q5I8R6|Q5I8R6_9FUNG',
> > > > >
> > > > > 'percent_id' => '40.18',
> > > > >
> > > > > 'query_match_len' => 939,
> > > > >
> > > > > 'evalue' => '6e-64',
> > > > >
> > > > > 'line' => 'TRINITY_DN77_c0_g1_i1 tr|Q5I8R6|Q5I8R6_9FUNG 40.18 331
> > > > > 18010 988 50 22 352 6e-64 229',
> > > > >
> > > > > 'query_id' => 'TRINITY_DN77_c0_g1_i1',
> > > > >
> > > > > 'db_match_len' => 331,
> > > > >
> > > > > 'query_start' => 988,
> > > > >
> > > > > 'query_end' => 50,
> > > > >
> > > > > 'db_start' => 22,
> > > > >
> > > > > 'bitscore' => ' 229',
> > > > >
> > > > > 'db_end' => 352
> > > > >
> > > > > };
> > > > >
> > > > > On Fri, Feb 26, 2016 at 3:12 PM, CAROLYN NICOLE ELYA <
> > elyac@berkeley.edu
> > > > >
> > > > > wrote:
> > > > >
> > > > > > Hi Brian. This is what I've tried:
> > > > > >
> > > > > >
> > > > > > On Fri, Feb 26, 2016 at 2:03 PM, Brian Haas <
> > notifications@github.com>
> > > > > > wrote:
> > > > > >
> > > > > >> That's very strange. Can you state the command you're running
> > along
> > > > with
> > > > > >> parameters?
> > > > > >>
> > > > > >> Thx
> > > > > >>
> > > > > >> -Brian
> > > > > >> (by iPhone)
> > > > > >>
> > > > > >>
> > > > > >> > On Feb 26, 2016, at 3:19 PM, homiec17 <
> notifications@github.com
> > >
> > > > wrote:
> > > > > >> >
> > > > > >> > I generated a protein blast database using the referenced
> > > > > >> Swisprot.fasta and ran a blastx search with my
> > > > assembled-transcriptome, as
> > > > > >> described. When I try to run
> analyze_blastPlus_tophit_coverage.pl
> > > > with the
> > > > > >> resultant blastx output, I repeatedly get the message "Error, no
> > > > length
> > > > > >> found for" name_of_transcript "with hit: $VAR1={".... The
> subject
> > ID
> > > > (hit)
> > > > > >> changes every time I try to run the script. The output file has
> a
> > > > header
> > > > > >> but is otherwise blank. Can you help?
> > > > > >> >
> > > > > >> > —
> > > > > >> > Reply to this email directly or view it on GitHub.
> > > > > >> >
> > > > > >>
> > > > > >> —
> > > > > >> Reply to this email directly or view it on GitHub
> > > > > >> <
> > > >
> >
> https://github.com/trinityrnaseq/trinityrnaseq/issues/105#issuecomment-189502717
> > > > >
> > > > > >> .
> > > >
> > > > > >>
> > > > > >
> > > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub.
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> >
> https://github.com/trinityrnaseq/trinityrnaseq/issues/105#issuecomment-189533227
> > >
> >
> > > > .
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/trinityrnaseq/trinityrnaseq/issues/105#issuecomment-189562772
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/105#issuecomment-189679250>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
