### ISSUE TITLE
 /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/..//Inchworm/bin/fastaToKmerCoverageStats: No such file or directory

### ISSUE THREAD

**Issue by juliemathari** [trinityrnaseq/trinityrnaseq#1079]
I am using trinity version 2.13.2. I am trying to run the script for sample data. However I am facing the below mentioned error.
I tried to reinstall the software and also increase the RAM however it still shows the same error.
I want to do transcriptome assembly of 46 samples. However not able to troubleshoot this error. Kindly let me know where am I going wrong.....
 
CMD: /opt/data/home/julie/julie_software                                                                                                             /trinityrnaseq-v2.13.2/util/insilico_read_normalization.pl --seqType fq --JM 4G                                                                                                               --max_cov 200 --min_cov 1 --CPU 4 --output /opt/data/home/julie/julie_software/                                                                                                             trinityrnaseq-v2.13.2/sample_data/test_Trinity_Assembly/trinity_out_dir/insilico                                                                                                             _read_normalization --max_CV 10000  --SS_lib_type RF  --left /opt/data/home/juli                                                                                                             e/julie_software/trinityrnaseq-v2.13.2/sample_data/test_Trinity_Assembly/reads.l                                                                                                             eft.fq.gz --right /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/samp                                                                                                             le_data/test_Trinity_Assembly/reads.right.fq.gz --pairs_together  --PARALLEL_STA                                                                                                             TS
-prepping seqs
Converting input files. (both directions in parallel)left file exists, nothing t                                                                                                             o doright file exists, nothing to doDone converting input files.-kmer counting.
-generating stats files
CMD: /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/..//Inchworm                                                                                                             /bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.f                                                                                                             a --kmer_size 25  --num_threads 2  > left.fa.K25.stats
bash: /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/..//Inchwor                                                                                                             m/bin/fastaToKmerCoverageStats: No such file or directory
Thread 3 terminated abnormally: Error, cmd: /opt/data/home/julie/julie_software/                                                                                                             trinityrnaseq-v2.13.2/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads lef                                                                                                             t.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > left                                                                                                             .fa.K25.stats died with ret 32512 at /opt/data/home/julie/julie_software/trinity                                                                                                             rnaseq-v2.13.2/util/insilico_read_normalization.pl line 795.
CMD: /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/..//Inchworm                                                                                                             /bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.                                                                                                             fa --kmer_size 25  --num_threads 2  > right.fa.K25.stats
Error, thread exited with error Error, cmd: /opt/data/home/julie/julie_software/                                                                                                             trinityrnaseq-v2.13.2/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads lef                                                                                                             t.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > left                                                                                                             .fa.K25.stats died with ret 32512 at /opt/data/home/julie/julie_software/trinity                                                                                                             rnaseq-v2.13.2/util/insilico_read_normalization.pl line 795.

bash: /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/..//Inchwor                                                                                                             m/bin/fastaToKmerCoverageStats: No such file or directory
Thread 4 terminated abnormally: Error, cmd: /opt/data/home/julie/julie_software/                                                                                                             trinityrnaseq-v2.13.2/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads rig                                                                                                             ht.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > rig                                                                                                             ht.fa.K25.stats died with ret 32512 at /opt/data/home/julie/julie_software/trini                                                                                                             tyrnaseq-v2.13.2/util/insilico_read_normalization.pl line 795.
Error, thread exited with error Error, cmd: /opt/data/home/julie/julie_software/                                                                                                             trinityrnaseq-v2.13.2/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads rig                                                                                                             ht.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 2  > rig                                                                                                             ht.fa.K25.stats died with ret 32512 at /opt/data/home/julie/julie_software/trini                                                                                                             tyrnaseq-v2.13.2/util/insilico_read_normalization.pl line 795.

Error, 2 threads errored out at /opt/data/home/julie/julie_software/trinityrnase                                                                                                             q-v2.13.2/util/insilico_read_normalization.pl line 999.
Error, cmd: /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/util/insil                                                                                                             ico_read_normalization.pl --seqType fq --JM 4G  --max_cov 200 --min_cov 1 --CPU                                                                                                              4 --output /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/sample_data                                                                                                             /test_Trinity_Assembly/trinity_out_dir/insilico_read_normalization --max_CV 1000                                                                                                             0  --SS_lib_type RF  --left /opt/data/home/julie/julie_software/trinityrnaseq-v2                                                                                                             .13.2/sample_data/test_Trinity_Assembly/reads.left.fq.gz --right /opt/data/home/                                                                                                             julie/julie_software/trinityrnaseq-v2.13.2/sample_data/test_Trinity_Assembly/rea                                                                                                             ds.right.fq.gz --pairs_together  --PARALLEL_STATS   died with ret 7424 at /opt/d                                                                                                             ata/home/julie/julie_software/trinityrnaseq-v2.13.2/Trinity line 2863.
        main::process_cmd("/opt/data/home/julie/julie_software/trinityrnaseq-v2.                                                                                                             13.2/uti"...) called at /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.                                                                                                             2/Trinity line 3416
        main::normalize("/opt/data/home/julie/julie_software/trinityrnaseq-v2.13                                                                                                             .2/sam"..., 200, ARRAY(0x7f70ccaa5070), ARRAY(0x7f70cce42700)) called at /opt/da                                                                                                             ta/home/julie/julie_software/trinityrnaseq-v2.13.2/Trinity line 3356
        main::run_normalization(200, ARRAY(0x7f70ccaa5070), ARRAY(0x7f70cce42700                                                                                                             )) called at /opt/data/home/julie/julie_software/trinityrnaseq-v2.13.2/Trinity l                                                                                                             ine 1394

**Comment by lebelm** [comment]
Hello,
I know this issue is old, but I got the exact same error in trinityrnaseq-v2.15.1:


```
-------------------------------------------
----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

CMD: jellyfish count -t 8 -m 25 -s 100000000  --canonical  single.fa
CMD finished (41 seconds)
CMD: jellyfish histo -t 8 -o jellyfish.K25.min2.kmers.fa.histo mer_counts.jf
CMD finished (3 seconds)
CMD: jellyfish dump -L 2 mer_counts.jf > jellyfish.K25.min2.kmers.fa
CMD finished (7 seconds)
CMD: touch jellyfish.K25.min2.kmers.fa.success
CMD finished (0 seconds)
-generating stats files
CMD: /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads single.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > single.fa.K25.stats
bash: line 1: /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/..//Inchworm/bin/fastaToKmerCoverageStats: No such file or directory
```
and then more error lines as the process dies:
```
Error, cmd: /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads single.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > single.fa.K25.stats died with ret 32512 at /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/insilico_read_normalization.pl line 807.
Error, cmd: /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/insilico_read_normalization.pl --seqType fq --JM 20G  --max_cov 200 --min_cov 1 --CPU 8 --output /home/marie/mutation/ML2_rRNA_assembly_and_mapping/Trinity_assembly/trinity_out_dir/insilico_read_normalization --max_CV 10000  --single /home/marie/mutation/ML2_rRNA_assembly_and_mapping/Trinity_assembly/../../ML1_Test2_STAR_L50-1/Unmapped.out.mate1.fastq died with ret 512 at /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/Trinity line 2919.
        main::process_cmd("/omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/util/in"...) called at /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/Trinity line 3472
        main::normalize("/home/marie/mutation/ML2_rRNA_assembly_and_mapping/Trinity_as"..., 200, ARRAY(0x560be1fdd118)) called at /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/Trinity line 3412
        main::run_normalization(200, ARRAY(0x560be1fdd118)) called at /omics-storage/lab-solana/softw/trinityrnaseq-v2.15.1/Trinity line 1455
```

It seems the issue is that the path to get the script "fastaToKmerCoverageStats" is wrong as the directory that contains it is called "src" and not "bin"
In other oword it searches ... trinityrnaseq-v2.15.1/util/..//Inchworm/bin/fastaToKmerCoverageStats 
Instead of the correct  ... trinityrnaseq-v2.15.1/util/..//Inchworm/src/fastaToKmerCoverageStats

As the OP managed to rn this successfully with Singularity, I might try it too, the version might not contain this error

Best,
Marie
