### ISSUE TITLE
Allow sample_data regression tests to be run outside TRINITY_HOME

### ISSUE THREAD

**Issue by nathanweeks** [trinityrnaseq/trinityrnaseq#109]
I've had to run the Trinity regression tests on a cluster where I don't have write access to the sample_data directory. In this case---and I     would suspect it's frequently the case---Trinity was also installed on a file system dedicated for software, where heavy I/O is discouraged, as  opposed to faster/parallel file systems where assemblies are done. It would be great if the Trinity regression tests could be copied to another  directory before running. I worked around this for the default regression tests (those run by "make test") in Trinity 2.1.1 by modifying the scripts to look for utilities/libraries with respect to the TRINITY_HOME environment variable; i.e.:

```
find sample_data-2.1.1/ -name '*.sh' -exec sed -i.orig 's#\.\./\.\./\(\.\./\)*#$TRINITY_HOME/#' {} +
find sample_data-2.1.1/ -name Makefile -exec sed -i.orig 's#\.\./\.\./\(\.\./\)*#$$TRINITY_HOME/#' {} +
sed -i.orig -e 's#use lib ("$FindBin::Bin/\.\./\.\./PerlLib");#use lib ("$ENV{TRINITY_HOME}/PerlLib");#' -e 's#$FindBin::Bin/\.\./\.\./util#$ENV{TRINITY_HOME}/util#' sample_data-2.1.1/test_align_and_estimate_abundance/align_and_estimate_tester.pl
```

If the user isn't running the regression tests from within the Trinity installation directory, then they're responsible for setting TRINITY_HOME to the pathname of the Trinity installation directory. 

The Makefile could be modified to set TRINITY_HOME such that if the user doesn't set TRINITY_HOME, then it's assumed that the sample_data directory lies within TRINITY_HOME (as is currently the case); e.g.:

```
--- Makefile.orig   2016-03-01 16:06:58.000000000 -0600
+++ Makefile    2016-03-21 08:19:49.000000000 -0500
@@ -11,7 +11,7 @@
 test:
    @for i in $(DIRS); do \
    echo "Running example in $$i..."; \
-   (cd $$i; $(MAKE) test) || exit $$?; done
+   (cd $$i; TRINITY_HOME=$${TRINITY_HOME:-$${PWD}/../../} $(MAKE) test) || exit $$?; done


 clean:
```

There are probably other (better) ways of doing it, but that's one suggestion.

**Comment by brianjohnhaas** [comment]
I think we'll have installers run the tests before installation.  The tests have been reorganized to reduce bloat, too.
