### ISSUE TITLE
Improper pairs in SAM_nameSorted_to_uniq_count_stats.pl

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#11]
(From Dr. Ken Field)

To determine if your paired-end data is really not mapping properly onto your assembly, or if you are having an issue with overlapping reads:

Run samtools stats on the BAM file from bowtie_PE_separate_then_join.pl:
samtools stats bowtie_out.coordSorted.bam > bowtie_out.coordSorted.bam.stats
This generates all kinds of data about the bam file. To extract the summary, use `grep ^SN | cut -f 2-` on that file.
The key information is at the bottom of this section:

SN insert size average: 194.4
SN insert size standard deviation: 77.0
SN inward oriented pairs: 24702869
SN outward oriented pairs: 0
SN pairs with other orientation: 0
SN pairs on different chromosomes: 0

This data had no outward oriented pairs or pairs on different components, which conflicts with the improper pairs stat from bowtie_PE_separate_then_join.pl which had 13.89% of the pairs classified as "improper" and less than 80% "proper". 

The discrepancy is caused by having 100-base pair reads on 200 base fragments. The standard deviation of the insert size shows that there are a significant number of reads with a length of less than 100 bases and if one of the reads gets quality-trimmed to less than the fragment size then that read pair will be flagged as improper because the ends will overlap. 

Modify the script to classify those reads separately, or even just put them in the "proper" category (although that might be confusing if someone isn't aware of the change and has run both versions on the same data set).

**Comment by brianjohnhaas** [comment]
I would add that if your read lengths overlap with your fragment lengths, most of the 'improper pairs' may in fact just be overlapping reads. In my case, I had 200 basepair fragments and 100 basepair reads and I found that almost all of the improper pairs were actually just overlaps.

It would be great if bowtie_PE_separate_then_join.pl would have a separate category of overlapping reads versus truly improper pairs (i.e. pairs that map to the same contig but in the wrong orientation relative to each other).

Ken
Ken Field, Ph.D.
Associate Professor of Biology
Program in Cell Biology/Biochemistry
Bucknell University
Room 203A Biology Building

**Comment by brianjohnhaas** [comment]
done
