### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by yannickwurm** [trinityrnaseq/trinityrnaseq#110]
Running `make` on the latest release source code, I get a bunch of warnings when compiling. Is it safe to ignore these? Some examples: 
- `./analysis/GraphFromFasta.cc:1778:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]`
- `DeBruijnGraph.cpp:306:18: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]`
- `sub_commands/count_main.cc:248:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]`

Note that compilation seems to complete successfully, and all unit tests seem to be running properly. 

Thanks!

**Comment by brianjohnhaas** [comment]
should be fine.
