### ISSUE TITLE
contig sense dependent RSEM

### ISSUE THREAD

**Issue by PolinaN** [trinityrnaseq/trinityrnaseq#111]
Hi! I'm using not strand specific libraries and not specifying any 'SS_lib_type' during assembly or alignment. So, here is the problem:
For all reverse sense contigs (for example, all those starting with many T’s, the reverse poly-A tail), the expression is estimated correctly. All other contigs (those ending with a poly-A tail) are heavily underestimated.
Any recommendations?
Thank you,
Polina

**Comment by PolinaN** [comment]
here is the command for RSEM counts:

/software/shared/apps/x86_64/trinity/2.0.4/util/align_and_estimate_abundance.pl --transcripts Trinity-cdhit --left $raw/left.fq --right $raw/right.fq --SS_lib_type FR  --seqType fq --thread_count 8 --max_ins_size 500 --output_dir Trinity_estimate --trinity_mode --est_method RSEM --aln_method bowtie --prep_reference

**Comment by brianjohnhaas** [comment]
I suggest trying some of the other abundance estimation methods and see how
they compare, as in:

 https://groups.google.com/forum/#!topic/trinityrnaseq-users/9qZ2DCLUv0c


On Wed, Mar 23, 2016 at 11:58 PM, PolinaN <notifications@github.com> wrote:

> here is the command for RSEM counts:
>
> /software/shared/apps/x86_64/trinity/2.0.4/util/
> align_and_estimate_abundance.pl --transcripts Trinity-cdhit --left
> $raw/left.fq --right $raw/right.fq --SS_lib_type FR --seqType fq
> --thread_count 8 --max_ins_size 500 --output_dir Trinity_estimate
> --trinity_mode --est_method RSEM --aln_method bowtie --prep_reference
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/111#issuecomment-200651122>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
