### ISSUE TITLE
passing arguments to butterfly

### ISSUE THREAD

**Issue by macmanes** [trinityrnaseq/trinityrnaseq#118]
using 2.2.0

```
Trinity --seqType fq --max_memory 300G --trimmomatic --SS_lib_type RF \
--left 3te.1.fq.gz --right 3te.2.fq.gz --CPU 10 \
--output trinity_HPG_atlas --inchworm_cpu 10 \
--full_cleanup \
--bflyGCThreads 20 --bflyHeapSpaceMax 40G
```

The Xmx and GC threads settings do not parse to Butterfly - you still get GCthreads=2 and Xmx=4G

**Comment by ricardojp** [comment]
I was having a similar problem:
after my first attempt to run Trinity with standard memory setting, the run failed during Butterfly. I tried adding the commands --bflyHeapSpaceMax 12G --bflyGCThreads 1. At first, I ran these new commands into the same output folder, so Trinity would jump the steps that worked before. Yet, I noticed that the new memory commands were not being executed during the "new" Butterfly.
When I ran the same commands into a new folder, the new memory setting were applied and my run finished successfully!

Is it possible that some of the files written before Butterfly during a failed rung do not allow new commands to apply?

**Comment by brianjohnhaas** [comment]
That sounds right...   Once the reads are partitioned and the assembly
commands are written out, a checkpoint is set.  There's no easy way right
now to update the butterfly parameters for just the previously failed
jobs.  I'll comment on the harder way to do it shortly on the google groups
thread.

~b

On Mon, Apr 4, 2016 at 3:21 AM, ricardojp <notifications@github.com> wrote:

> I was having a similar problem:
> after my first attempt to run Trinity with standard memory setting, the
> run failed during Butterfly. I tried adding the commands --bflyHeapSpaceMax
> 12G --bflyGCThreads 1. At first, I ran these new commands into the same
> output folder, so Trinity would jump the steps that worked before. Yet, I
> noticed that the new memory commands were not being executed during the
> "new" Butterfly.
> When I ran the same commands into a new folder, the new memory setting
> were applied and my run finished successfully!
>
> Is it possible that some of the files written before Butterfly during a
> failed rung do not allow new commands to apply?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/118#issuecomment-205171028>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
