### ISSUE TITLE
long read error

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#119]
Magdy has examples w/ null ptrs

**Comment by bimbam23** [comment]
Hi Brian,
do you think you will fix the long_read error in the next release? 
Cheers Jochen

**Comment by brianjohnhaas** [comment]
I'll aim to do this.

On Fri, Jun 10, 2016 at 10:33 AM, Jochen Bick <notifications@github.com>
wrote:

> Hi Brian,
> do you think you will fix the long_read error in the next release?
> Cheers Jochen
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/119#issuecomment-225123885>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX37mQjWrSq7kQIi-25Po9CI_TENyks5qKSFmgaJpZM4H_Yr9>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
long read support fully revised in latest release.
