### ISSUE TITLE
Remove git code from htslib before shipping

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#120]
The HTSLib Makefile assumes that it is being built from a GIT repository. There are lines in the file that say "If you don't have GNU Make and/or are not building from a Git repository, comment out this conditional." Those lines should be commented out. This will fix the issue of "make: git: Command not found" that comes up on some systems.

**Comment by brianjohnhaas** [comment]
awesome!  nice job hunting that down!

~b

On Mon, Apr 4, 2016 at 3:28 PM, Ben Fulton <notifications@github.com> wrote:

> The HTSLib Makefile assumes that is is being built from a GIT repository.
> There are lines in the file that say "If you don't have GNU Make and/or are
> not building from a Git repository, comment out this conditional." Those
> lines should be commented out. This will fix the issue of "make: git:
> Command not found" that comes up on some systems.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/120>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by jmarshall** [comment]
Not really… the HTSlib Makefile checks whether it is being built from a git repository (using GNU Make-specific make functions to do so).

The bleeding-edge _htslib.github.Aug182015.tar.gz_ you've tarred up and included here contains a _.git_ subdirectory so in fact **is a git repository**, and so the makefile reasonably enough runs `git describe` on it.

I suggest you replace both _htslib-1.2.1.tar.bz2_ and _htslib.github.Aug182015.tar.gz_ with the [current 1.3.1 release](https://github.com/samtools/htslib/releases/latest) instead, which further improves on your ad hoc one and is packaged correctly—without a _.git_ subdirectory.

Even better than bundling htslib, you might like to make it possible to build against an already-installed or pre-existing separate htslib.

**Comment by brianjohnhaas** [comment]
Ben - further thoughts on this?

**Comment by brianjohnhaas** [comment]
replaced w/ latest samtools v1.3
