### ISSUE TITLE
Does Trinity has precompiled version?

### ISSUE THREAD

**Issue by zhaoletian** [trinityrnaseq/trinityrnaseq#121]
I want to use trinity on the server. Since the server's gcc java version is lower than the trinity requires. I wonder if there is any way to solve this problem.

**Comment by benfulton** [comment]
Hi,

If I understand you correctly, the version of Java installed on your server is less than 1.7, the minimum Java required by Trinity 2.2. You can try using your version of Java by adding the command line option "--bypass_java_version_check" but notice that we cannot help you if there are issues with running it this way. If that doesn't work, you can try installing a later version of Java to your own user directory and running that instead.

Good luck!

**Comment by zhaoletian** [comment]
Thanks a lot!
I'll try to install java to my own user directory. I've already use the gcc-4.4.3 on the /opt directory on the server after contact with the administrator of the server.
