### ISSUE TITLE
v2.2.0 fails to compile

### ISSUE THREAD

**Issue by jmandrie** [trinityrnaseq/trinityrnaseq#122]
V2.2.0 fails to compile for me. I get an error almost immediately (see below). I am not especially computer-saavy, but v2.1.1 compiles fine for me, and I have compiled and used v2.0.6 in the past with no trouble. Could you please look into this error? If it is not a bug, and instead a special compatibility requirement for other programs, could you make note on the install page (like you already have with gcc)? Thanks!

make[1]: Entering directory `user_path/trinityrnaseq-2.2.0/Inchworm'
Making install in src
make[2]: Entering directory `user_path/trinityrnaseq-2.2.0/Inchworm/src'
g++ -ansi -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2  -software_path/java/7u17/Linux/RHEL6/x86_64/lib/ -software_path/python/2.7.2/Linux/RHEL6/x86_64/lib/ -o inchworm Fasta_entry.o IRKE_run.o sequenceUtil.o IRKE.o KmerCounter.o string_util.o Fasta_reader.o stacktrace.o argProcessor.o  
sequenceUtil.o: In function `_M_check':
software_path/gcc/4.9.1/Linux/RHEL6/x86_64/include/c++/4.9.1/bits/basic_string.h:324: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
collect2: ld returned 1 exit status
make[2]: *** [inchworm] Error 1
make[2]: Leaving directory `user_path/trinityrnaseq-2.2.0/Inchworm/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `user_path/trinityrnaseq-2.2.0/Inchworm'
make: *** [inchworm_target] Error 2

**Comment by benfulton** [comment]
Hi,

Nothing has changed in Inchworm from the previous version that would indicate this. The most common reason for this error is a library or file that has been compiled with a different version of gcc. Can you try doing a "make clean" at the root directory and then running "make" again?

**Comment by jmandrie** [comment]
I tried this and "make clean" also gave me an error message. I ended up installing it in a different, shared location (rather than locally) and didn't have any trouble with that compilation. 

Thank you for your help!
