### ISSUE TITLE
Trinity2.2 - perl not built to support thread

### ISSUE THREAD

**Issue by liaguiro** [trinityrnaseq/trinityrnaseq#123]
Hello,

I tested the installation but it failed (Trinity2.2). The message that I get is below. Can you please help me fix this problem? 
../../Trinity --seqType fq --max_memory 2G --left reads.left.fq.gz,reads2.left.fq.gz --right reads.right.fq.gz,reads2.right.fq.gz --SS_lib_type RF --CPU 4 --no_cleanup --normalize_reads
This Perl not built to support threads
Compilation failed in require at ../../Trinity line 5.
BEGIN failed--compilation aborted at ../../Trinity line 5.

**Comment by brianjohnhaas** [comment]
Hi,

You'll need perl built with multithreading support.  There's no way around
it for now.

best,

~b

On Fri, Apr 8, 2016 at 6:23 PM, liaguiro <notifications@github.com> wrote:

> Hello,
>
> I tested the installation but it failed (Trinity2.2). The message that I
> get is below. Can you please help me fix this problem?
> ../../Trinity --seqType fq --max_memory 2G --left
> reads.left.fq.gz,reads2.left.fq.gz --right
> reads.right.fq.gz,reads2.right.fq.gz --SS_lib_type RF --CPU 4 --no_cleanup
> --normalize_reads
> This Perl not built to support threads
> Compilation failed in require at ../../Trinity line 5.
> BEGIN failed--compilation aborted at ../../Trinity line 5.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/123>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
