### ISSUE TITLE
kallisto error

### ISSUE THREAD

**Issue by bprabin** [trinityrnaseq/trinityrnaseq#125]
I tried to run kallisto but get followling error. I need a help

prabinb@biolab:/data/Prabin_trinity/Jonsok_complete_trinity> /data/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts Trinity.fasta --seqType fq --left Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz,Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz,Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz --right Jonsok10daysR1CGATGTR2.fastq.P.qtrim.gz,Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz,Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz --est_method kallisto --trinity_mode --prep_reference --output_dir J96KCMD: kallisto quant -i /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.kallisto_idx  -o J96K <(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz) <(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR2.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz)

Error: file not found /dev/fd/63,/dev/fd/62,/dev/fd/61
Error: file not found /dev/fd/60,/dev/fd/59,/dev/fd/58

Usage: kallisto quant [arguments] FASTQ-files

Required arguments:
-i, --index=STRING            Filename for the kallisto index to be used for
                              quantification
-o, --output-dir=STRING       Directory to write output to

Optional arguments:
    --bias                    Perform sequence based bias correction
-b, --bootstrap-samples=INT   Number of bootstrap samples (default: 0)
    --seed=INT                Seed for the bootstrap sampling (default: 42)
    --plaintext               Output plaintext instead of HDF5
    --single                  Quantify single-end reads
-l, --fragment-length=DOUBLE  Estimated average fragment length
-s, --sd=DOUBLE               Estimated standard deviation of fragment length
                              (default: value is estimated from the input data)
-t, --threads=INT             Number of threads to use (default: 1)
    --pseudobam               Output pseudoalignments in SAM format to stdout
Error, cmd: kallisto quant -i /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.kallisto_idx  -o J96K <(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz) <(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR2.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz),<(gunzip -c /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz) died with ret: 256 at /data/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl line 714.

**Comment by brianjohnhaas** [comment]
Hi

It wants a single file, not a set of files.  If these all correspond to the
same condition, then you'll want to merge them into single files.  If they
are different conditions, you'll want to run kallisto on each pair
separately.

If kallisto has built-in functionality to handle multiple files, please let
me know and I'll see if we can support it somehow.

best,

~b

On Mon, Apr 11, 2016 at 7:45 AM, bprabin <notifications@github.com> wrote:

> I tried to run kallisto but get followling error. I need a help
>
> prabinb@biolab:/data/Prabin_trinity/Jonsok_complete_trinity>
> /data/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl
> --transcripts Trinity.fasta --seqType fq --left
> Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz,Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz,Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz
> --right
> Jonsok10daysR1CGATGTR2.fastq.P.qtrim.gz,Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz,Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz
> --est_method kallisto --trinity_mode --prep_reference --output_dir J96KCMD:
> kallisto quant -i
> /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.kallisto_idx -o
> J96K <(gunzip -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz)
> <(gunzip -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR2.fastq.P.qtr
> im.gz),<(gunzip -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz)
>
> Error: file not found /dev/fd/63,/dev/fd/62,/dev/fd/61
> Error: file not found /dev/fd/60,/dev/fd/59,/dev/fd/58
>
> Usage: kallisto quant [arguments] FASTQ-files
>
> Required arguments:
> -i, --index=STRING Filename for the kallisto index to be used for
> quantification
> -o, --output-dir=STRING Directory to write output to
>
> Optional arguments:
> --bias Perform sequence based bias correction
> -b, --bootstrap-samples=INT Number of bootstrap samples (default: 0)
> --seed=INT Seed for the bootstrap sampling (default: 42)
> --plaintext Output plaintext instead of HDF5
> --single Quantify single-end reads
> -l, --fragment-length=DOUBLE Estimated average fragment length
> -s, --sd=DOUBLE Estimated standard deviation of fragment length
> (default: value is estimated from the input data)
> -t, --threads=INT Number of threads to use (default: 1)
> --pseudobam Output pseudoalignments in SAM format to stdout
> Error, cmd: kallisto quant -i
> /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.kallisto_idx -o
> J96K <(gunzip -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR1.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR1.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR1.fastq.P.qtrim.gz)
> <(gunzip -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR1CGATGTR2.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR2CAGATCR2.fastq.P.qtrim.gz),<(gunzip
> -c
> /data/Prabin_trinity/Jonsok_complete_trinity/Jonsok10daysR3GTGAAAR2.fastq.P.qtrim.gz)
> died with ret: 256 at /data/trinityrnaseq-2.1.1/util/
> align_and_estimate_abundance.pl line 714.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/125>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by bprabin** [comment]
Hi,
all sets of files are of same condition. How to merge all sets of files into set of files. Also  I have done same process with RSEM it worked very good and completed with good result.

I was also trying to run first prepare reference seperately but it gives a error like this

prabinb@biolab:/data/Prabin_trinity/Jonsok_complete_trinity> /data/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts Trinity.fasta --seqType fq --est_method kallisto --trinity_mode --prep_reference --output_dir J96KCMD: kallisto index -i /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.kallisto_idx /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta

[build] loading fasta file /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 2325 target sequences
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 3085266 contigs and contains 192841363 k-mers 

CMD: /data/trinityrnaseq-2.1.1/util/support_scripts/kallisto_trans_to_gene_results.pl J96K/abundance.tsv /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.gene_trans_map > J96K/abundance.tsv.genes
Error, cannot open file J96K/abundance.tsv at /data/trinityrnaseq-2.1.1/util/support_scripts/kallisto_trans_to_gene_results.pl line 31.
Error, cmd: /data/trinityrnaseq-2.1.1/util/support_scripts/kallisto_trans_to_gene_results.pl J96K/abundance.tsv /data/Prabin_trinity/Jonsok_complete_trinity/Trinity.fasta.gene_trans_map > J96K/abundance.tsv.genes died with ret: 512 at /data/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl line 714.

**Comment by brianjohnhaas** [comment]
I'm not sure what's going on here.  If it's still an issue, let's pick it up on the google forum - which we use for tech support:

https://groups.google.com/forum/#!forum/trinityrnaseq-users
