### ISSUE TITLE
insilico_read_normalization/tmp_normalized_reads

### ISSUE THREAD

**Issue by thkitapci** [trinityrnaseq/trinityrnaseq#127]
Hi,
After my trinity run is completed using the command line
(Trinity version: v2.1.1)
`Trinity --seqType fq --max_memory $MEM --left $LEFT_READS --right $RIGHT_READS --CPU $NUM -- normalize_reads --trimmomatic --output $output_dir`

I have a folder called insilico_read_normalization/tmp_normalized_reads this folder's content is huge (about 1 TB) is there any reason for me to keep this folder or can I safely delete this after the run is completed ?

Thanks!
Hamdi

**Comment by brianjohnhaas** [comment]
Once the trinity_out_dir/both.fa file is written, the normalization folder
outputs should no longer be needed.

On Thu, Apr 14, 2016 at 8:13 PM, Tevfik Hamdi Kitapci <
notifications@github.com> wrote:

> Hi,
> After my trinity run is completed using the command line
> (Trinity version: v2.1.1)
> Trinity --seqType fq --max_memory $MEM --left $LEFT_READS --right
> $RIGHT_READS --CPU $NUM -- normalize_reads --trimmomatic --output
> $output_dir
>
> I have a folder called insilico_read_normalization/tmp_normalized_reads
> this folder's content is huge (about 1 TB) is there any reason for me to
> keep this folder or can I safely delete this after the run is completed ?
>
> Thanks!
> Hamdi
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/127>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by thkitapci** [comment]
Thanks for the reply. What about the folder "read_partitions" is there any use for this after the run is completed ?

Thanks

**Comment by brianjohnhaas** [comment]
Once the full run is completed, all you need is the Trinity fasta file.

If you use the --full_cleanup option, it'll take care of the cleaning for
you, though this happens at the very end of the run.

~b

On Fri, Apr 15, 2016 at 12:58 PM, Tevfik Hamdi Kitapci <
notifications@github.com> wrote:

> Thanks for the reply. What about the folder "read_partitions" is there any
> use for this after the run is completed ?
>
> Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/127#issuecomment-210546591>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
