### ISSUE TITLE
decrease verbosity in recursive butterfly phase

### ISSUE THREAD

**Issue by macmanes** [trinityrnaseq/trinityrnaseq#13]
While impressive to non-computation colleagues, Bfly in 2.02  is __SO__ verbose that it is impossible to garner any information from it as it's whizzing past you on the screen. Should seriously consider limiting this info to the counted (34 of 345 complete) or something like that...

**Comment by brianjohnhaas** [comment]
My bad.... ;)    I'll take care of this.

On Fri, Jan 30, 2015 at 9:01 AM, Matt MacManes <notifications@github.com>
wrote:

> While impressive to non-computation colleagues, Bfly in 2.02 is *SO*
> verbose that it is impossible to garner any information from it as it's
> whizzing past you on the screen. Should seriously consider limiting this
> info to the counted (34 of 345 complete) or something like that...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/13>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Hi Matt, 

I think it's only verbose when you run the sample data set, but it's not verbose (at all) in a normal run.  I'll just turn off the verbosity for the default sample data execution.

best,

~brian

**Comment by brianjohnhaas** [comment]
actually, I think I understand the issue. It's not a butterfly thing but a Trinity thing.  Where we used to just run butterfly, it's now running full Trinity, and you see all the output from each of the Trinity executions.  What we need is a less verbose Trinity... not a problem, will work on that soon.

**Comment by macmanes** [comment]
Yep, that's exactly it. Clearly this is an enhancement, so there may be more pressing issues to deal with before this..

**Comment by brianjohnhaas** [comment]
Done.  The system is now very quiet, providing progress monitoring and a little bit of logging.
