### ISSUE TITLE
very similar sequences defined as separate genes

### ISSUE THREAD

**Issue by wangyingBena** [trinityrnaseq/trinityrnaseq#131]
I assembled my RNA-seq reads with trinityrnaseq-2.2.0 and found something strange in my Trinity.fasta file.
These two sequences below seem to be defined as separate genes, but they differ only by two SNP. Any idea how this could have happened ? How to solve this problem? 
By the way, the same problem exists when I use trinityrnaseq-2.0.6 and trinityrnaseq-2.2.0 give me more genes and transcripts. I am also attaching my stats.

>TRINITY_DN66_c0_g1_i1 len=419 path=[851:0-195 852:196-224 853:225-418] [-1, 851, 852, 853, -2]
GTTAATTTGGATAGGGACAGGAAGACTCATTTTCCACATAAAAAATAAACATTAAGTCAA
GCAACCTTCATGTTCACTACAGAATAAGTAAAACCGAACCAGACATGCCGTGCCGAGTGA
AGTCTGAAATCGGGCCAATTTTATCACGTGTGAAGCCGGGCTGAGCTCAAACTAAAAAAT
AGATGAAGAAACACGGTCCAAGCTTGTGTTAGACCAGATCAGGTAATCAGACTTTCGAAC
CGGCCCAACGACATCCCTAATTTTGTGTGATATATAGTTTATGCATATGTTTTCACCTCA
TCTGCATTGCGAGATCGAGGACATGCAGTATTGCATGTATATACATATATATATATAATT
TCGAAGGGATCCTCTCTTAATTTACCTGGAAGGCTGTGAACTTGAAAGGGCTTTCTGGA
>TRINITY_DN66_c0_g2_i1 len=419 path=[854:0-195 855:196-224 856:225-418] [-1, 854, 855, 856, -2]
GTTAATTTGGATAGGGACAGGAAGACTCATTTTCCACATAAAAAATAAACATTAAGTCAA
GCAACCTTCATGTTCACTACAGAATAAGTAAAACCGAACCAGACATGCCGTGCCGAGTGA
AGTCTGAAATCGGGCCAATTTTATCACGTGTGAAGCCGGGCTGAGCTCAAACTAAAAAAT
AGATGAAGAAACACGGCCCAAACTTGTGTTAGACCAGATCAGGTAATCAGACTTTCGAAC
CGGCCCAACGACATCCCTAATTTTGTGTGATATATAGTTTATGCATATGTTTTCACCTCA
TCTGCATTGCGAGATCGAGGACATGCAGTATTGCATGTATATACATATATATATATAATT
TCGAAGGGATCCTCTCTTAATTTACCTGGAAGGCTGTGAACTTGAAAGGGCTTTCTGGA
#### trinityrnaseq-2.2.0

Item  genes        transcripts
Total_number        129,284 183,213
N10(bp) 2,120   2,196
N20(bp) 1,422   1,552
N30(bp) 954     1,123
N40(bp) 647     802
N50(bp) 476     588
Median_length(bp)       309     337
Average_length(bp)      452.65  508.07
Total_length(bp)        58,520,080      93,084,858
#### trinityrnaseq-2.0.6

Item    genes        transcripts
Total_number     108,504 162,223
N10(bp) 2,230   2,285
N20(bp) 1,543   1,659
N30(bp) 1,077   1,229
N40(bp) 745     905
N50(bp) 538     663
Median_length(bp)       337     371
Average_length(bp)      504.96  562.95
Total_length(bp)        54,789,755      91,324,201

**Comment by brianjohnhaas** [comment]
This should be fixed in the latest release.
