### ISSUE TITLE
Build Transcript and Gene Expression Matrices

### ISSUE THREAD

**Issue by MassiMolari** [trinityrnaseq/trinityrnaseq#132]
Hi,
i'm using this command:

> trinityrnaseq-2.2.0/util/abundance_estimates_to_matrix.pl --est_method kallisto --out_prefix trans_counts --name_sample_by_basedir sampleA/abundance.tsv sampleB/abundance.tsv 

It produced an empty trans_counts.TMM.EXPR.matrix, due to this error:

> Error in library(edgeR) : there is no package called 'edgeR'

How can I solve this?

**Comment by brianjohnhaas** [comment]
Hi,

You just need to install edgeR  (and qvalue)

https://bioconductor.org/packages/release/bioc/html/edgeR.html
and
https://bioconductor.org/packages/release/bioc/html/qvalue.html

just a few commands to type in an R window, as per instructions.


best,

~b

On Thu, Apr 28, 2016 at 12:01 PM, Massimiliano Molari <
notifications@github.com> wrote:

> Hi,
> i'm using this command:
>
> trinityrnaseq-2.2.0/util/abundance_estimates_to_matrix.pl --est_method
> kallisto --out_prefix trans_counts --name_sample_by_basedir
> sampleA/abundance.tsv sampleB/abundance.tsv
>
> It produced an empty trans_counts.TMM.EXPR.matrix, due to this error:
>
> Error in library(edgeR) : there is no package called 'edgeR'
>
> How can I solve this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/132>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by MassiMolari** [comment]
Hi Brian,
actually I have already tried to install these packages, but I had some problems to install packages from bioconductor... I do not why the normal "source" command does not work.
Thanks for your help!
