### ISSUE TITLE
Suspected out of memory

### ISSUE THREAD

**Issue by Wenwen012345** [trinityrnaseq/trinityrnaseq#1329]
DEAR Professor BRAIN. @brianjohnhaas 

Hello, first of all I would like to pay a short tribute to you; it is you who have worked so diligently to create such a great tool. I have often been favoured by you so that my research has been able to advance. Our paper applying Trinity is still under review and may be published in the future; but it certainly could not have been done without your help!

Now I would like to ask my question. Although I consider myself a veteran of Trinity use, this time I am still a bit confused about the problems I encountered. And it seems to be a bit more difficult to find similar problems due to the current clutter in the problem library. Sorry for the interruption.

The problem namely is that I seem to be running over the memory limit (135G RAM), which surprises me; as I've rarely encountered similar problems lately. The problem has also been rarely encountered in recent times in Trinity runs of closely related species. My species genome is ~800M and then the transcriptome file size is about 10G*2 with double-ended sequencing. I have also tried both the separate double-ended file and the "samples_file" method (which contains 10 transcriptomes), and neither of them work. Is there anything that can be done if there really isn't enough memory? If not, I may just try to get a different server with 200G of RAM.

![屏幕截图 2023-08-05 223333](https://github.com/trinityrnaseq/trinityrnaseq/assets/63379795/598bf93f-ca2b-44c3-a5cf-2a8e9aefcb56)
The memory change curve seems to indicate that there is indeed not enough memory.

```

(tri) admin210@admin210-ProLiant-DL380-Gen9:~/w/BL1$ Trinity --seqType fq --max_memory 135G --left hua1.p1.fq --right hua1.p2.fq  --CPU 35  --full_cleanup


     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

    Trinity-v2.13.2



Left read files: $VAR1 = [
          'hua1.p1.fq'
        ];
Right read files: $VAR1 = [
          'hua1.p2.fq'
        ];
Trinity version: Trinity-v2.13.2
** NOTE: Latest version of Trinity is Trinity-v2.15.1, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

Saturday, August 5, 2023: 22:32:46	CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/support_scripts/ExitTester.jar 0
Saturday, August 5, 2023: 22:32:46	CMD: java -Xmx4g -XX:ParallelGCThreads=2  -jar /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/support_scripts/ExitTester.jar 1


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

---------------------------------------------------------------
------------ In silico Read Normalization ---------------------
-- (Removing Excess Reads Beyond 200 Coverage --
---------------------------------------------------------------

# running normalization on reads: $VAR1 = [
          [
            '/home/admin210/w/BL1/hua1.p1.fq'
          ],
          [
            '/home/admin210/w/BL1/hua1.p2.fq'
          ]
        ];


Saturday, August 5, 2023: 22:32:47	CMD: /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl --seqType fq --JM 135G  --max_cov 200 --min_cov 1 --CPU 35 --output /home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization --max_CV 10000  --left /home/admin210/w/BL1/hua1.p1.fq --right /home/admin210/w/BL1/hua1.p2.fq --pairs_together  --PARALLEL_STATS  
-prepping seqs
Converting input files. (both directions in parallel)left file exists, nothing to doright file exists, nothing to doDone converting input files.-kmer counting.
-------------------------------------------
----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

CMD: jellyfish count -t 35 -m 25 -s 19029257507  --canonical  both.fa
Error, cmd: jellyfish count -t 35 -m 25 -s 19029257507  --canonical  both.fa died with ret 9 at /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl line 795.
Error, cmd: /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl --seqType fq --JM 135G  --max_cov 200 --min_cov 1 --CPU 35 --output /home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization --max_CV 10000  --left /home/admin210/w/BL1/hua1.p1.fq --right /home/admin210/w/BL1/hua1.p2.fq --pairs_together  --PARALLEL_STATS   died with ret 512 at /home/admin210/miniconda3/envs/tri/bin/Trinity line 2863.
	main::process_cmd("/home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/in"...) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 3416
	main::normalize("/home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization", 200, ARRAY(0x1a29ca8), ARRAY(0x1a29cc0)) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 3356
	main::run_normalization(200, ARRAY(0x1a29ca8), ARRAY(0x1a29cc0)) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 1394


```

**Comment by brianjohnhaas** [comment]
Hi Wenwen,

Thanks for the kind words!  I'm glad that Trinity has been mostly
serving you well so far.

To reduce memory requirements here, try setting:

     --max_memory 50G --min_kmer_cov 2

and if it still crashes for out of memory issues, try running with the
additional parameter:

   --no_parallel_norm_stats


Let's see how that goes.

best,

~brian


On Sat, Aug 5, 2023 at 10:46 AM Wenwen ***@***.***> wrote:
>
> DEAR Professor BRAIN. @brianjohnhaas
>
> Hello, first of all I would like to pay a short tribute to you; it is you who have worked so diligently to create such a great tool. I have often been favoured by you so that my research has been able to advance. Our paper applying Trinity is still under review and may be published in the future; but it certainly could not have been done without your help!
>
> Now I would like to ask my question. Although I consider myself a veteran of Trinity use, this time I am still a bit confused about the problems I encountered. And it seems to be a bit more difficult to find similar problems due to the current clutter in the problem library. Sorry for the interruption.
>
> The problem namely is that I seem to be running over the memory limit (135G RAM), which surprises me; as I've rarely encountered similar problems lately. The problem has also been rarely encountered in recent times in Trinity runs of closely related species. My species genome is ~800M and then the transcriptome file size is about 10G*2 with double-ended sequencing. Is there anything that can be done if there really isn't enough memory? If not, I may just try to get a different server with 200G of RAM.
>
>
> The memory change curve seems to indicate that there is indeed not enough memory.
>
> `(tri) ***@***.***:~/w/BL1$ Trinity --seqType fq --max_memory 135G --left hua1.p1.fq --right hua1.p2.fq --CPU 35 --full_cleanup
>
>  ______  ____   ____  ____   ____  ______  __ __
> |      ||    \ |    ||    \ |    ||      ||  |  |
> |      ||  D  ) |  | |  _  | |  | |      ||  |  |
> |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
>   |  |  |    \  |  | |  |  | |  |   |  |  |___, |
>   |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
>   |__|  |__|\_||____||__|__||____|  |__|  |____/
>
> Trinity-v2.13.2
>
> Left read files: $VAR1 = [
> 'hua1.p1.fq'
> ];
> Right read files: $VAR1 = [
> 'hua1.p2.fq'
> ];
> Trinity version: Trinity-v2.13.2
> ** NOTE: Latest version of Trinity is Trinity-v2.15.1, and can be obtained at:
> https://github.com/trinityrnaseq/trinityrnaseq/releases
>
> Saturday, August 5, 2023: 22:32:46 CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/support_scripts/ExitTester.jar 0
> Saturday, August 5, 2023: 22:32:46 CMD: java -Xmx4g -XX:ParallelGCThreads=2 -jar /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/support_scripts/ExitTester.jar 1
>
> ________________________________
>
> -------------- Trinity Phase 1: Clustering of RNA-Seq Reads ---------------------
>
> ________________________________
>
> ------------ In silico Read Normalization ---------------------
> -- (Removing Excess Reads Beyond 200 Coverage --
>
> running normalization on reads: $VAR1 = [
>
>       [
>         '/home/admin210/w/BL1/hua1.p1.fq'
>       ],
>       [
>         '/home/admin210/w/BL1/hua1.p2.fq'
>       ]
>     ];
>
> Saturday, August 5, 2023: 22:32:47 CMD: /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl --seqType fq --JM 135G --max_cov 200 --min_cov 1 --CPU 35 --output /home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization --max_CV 10000 --left /home/admin210/w/BL1/hua1.p1.fq --right /home/admin210/w/BL1/hua1.p2.fq --pairs_together --PARALLEL_STATS
> -prepping seqs
> Converting input files. (both directions in parallel)left file exists, nothing to doright file exists, nothing to doDone converting input files.-kmer counting.
>
> ----------- Jellyfish --------------------
> -- (building a k-mer catalog from reads) --
>
> CMD: jellyfish count -t 35 -m 25 -s 19029257507 --canonical both.fa
> Error, cmd: jellyfish count -t 35 -m 25 -s 19029257507 --canonical both.fa died with ret 9 at /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl line 795.
> Error, cmd: /home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/insilico_read_normalization.pl --seqType fq --JM 135G --max_cov 200 --min_cov 1 --CPU 35 --output /home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization --max_CV 10000 --left /home/admin210/w/BL1/hua1.p1.fq --right /home/admin210/w/BL1/hua1.p2.fq --pairs_together --PARALLEL_STATS died with ret 512 at /home/admin210/miniconda3/envs/tri/bin/Trinity line 2863.
> main::process_cmd("/home/admin210/miniconda3/envs/tri/opt/trinity-2.13.2/util/in"...) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 3416
> main::normalize("/home/admin210/w/BL1/trinity_out_dir/insilico_read_normalization", 200, ARRAY(0x1a29ca8), ARRAY(0x1a29cc0)) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 3356
> main::run_normalization(200, ARRAY(0x1a29ca8), ARRAY(0x1a29cc0)) called at /home/admin210/miniconda3/envs/tri/bin/Trinity line 1394
>
> `
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by Wenwen012345** [comment]
Dear Professor Brain. @brianjohnhaas 
The first method works, that step goes straight through smoothly. Grateful for your help!

Sincerely!
Wen
