### ISSUE TITLE
the bowtie2 support of util/bowtie_PE_separate_then_join.pl need some fixes

### ISSUE THREAD

**Issue by wangyugui** [trinityrnaseq/trinityrnaseq#134]
The bowtie2 support of util/bowtie_PE_separate_then_join.pl need some fixes。
The version of bowtie2 that I tested is 2.2.9.

1)There is no --chunkmbs 512 option for bowtie2.
2)There is no -o option for bowtie2.

**Comment by brianjohnhaas** [comment]
done.  bowtie_PE_separate_then_join.pl is now deprecated and we run bowtie2 directly as part of our recommended protocol.
