### ISSUE TITLE
samtools and other plugins

### ISSUE THREAD

**Issue by nextgenusfs** [trinityrnaseq/trinityrnaseq#136]
So I understand the reason that certain versions of external programs are packaged into `trinity` - with the most obvious being samtools.  However, while samtools-0.1.19 is bundled, the system call to `samtools` in the system scripts defaults to `samtools` in your path, which is typically not going to be the version that you have pre-bundled.  This is now especially problematic as of `samtools 1.3` it no longer supports the command line convention like this: `samtools sort input.bam output.sort` and now the command would look like this `samtools sort -o output.sort input.bam`.  Because of this issue, if you have `samtools 1.3` in your PATH, Trinity will lock up on the first step of Phase II.  

So either the calls to `samtools` from Trinity need to be fixed - or maybe a long term solution would be to fix the output of `samtools sort` to the more modern convention?

Adding something like $SAMTOOLS variable and then linking that to the proper `samtools` version appears to be working for me.  I edited the main `Trinity` script and also the `util/bowtie_PE_spearate_then_join.pl`, and just did a `samtools sort` find/replace with `$SAMTOOLS sort`.

Thanks,
Jon

**Comment by brianjohnhaas** [comment]
I see.  Trinity itself sets the PATH like so:

 $ENV{PATH} = "$ROOTDIR/trinity-plugins/BIN:$ENV{PATH}"; 

so it'll find the proper samtools while running.

The accessory scripts might not do this...   In the case of util/bowtie_PE_separate_then_join.pl, that script has been deprecated and so it's no longer relevant, but if it does turn out to be important for other downstream processes, we'll look into adapting them.

thanks!

~b
