### ISSUE TITLE
How to check how Trinity treated the data.

### ISSUE THREAD

**Issue by VichoDeivis** [trinityrnaseq/trinityrnaseq#137]
Hello. By mistake I assembled paired end with trinity without the "/1" and the "/2" in the reads names. A mate from the lab found the error, we did some assemblies to check and it looks that indeed Trinity treated the data as single end. 

The question is: there is a better way to know if trinity treated the data as SE or PE?

Thanks

**Comment by brianjohnhaas** [comment]
If the read names still match up in the left and right fq files, then the
Butterfly step would have used the pairing info in the final assembly step.
  The only thing you probably lost was using paired-end info to link
inchworm contigs.   You can rerun the assembly if you want, but it's
probably just fine.

~b

On Tue, May 17, 2016 at 1:45 PM, VichoDeivis <notifications@github.com>
wrote:

> Hello. By mistake I assembled paired end with trinity without the "/1" and
> the "/2" in the reads names. A mate from the lab found the error, we did
> some assemblies to check and it looks that indeed Trinity treated the data
> as single end.
>
> The question is: there is a better way to know if trinity treated the data
> as SE or PE?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/137>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
