### ISSUE TITLE
Hybrid assembly

### ISSUE THREAD

**Issue by SimonHegele** [trinityrnaseq/trinityrnaseq#1385]
Hello Trinity Developers,

how is hybrid de novo assembly performed in Trinity? Would be very nice to have a comprehensive explanation. If you have something at hand I would really appreciate you sharing it.

Thanks in advance, best
simon

**Comment by brianjohnhaas** [comment]
Hi,

The hybrid assembly basically uses the Illumina data (exclusively) to construct the de Bruijn graph.  The long reads (need HiFi accuracy) are then used to define paths in the graph along with the Illumina reads during the Butterfly step.  It's still primarily an Illumina-based assembly, but the long reads just help to resolve paths, which is particularly helpful for certain complex isoform graphs.

I hope this helps
