### ISSUE TITLE
Add timestamp to trinity fasta?

### ISSUE THREAD

**Issue by macmanes** [trinityrnaseq/trinityrnaseq#14]
What do people think about adding a time stamp to `Trinity.fasta`, e.g., `Trinity.HHMMSS.fasta`?

Occasionally I am forced to try identify a specific assembly and have a list of `Trinity.fasta`'s and having a time stamp would solve this.. Also, I think it might be a good idea to 'version' assemblies like this as people are making multiple assemblies using different settings. This is less of an issue when people use `-o`, but I know that is not happening.

**Comment by brianjohnhaas** [comment]
Hi Matt,

This issue surfaces with all software tools, and I'm not sure we need a
trinity-specific solution here.  What you can do, though, is to set the
output directory to include the date you're running it, and that could
suffice.

best,

~brian


On Tue, Feb 10, 2015 at 7:59 AM, Matt MacManes <notifications@github.com>
wrote:

> What do people think about adding a time stamp to Trinity.fasta, e.g.,
> Trinity.HHMMSS.fasta?
>
> Occasionally I am forced to try identify a specific assembly and have a
> list of Trinity.fasta's and having a time stamp would solve this.. Also,
> I think it might be a good idea to 'version' assemblies like this as people
> are making multiple assemblies using different settings. This is less of an
> issue when people use -o, but I know that is not happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/14>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by sammyjava** [comment]
I have handy scripts witten which require no tweaking because they simply reference Trinity.fasta. I'd wind up renaming Trinity.date.fasta to Trinity.fasta anyway. One can always rename a file and I use a different trinity_out_dir name if I do an alternative run (Trinity.fasta isn't the only file that chandes!) So IMO - bad idea.

**Comment by brianjohnhaas** [comment]
agreed - we'll not include timestamp in trinity filename.
