### ISSUE TITLE
run_DE_analysis.pl producing wrong foldchange

### ISSUE THREAD

**Issue by RatneshSingh** [trinityrnaseq/trinityrnaseq#140]
Hi,
I am using **run_DE_analysis.pl** to get differentially expressed genes. I am getting one way fold change results irrespective of if I use "ConditionA_vs_ConditionB" or "ConditionB_vs_ConditionA". I am using DESeq2 method using following command:

`/run_DE_analysis.pl --matrix Stem.genes.counts.matrix --method DESeq2 --samples_file StalkNumLow_vs_StalkNumHigh.txt --contrast contrast.txt --output StalkNumLow_vs_StalkNumHigh`
### eg:I ran the script with a set of "SampleA vs SampleB" and later "SampleB vs Sample A". In both cases the the fold change in (.DE.results) is negative while I expect it to be negative in one case and positive in other.

First run "SampleA vs Sample B". 

> id  baseMeanA baseMeanB   baseMean    **log2FoldChange**  lfcSE   stat    pvalue  padj
> DN30148_c5_g19  475.84  72.27   245.23  **-2.70**   0.17    -15.06  2.84e-51 1.81e-46

second run "SampleB vs Sample A". 

> id  baseMeanA baseMeanB   baseMean    **log2FoldChange**  lfcSE   stat    pvalue  padj
> DN30148_c5_g19    108.21  426.94  227.73  **-1.88**   0.43    -4.33   1.49e-05    0.00068
###### 

After bit of troubleshooting, I could fix the fold change issue by changing the following code at line#485 in run_DE_analysis.pl.
`print $ofh "res = results(dds)\n";`
to (changed the code to create a contrast variable and passed it to result())
`print $ofh "contrast=c(\"conditions\",\"$sample_A\",\"$sample_B\")\n";  
  print $ofh "res = results(dds,contrast)\n";                       
`

The script "analyze_diff_expr.pl" to extract up and down genes was also not working properly. In some cases, the outputs  *-UP.subset still contained wrong genes. From the code at Line#385 of  "analyze_diff_expr.pl"  it seems that all the positive fold changes are labelled as UP in ConditionB. 
`if ($log_fold_change > 0) {                         
                        print $condB_up_ofh "$line\t$matrix_counts\n";
                        $countB++;
                        $condB_up_genes{$id} = $rank;
                    }
                    else {
                        print $condA_up_ofh "$line\t$matrix_counts\n";
                        $countA++;
                        $condA_up_genes{$id} = $rank;
                    }`
while from "run_DE_analysis.pl" it seems that fold change in DESeq2 is calculated using formula ConditionA/ConditionB and hence positive values should be considered as UP in condition A and not in ConditionB. 
Changing `$log_fold_change > 0` to `$log_fold_change < 0` in the above code does fix the issue. 

Just wanted to ask your opinion that I am not messing anything else by making these changes.
Thanks
Ratnesh

**Comment by brianjohnhaas** [comment]
Is this the latest version of Trinity?   I'm pretty sure this was dealt
with a while back.

thx,

~b

On Wed, Jun 1, 2016 at 4:10 PM, Ratnesh Singh <notifications@github.com>
wrote:

> Hi,
> I am using *run_DE_analysis.pl* to get differentially expressed genes. I
> am getting one way fold change results irrespective of if I use
> "ConditionA_vs_ConditionB" or "ConditionB_vs_ConditionA". I am using DESeq2
> method using following command:
>
> /run_DE_analysis.pl --matrix Stem.genes.counts.matrix --method DESeq2
> --samples_file StalkNumLow_vs_StalkNumHigh.txt --contrast contrast.txt
> --output StalkNumLow_vs_StalkNumHigh
>
> ###eg:I ran the script with a set of "SampleA vs SampleB" and later
> "SampleB vs Sample A". In both cases the the fold change in (.DE.results)
> is negative while I expect it to be negative in one case and positive in
> other.
> First run "SampleA vs Sample B".
>
> id baseMeanA baseMeanB baseMean *log2FoldChange* lfcSE stat pvalue padj
> DN30148_c5_g19 475.84 72.27 245.23 *-2.70* 0.17 -15.06 2.84e-51 1.81e-46
>
> second run "SampleB vs Sample A".
>
> id baseMeanA baseMeanB baseMean *log2FoldChange* lfcSE stat pvalue padj
> DN30148_c5_g19 108.21 426.94 227.73 *-1.88* 0.43 -4.33 1.49e-05 0.00068
>
> #######################
> After bit of troubleshooting, I could fix the fold change issue by
> changing the following code at line#485 in run_DE_analysis.pl.
> print $ofh "res = results(dds)\n";
> to (changed the code to create a contrast variable and passed it to
> result())
> print $ofh "contrast=c(\"conditions\",\"$sample_A\",\"$sample_B\")\n";
> print $ofh "res = results(dds,contrast)\n";
>
> The script "analyze_diff_expr.pl" to extract up and down genes was also
> not working properly. In some cases, the outputs *-UP.subset still
> contained wrong genes. From the code at Line#385 of "analyze_diff_expr.pl"
> it seems that all the positive fold changes are labelled as UP in
> ConditionB.
> if ($log_fold_change > 0) {
> print $condB_up_ofh "$line\t$matrix_counts\n";
> $countB++;
> $condB_up_genes{$id} = $rank;
> }
> else {
> print $condA_up_ofh "$line\t$matrix_counts\n";
> $countA++;
> $condA_up_genes{$id} = $rank;
> }
> while from "run_DE_analysis.pl" it seems that fold change in DESeq2 is
> calculated using formula ConditionA/ConditionB and hence positive values
> should be considered as UP in condition A and not in ConditionB.
> Changing $log_fold_change > 0 to $log_fold_change < 0 in the above code
> does fix the issue.
>
> Just wanted to ask your opinion that I am not messing anything else by
> making these changes.
> Thanks
> Ratnesh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/140>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX2TYcisxfpOlAPkB4XHiV6S1Yb2zks5qHec8gaJpZM4Ir7bu>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by RatneshSingh** [comment]
I am using trinityrnaseq-2.2.0

**Comment by brianjohnhaas** [comment]
gotcha. ok - I'll take a look shortly.

thx,
~b

On Wed, Jun 1, 2016 at 6:40 PM, Ratnesh Singh <notifications@github.com>
wrote:

> I am using trinityrnaseq-2.2.0
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/140#issuecomment-223146511>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX21zZ6N2ezs3w7L_B9seuVw6jKTfks5qHgpxgaJpZM4Ir7bu>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
I expect your changes should be fine, but we should change the log fold
change so it's consistent with edgeR, assuming that the problem here was
just related to DESeq2 as integrated here.

thx,

~b



On Wed, Jun 1, 2016 at 6:41 PM, Brian Haas <bhaas@broadinstitute.org> wrote:

> gotcha. ok - I'll take a look shortly.
>
> thx,
> ~b
>
> On Wed, Jun 1, 2016 at 6:40 PM, Ratnesh Singh <notifications@github.com>
> wrote:
>
>> I am using trinityrnaseq-2.2.0
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/trinityrnaseq/trinityrnaseq/issues/140#issuecomment-223146511>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AHMVX21zZ6N2ezs3w7L_B9seuVw6jKTfks5qHgpxgaJpZM4Ir7bu>
>> .
>>
>
>
>
> --
> --
> Brian J. Haas
> The Broad Institute
> http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
>
>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by RatneshSingh** [comment]
Thanks Brian.

**Comment by brianjohnhaas** [comment]
thanks again!  this was very helpful!
