### ISSUE TITLE
Update the code wiki page in downstream analyses using Dockerized Trinity

### ISSUE THREAD

**Issue by permia** [trinityrnaseq/trinityrnaseq#1414]
[Downstream analyses using Dockerized Trinity](https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-in-Docker#downstream-analyses-using-dockerized-trinity)
In this page, the perl script path of example is wrong.
Old:
` %  docker run -v`pwd`:`pwd` trinityrnaseq/trinityrnaseq \
      /usr/local/bin/trinityrnaseq/util/align_and_estimate_abundance.pl`

Correct to:
` %  docker run -v`pwd`:`pwd` trinityrnaseq/trinityrnaseq \
      /usr/local/bin/util/align_and_estimate_abundance.pl`

or:
` %  docker run -v`pwd`:`pwd` trinityrnaseq/trinityrnaseq \
     $TRINITY_HOME/util/align_and_estimate_abundance.pl`

**Comment by brianjohnhaas** [comment]
done. thx!
