### ISSUE TITLE
RSEM problems

### ISSUE THREAD

**Issue by snowbyforever** [trinityrnaseq/trinityrnaseq#145]
Hi, 
I really need you help to figure the problems I encountered when ran RSEM on DMC of suppercomputer. Could you give some suggestion? 

When I used this order:
/mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/util/align_and_estimate_abundance.pl --transcripts Trinity.fasta --seqType fq --left reads.left.fq --right reads.right.fq --gene_trans_map Trinity.fasta.gene_trans_map --aln_method bowtie --est_method RSEM --output_dir rsem_estimate --SS_lib_type RF --prep_reference

There is always errors:
CMD: rsem-prepare-reference  --transcript-to-gene-map /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.gene_trans_map /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.RSEM
Undefined subroutine &FindBin::abs_path called at /opt/asn/apps/perl_5.12.3/lib/FindBin.pm line 197.
BEGIN failed--compilation aborted at /opt/asn/apps/perl_5.12.3/lib/FindBin.pm line 205.
Compilation failed in require at /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/trinity-plugins/rsem-1.2.19/rsem-prepare-reference line 5.
BEGIN failed--compilation aborted at /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/trinity-plugins/rsem-1.2.19/rsem-prepare-reference line 5.
Error, cmd: rsem-prepare-reference  --transcript-to-gene-map /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.gene_trans_map /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.RSEM died with ret: 5632 at /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/util/align_and_estimate_abundance.pl line 653.

Thanks so much!

Dong

**Comment by brianjohnhaas** [comment]
Hi,

this looks like a perl module installation problem.  See if you can get the
FindBin module re-installed.  It's a standard module available in CPAN.

~b

On Wed, Jun 8, 2016 at 10:36 PM, snowbyforever <notifications@github.com>
wrote:

> Hi,
> I really need you help to figure the problems I encountered when ran RSEM
> on DMC of suppercomputer. Could you give some suggestion?
>
> When I used this order:
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/util/
> align_and_estimate_abundance.pl --transcripts Trinity.fasta --seqType fq
> --left reads.left.fq --right reads.right.fq --gene_trans_map
> Trinity.fasta.gene_trans_map --aln_method bowtie --est_method RSEM
> --output_dir rsem_estimate --SS_lib_type RF --prep_reference
>
> There is always errors:
> CMD: rsem-prepare-reference --transcript-to-gene-map
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.gene_trans_map
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.RSEM
> Undefined subroutine &FindBin::abs_path called at
> /opt/asn/apps/perl_5.12.3/lib/FindBin.pm line 197.
> BEGIN failed--compilation aborted at
> /opt/asn/apps/perl_5.12.3/lib/FindBin.pm line 205.
> Compilation failed in require at
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/trinity-plugins/rsem-1.2.19/rsem-prepare-reference
> line 5.
> BEGIN failed--compilation aborted at
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/trinity-plugins/rsem-1.2.19/rsem-prepare-reference
> line 5.
> Error, cmd: rsem-prepare-reference --transcript-to-gene-map
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.gene_trans_map
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta
> /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/sample_data/test_align_and_estimate_abundance/Trinity.fasta.RSEM
> died with ret: 5632 at /mnt/homeapps/home/aubdxz/trinityrnaseq-2.0.6/util/
> align_and_estimate_abundance.pl line 653.
>
> Thanks so much!
>
> Dong
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/145>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX_lAZGHRCxMzbYkoDoXPODn4-D83ks5qJyfogaJpZM4IxX2->
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
