### ISSUE TITLE
running abundance_estimates_to_matrix.pl--transcript_id: command not found

### ISSUE THREAD

**Issue by snowbyforever** [trinityrnaseq/trinityrnaseq#147]
I want to run "abundance_estimates_to_matrix.pl" using my output RSEM.isoforms.results. But there are always errors like this:
RSEM_out1/RSEM.isoforms1.results: line 1: transcript_id: command not found
RSEM_out1/RSEM.isoforms1.results: line 2: TRINITY_DN100000_c0_g1_i1: command not found
RSEM_out1/RSEM.isoforms1.results: line 3: TRINITY_DN100001_c0_g1_i1: command not found
RSEM.isoforms1.results: line 4: TRINITY_DN100002_c0_g1_i1: command not found
RSEM_out1/RSEM.isoforms1.results: line 5: TRINITY_DN100003_c0_g1_i1: command not found
……………

My RSEM.isoforms.results. are like following:
transcript_id   gene_id length  effective_length        expected_count  TPM     FPKM    IsoPct
TRINITY_DN100000_c0_g1_i1       TRINITY_DN100000_c0_g1  337     125.78  0.00    0.00    0.00    0.00
TRINITY_DN100001_c0_g1_i1       TRINITY_DN100001_c0_g1  384     168.52  0.00    0.00    0.00    0.00
TRINITY_DN100002_c0_g1_i1       TRINITY_DN100002_c0_g1  317     108.31  0.00    0.00    0.00    0.00
TRINITY_DN100003_c0_g1_i1       TRINITY_DN100003_c0_g1  358     144.63  3.00    1.28    1.33    100.00
TRINITY_DN100004_c0_g1_i1       TRINITY_DN100004_c0_g1  252     56.15   0.00    0.00    0.00    0.00
TRINITY_DN100005_c0_g1_i1       TRINITY_DN100005_c0_g1  374     159.27  0.00    0.00    0.00    0.00
TRINITY_DN100006_c0_g1_i1       TRINITY_DN100006_c0_g1  272     71.26   0.00    0.00    0.00    0.00
TRINITY_DN100007_c0_g1_i1       TRINITY_DN100007_c0_g1  398     181.60  0.00    0.00    0.00    0.00
TRINITY_DN100008_c0_g1_i1       TRINITY_DN100008_c0_g1  330     119.61  0.00    0.00    0.00    0.00

Could you give me some suggestions how to figure out this problems?

Thanks!

Dong

**Comment by brianjohnhaas** [comment]
https://groups.google.com/forum/#!forum/trinityrnaseq-users

for tech support
