### ISSUE TITLE
Compile Inchworm with C++11 support to reduce memory usage

### ISSUE THREAD

**Issue by nathanweeks** [trinityrnaseq/trinityrnaseq#15]
A colleague had a Trinity run that would bomb out with std::bad_alloc in Inchworm around the end of KmerCounter::get_kmers_sort_descending_counts().  After microbenchmarking, I believe the issue was partially due to extra memory usage caused by the copying of the kmer_list vector that is allocated in KmerCounter::get_kmers_sort_descending_counts:

```
// KmerCounter.cpp
vector<Kmer_Occurence_Pair> KmerCounter::get_kmers_sort_descending_counts() {
...
    vector<Kmer_Occurence_Pair> kmer_list;
..
return(kmer_list);
}

// IRKE.cpp
// vector<Kmer_Occurence_Pair> kmer_list;
void IRKE::populate_sorted_kmers_list() {

    sorted_kmers = kcounter.get_kmers_sort_descending_counts();
...
}
```

Using C++03 and earlier semantics, this appears to cause the copy constructor of the destination vector to be invoked, resulting in the allocation of a vector of sorted_kmers, and a copy of the kmer_list vector to this newly-allocated vector. This behavior can be demonstrated for GCC 4.6.3, Intel 15.0.0, and Clang 3.4 using the following test code: 

```
$ cat test1.cpp
#include <iostream>
#include <utility>
#include <vector>

#define VECTOR_SIZE 1073741824

typedef unsigned long long kmer_int_type_t;
typedef std::pair<kmer_int_type_t,unsigned int> Kmer_Occurence_Pair;

std::vector<Kmer_Occurence_Pair> get_kmers_sort_descending_counts() {

    std::vector<Kmer_Occurence_Pair> kmer_list;

    for (int i = 0; i < VECTOR_SIZE; i++) {
        Kmer_Occurence_Pair kp (1234LL, 5678);
        kmer_list.push_back(kp);
    }

    return(kmer_list);
}

int main(void) {
    std::vector<Kmer_Occurence_Pair> kmer_list;
    kmer_list = get_kmers_sort_descending_counts();
    std::cout << "size:" << kmer_list.size() << std::endl;
}
```

With g++ 4.6.3, this results in ~128G memory usage ("Maximum resident set size"):
```
$ g++ -O2 test1.cpp
$ time -v ./a.out
size:1073741824
        Command being timed: "./a.out"
        User time (seconds): 20.08
        System time (seconds): 28.73
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:49.08
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 134222464
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 12583273
        Voluntary context switches: 1
        Involuntary context switches: 4138
        Swaps: 0
        File system inputs: 33
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

If the -std=c++0x option is added, however, I believe the std::vector's move constructor (a feature added in C++11: http://en.wikipedia.org/wiki/C%2B%2B11#Rvalue_references_and_move_constructors) is used instead of its copy constructor to avoid another allocation + copy, halving the memory usage (and reducing runtime):

```
$ g++ -std=c++0x -O2 test1.cpp
$ time -v ./a.out
size:1073741824
        Command being timed: "./a.out"
        User time (seconds): 15.05
        System time (seconds): 19.12
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:34.35
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 67113648
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 8388966
        Voluntary context switches: 1
        Involuntary context switches: 2897
        Swaps: 0
        File system inputs: 33
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

By default, GCC 4.6.3, Intel 15.0.0, and Clang 3.4 don't assume C++11 semantics due to incomplete support and/or backwards compatibility issues.

My suggestion is to compile Inchworm assuming C++11 support, so the new, more performant semantics are used everywhere where it may be relevant. Ideally, if you (Brian?) have a recent version of the Autoconf Archive (http://savannah.gnu.org/projects/autoconf-archive/) installed, putting the AX_CXX_COMPILE_STDCXX_11 macro in Inchworm/configure.ac before regenerating the configure script will cause this functionality to be enabled for the copmiler (note that AC_CXX_COMPILE_STDCXX_0X would for with somewhat older versions of autoconf-archive).

If the responsible Trinity developer's autotools doesn't support either macro, then the option is generally -std=c++11 in newer compilers, but for compatibility should probably start with -std=c++0x for older compilers:

```
--- a/Inchworm/configure.ac
+++ b/Inchworm/configure.ac
@@ -5,9 +5,9 @@ AC_PROG_CXX
 #AC_OPENMP # requires autoconf >= 2.62
 AC_SUBST([AM_CXXFLAGS], [-m64])
 case $CXX in
-  g++*) AC_SUBST([AM_CXXFLAGS],["-pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated $AM_CXXFLAGS"]);;
-  sunCC*) AC_SUBST([AM_CXXFLAGS], ["-library=stlport4 -xopenmp -xvpara -fast $AM_CXXFLAGS"]) ;;
-  icpc*) AC_SUBST([AM_CXXFLAGS], ["-Wall -openmp $AM_CXXFLAGS"]) ;;
+  g++*) AC_SUBST([AM_CXXFLAGS],["-std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated $AM_CXXFLAGS"]);;
+  sunCC*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -library=stlport4 -xopenmp -xvpara -fast $AM_CXXFLAGS"]) ;;
+  icpc*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -Wall -openmp $AM_CXXFLAGS"]) ;;
 esac
 AC_SEARCH_LIBS([cos], [m])
 AC_CONFIG_HEADERS([config.h])
```

Note that -std=c++0x obviates the need for -Wno-long-long in the g++ CXXFLAGS, as "long long" is part of the C++11 standard.

As an aside, I think it's probably safe to uncomment the AC_OPENMP option and remove the -fopenmp/-xopenmp/-openmp compiler options that are hard-coded in the various CXXFLAGS, since the Intel compiler recently deprecated -openmp in 15.0 (replaced with -qopenmp), and one may want to try compiling Inchworm with a compiler other than the three listed compilers.

**Comment by brianjohnhaas** [comment]
Thanks, Nathan!

I'm trying to incorporate these updates and running into some trouble,
though.

I installed the latest version of autoconf, updated the configure.ac, and
it's reporting:

configure.ac:7: error: possibly undefined macro: AC_CXX_COMPILE_STDCXX_0X

      If this token and others are legitimate, please use m4_pattern_allow.

      See the Autoconf documentation.

autoreconf:
/seq/regev_genome_portal/SOFTWARE/AUTOCONF/current/../bin/autoconf failed
with exit status: 1


I put in the newer AX_CXX_COMPILE_STDCXX_11, and autoreconf --install works
fine, but then when I run configure:


bhaas@delanatii $ ./configure --prefix=`pwd`

checking for a BSD-compatible install...
/broad/software/free/Linux/redhat_6_x86_64/pkgs/coreutils_8.22/bin/install
-c

checking whether build environment is sane... yes

checking for a thread-safe mkdir -p...
/broad/software/free/Linux/redhat_6_x86_64/pkgs/coreutils_8.22/bin/mkdir -p

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking for g++... g++

checking whether the C++ compiler works... yes

checking for C++ compiler default output file name... a.out

checking for suffix of executables...

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C++ compiler... yes

checking whether g++ accepts -g... yes

checking for style of include used by make... GNU

checking dependency style of g++... gcc3

checking for g++ option to support OpenMP... -fopenmp

*./configure: line 3104: AX_CXX_COMPILE_STDCXX_11: command not found*

checking for library containing cos... none required

configure: creating ./config.status

config.status: creating Makefile

config.status: creating src/Makefile

config.status: creating config.h

config.status: executing depfiles commands

bhaas@delanatii $ which autoreconf

/seq/regev_genome_portal/SOFTWARE/AUTOCONF/bin/autoreconf


This was all done on redhat enterprise linux 6


any ideas?

many thanks!


~brian




On Sat, Feb 14, 2015 at 2:12 PM, Nathan T. Weeks <notifications@github.com>
wrote:

> A colleague had a Trinity run that would bomb out with std::bad_alloc in
> Inchworm around the end of KmerCounter::get_kmers_sort_descending_counts().
> After microbenchmarking, I believe the issue was partially due to extra
> memory usage caused by the copying of the kmer_list vector that is
> allocated in KmerCounter::get_kmers_sort_descending_counts:
>
> // KmerCounter.cpp
> vector<Kmer_Occurence_Pair> KmerCounter::get_kmers_sort_descending_counts() {
> ...
>     vector<Kmer_Occurence_Pair> kmer_list;
> ..
> return(kmer_list);
> }
>
> // IRKE.cpp
> // vector<Kmer_Occurence_Pair> kmer_list;
> void IRKE::populate_sorted_kmers_list() {
>
>     sorted_kmers = kcounter.get_kmers_sort_descending_counts();
> ...
> }
>
> Using C++03 and earlier semantics, this appears to cause the copy
> constructor of the destination vector to be invoked, resulting in the
> allocation of a vector of sorted_kmers, and a copy of the kmer_list vector
> to this newly-allocated vector. This behavior can be demonstrated for GCC
> 4.6.3, Intel 15.0.0, and Clang 3.4 using the following test code:
>
> $ cat test1.cpp
> #include <iostream>
> #include <utility>
> #include <vector>
>
> #define VECTOR_SIZE 1073741824
>
> typedef unsigned long long kmer_int_type_t;
> typedef std::pair<kmer_int_type_t,unsigned int> Kmer_Occurence_Pair;
>
> std::vector<Kmer_Occurence_Pair> get_kmers_sort_descending_counts() {
>
>     std::vector<Kmer_Occurence_Pair> kmer_list;
>
>     for (int i = 0; i < VECTOR_SIZE; i++) {
>         Kmer_Occurence_Pair kp (1234LL, 5678);
>         kmer_list.push_back(kp);
>     }
>
>     return(kmer_list);
> }
>
> int main(void) {
>     std::vector<Kmer_Occurence_Pair> kmer_list;
>     kmer_list = get_kmers_sort_descending_counts();
>     std::cout << "size:" << kmer_list.size() << std::endl;
> }
>
> With g++ 4.6.3, this results in ~128G memory usage ("Maximum resident set
> size"):
>
> $ g++ -O2 test1.cpp
> $ time -v ./a.out
> size:1073741824
>         Command being timed: "./a.out"
>         User time (seconds): 20.08
>         System time (seconds): 28.73
>         Percent of CPU this job got: 99%
>         Elapsed (wall clock) time (h:mm:ss or m:ss): 0:49.08
>         Average shared text size (kbytes): 0
>         Average unshared data size (kbytes): 0
>         Average stack size (kbytes): 0
>         Average total size (kbytes): 0
>         Maximum resident set size (kbytes): 134222464
>         Average resident set size (kbytes): 0
>         Major (requiring I/O) page faults: 1
>         Minor (reclaiming a frame) page faults: 12583273
>         Voluntary context switches: 1
>         Involuntary context switches: 4138
>         Swaps: 0
>         File system inputs: 33
>         File system outputs: 0
>         Socket messages sent: 0
>         Socket messages received: 0
>         Signals delivered: 0
>         Page size (bytes): 4096
>         Exit status: 0
>
> If the -std=c++0x option is added, however, I believe the std::vector's
> move constructor (a feature added in C++11:
> http://en.wikipedia.org/wiki/C%2B%2B11#Rvalue_references_and_move_constructors)
> is used instead of its copy constructor to avoid another allocation + copy,
> halving the memory usage (and reducing runtime):
>
> $ g++ -std=c++0x -O2 test1.cpp
> $ time -v ./a.out
> size:1073741824
>         Command being timed: "./a.out"
>         User time (seconds): 15.05
>         System time (seconds): 19.12
>         Percent of CPU this job got: 99%
>         Elapsed (wall clock) time (h:mm:ss or m:ss): 0:34.35
>         Average shared text size (kbytes): 0
>         Average unshared data size (kbytes): 0
>         Average stack size (kbytes): 0
>         Average total size (kbytes): 0
>         Maximum resident set size (kbytes): 67113648
>         Average resident set size (kbytes): 0
>         Major (requiring I/O) page faults: 1
>         Minor (reclaiming a frame) page faults: 8388966
>         Voluntary context switches: 1
>         Involuntary context switches: 2897
>         Swaps: 0
>         File system inputs: 33
>         File system outputs: 0
>         Socket messages sent: 0
>         Socket messages received: 0
>         Signals delivered: 0
>         Page size (bytes): 4096
>         Exit status: 0
>
> By default, GCC 4.6.3, Intel 15.0.0, and Clang 3.4 don't assume C++11
> semantics due to incomplete support and/or backwards compatibility issues.
>
> My suggestion is to compile Inchworm assuming C++11 support, so the new,
> more performant semantics are used everywhere where it may be relevant.
> Ideally, if you (Brian?) have a recent version of the Autoconf Archive (
> http://savannah.gnu.org/projects/autoconf-archive/) installed, putting
> the AX_CXX_COMPILE_STDCXX_11 macro in Inchworm/configure.ac before
> regenerating the configure script will cause this functionality to be
> enabled for the copmiler (note that AC_CXX_COMPILE_STDCXX_0X would for with
> somewhat older versions of autoconf-archive).
>
> If the responsible Trinity developer's autotools doesn't support either
> macro, then the option is generally -std=c++11 in newer compilers, but for
> compatibility should probably start with -std=c++0x for older compilers:
>
> --- a/Inchworm/configure.ac
> +++ b/Inchworm/configure.ac
> @@ -5,9 +5,9 @@ AC_PROG_CXX
>  #AC_OPENMP # requires autoconf >= 2.62
>  AC_SUBST([AM_CXXFLAGS], [-m64])
>  case $CXX in
> -  g++*) AC_SUBST([AM_CXXFLAGS],["-pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated $AM_CXXFLAGS"]);;
> -  sunCC*) AC_SUBST([AM_CXXFLAGS], ["-library=stlport4 -xopenmp -xvpara -fast $AM_CXXFLAGS"]) ;;
> -  icpc*) AC_SUBST([AM_CXXFLAGS], ["-Wall -openmp $AM_CXXFLAGS"]) ;;
> +  g++*) AC_SUBST([AM_CXXFLAGS],["-std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated $AM_CXXFLAGS"]);;
> +  sunCC*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -library=stlport4 -xopenmp -xvpara -fast $AM_CXXFLAGS"]) ;;
> +  icpc*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -Wall -openmp $AM_CXXFLAGS"]) ;;
>  esac
>  AC_SEARCH_LIBS([cos], [m])
>  AC_CONFIG_HEADERS([config.h])
>
> Note that -std=c++0x obviates the need for -Wno-long-long in the g++
> CXXFLAGS, as "long long" is part of the C++11 standard.
>
> As an aside, I think it's probably safe to uncomment the AC_OPENMP option
> and remove the -fopenmp/-xopenmp/-openmp compiler options that are
> hard-coded in the various CXXFLAGS, since the Intel compiler recently
> deprecated -openmp in 15.0 (replaced with -qopenmp), and one may want to
> try compiling Inchworm with a compiler other than the three listed
> compilers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/15>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by benfulton** [comment]
Perhaps Nathan could send a pull request incorporating the changes he'd
like to see?

**Comment by brianjohnhaas** [comment]
right - that's probably the best plan.

On Sun, Feb 15, 2015 at 1:57 PM, Ben Fulton <notifications@github.com>
wrote:

> Perhaps Nathan could send a pull request incorporating the changes he'd
> like to see?
>
>
> On Sun, Feb 15, 2015 at 10:43 AM, Brian Haas <notifications@github.com>
> wrote:
>
>
> > Thanks, Nathan!
> >
> > I'm trying to incorporate these updates and running into some trouble,
> > though.
> >
> > I installed the latest version of autoconf, updated the configure.ac,
> and
> > it's reporting:
> >
> > configure.ac:7: error: possibly undefined macro:
> AC_CXX_COMPILE_STDCXX_0X
> >
> > If this token and others are legitimate, please use m4_pattern_allow.
> >
> > See the Autoconf documentation.
> >
> > autoreconf:
> > /seq/regev_genome_portal/SOFTWARE/AUTOCONF/current/../bin/autoconf failed
> > with exit status: 1
> >
> >
> > I put in the newer AX_CXX_COMPILE_STDCXX_11, and autoreconf --install
> works
> > fine, but then when I run configure:
> >
> >
> > bhaas@delanatii $ ./configure --prefix=`pwd`
> >
> > checking for a BSD-compatible install...
> >
> /broad/software/free/Linux/redhat_6_x86_64/pkgs/coreutils_8.22/bin/install
> > -c
> >
> > checking whether build environment is sane... yes
> >
> > checking for a thread-safe mkdir -p...
> > /broad/software/free/Linux/redhat_6_x86_64/pkgs/coreutils_8.22/bin/mkdir
> -p
> >
> > checking for gawk... gawk
> >
> > checking whether make sets $(MAKE)... yes
> >
> > checking for g++... g++
> >
> > checking whether the C++ compiler works... yes
> >
> > checking for C++ compiler default output file name... a.out
> >
> > checking for suffix of executables...
> >
> > checking whether we are cross compiling... no
> >
> > checking for suffix of object files... o
> >
> > checking whether we are using the GNU C++ compiler... yes
> >
> > checking whether g++ accepts -g... yes
> >
> > checking for style of include used by make... GNU
> >
> > checking dependency style of g++... gcc3
> >
> > checking for g++ option to support OpenMP... -fopenmp
> >
> > *./configure: line 3104: AX_CXX_COMPILE_STDCXX_11: command not found*
> >
> > checking for library containing cos... none required
> >
> > configure: creating ./config.status
> >
> > config.status: creating Makefile
> >
> > config.status: creating src/Makefile
> >
> > config.status: creating config.h
> >
> > config.status: executing depfiles commands
> >
> > bhaas@delanatii $ which autoreconf
> >
> > /seq/regev_genome_portal/SOFTWARE/AUTOCONF/bin/autoreconf
> >
> >
> > This was all done on redhat enterprise linux 6
> >
> >
> > any ideas?
> >
> > many thanks!
> >
> >
> > ~brian
> >
> >
> >
> >
> > On Sat, Feb 14, 2015 at 2:12 PM, Nathan T. Weeks <
> notifications@github.com
> > >
> > wrote:
> >
> >
> > > A colleague had a Trinity run that would bomb out with std::bad_alloc
> in
> > > Inchworm around the end of
> > KmerCounter::get_kmers_sort_descending_counts().
> > > After microbenchmarking, I believe the issue was partially due to extra
> > > memory usage caused by the copying of the kmer_list vector that is
> > > allocated in KmerCounter::get_kmers_sort_descending_counts:
> > >
> > > // KmerCounter.cpp
> > > vector<Kmer_Occurence_Pair>
> > KmerCounter::get_kmers_sort_descending_counts() {
> > > ...
> > > vector<Kmer_Occurence_Pair> kmer_list;
> > > ..
> > > return(kmer_list);
> > > }
> > >
> > > // IRKE.cpp
> > > // vector<Kmer_Occurence_Pair> kmer_list;
> > > void IRKE::populate_sorted_kmers_list() {
> > >
> > > sorted_kmers = kcounter.get_kmers_sort_descending_counts();
> > > ...
> > > }
> > >
> > > Using C++03 and earlier semantics, this appears to cause the copy
> > > constructor of the destination vector to be invoked, resulting in the
> > > allocation of a vector of sorted_kmers, and a copy of the kmer_list
> > vector
> > > to this newly-allocated vector. This behavior can be demonstrated for
> GCC
> > > 4.6.3, Intel 15.0.0, and Clang 3.4 using the following test code:
> > >
> > > $ cat test1.cpp
> > > #include <iostream>
> > > #include <utility>
> > > #include <vector>
> > >
> > > #define VECTOR_SIZE 1073741824
> > >
> > > typedef unsigned long long kmer_int_type_t;
> > > typedef std::pair<kmer_int_type_t,unsigned int> Kmer_Occurence_Pair;
> > >
> > > std::vector<Kmer_Occurence_Pair> get_kmers_sort_descending_counts() {
> > >
> > > std::vector<Kmer_Occurence_Pair> kmer_list;
> > >
> > > for (int i = 0; i < VECTOR_SIZE; i++) {
> > > Kmer_Occurence_Pair kp (1234LL, 5678);
> > > kmer_list.push_back(kp);
> > > }
> > >
> > > return(kmer_list);
> > > }
> > >
> > > int main(void) {
> > > std::vector<Kmer_Occurence_Pair> kmer_list;
> > > kmer_list = get_kmers_sort_descending_counts();
> > > std::cout << "size:" << kmer_list.size() << std::endl;
> > > }
> > >
> > > With g++ 4.6.3, this results in ~128G memory usage ("Maximum resident
> set
> > > size"):
> > >
> > > $ g++ -O2 test1.cpp
> > > $ time -v ./a.out
> > > size:1073741824
> > > Command being timed: "./a.out"
> > > User time (seconds): 20.08
> > > System time (seconds): 28.73
> > > Percent of CPU this job got: 99%
> > > Elapsed (wall clock) time (h:mm:ss or m:ss): 0:49.08
> > > Average shared text size (kbytes): 0
> > > Average unshared data size (kbytes): 0
> > > Average stack size (kbytes): 0
> > > Average total size (kbytes): 0
> > > Maximum resident set size (kbytes): 134222464
> > > Average resident set size (kbytes): 0
> > > Major (requiring I/O) page faults: 1
> > > Minor (reclaiming a frame) page faults: 12583273
> > > Voluntary context switches: 1
> > > Involuntary context switches: 4138
> > > Swaps: 0
> > > File system inputs: 33
> > > File system outputs: 0
> > > Socket messages sent: 0
> > > Socket messages received: 0
> > > Signals delivered: 0
> > > Page size (bytes): 4096
> > > Exit status: 0
> > >
> > > If the -std=c++0x option is added, however, I believe the std::vector's
> > > move constructor (a feature added in C++11:
> > >
> >
> http://en.wikipedia.org/wiki/C%2B%2B11#Rvalue_references_and_move_constructors
> > )
> > > is used instead of its copy constructor to avoid another allocation +
> > copy,
> > > halving the memory usage (and reducing runtime):
> > >
> > > $ g++ -std=c++0x -O2 test1.cpp
> > > $ time -v ./a.out
> > > size:1073741824
> > > Command being timed: "./a.out"
> > > User time (seconds): 15.05
> > > System time (seconds): 19.12
> > > Percent of CPU this job got: 99%
> > > Elapsed (wall clock) time (h:mm:ss or m:ss): 0:34.35
> > > Average shared text size (kbytes): 0
> > > Average unshared data size (kbytes): 0
> > > Average stack size (kbytes): 0
> > > Average total size (kbytes): 0
> > > Maximum resident set size (kbytes): 67113648
> > > Average resident set size (kbytes): 0
> > > Major (requiring I/O) page faults: 1
> > > Minor (reclaiming a frame) page faults: 8388966
> > > Voluntary context switches: 1
> > > Involuntary context switches: 2897
> > > Swaps: 0
> > > File system inputs: 33
> > > File system outputs: 0
> > > Socket messages sent: 0
> > > Socket messages received: 0
> > > Signals delivered: 0
> > > Page size (bytes): 4096
> > > Exit status: 0
> > >
> > > By default, GCC 4.6.3, Intel 15.0.0, and Clang 3.4 don't assume C++11
> > > semantics due to incomplete support and/or backwards compatibility
> > issues.
> > >
> > > My suggestion is to compile Inchworm assuming C++11 support, so the
> new,
> > > more performant semantics are used everywhere where it may be relevant.
> > > Ideally, if you (Brian?) have a recent version of the Autoconf Archive
> (
> > > http://savannah.gnu.org/projects/autoconf-archive/) installed, putting
> > > the AX_CXX_COMPILE_STDCXX_11 macro in Inchworm/configure.ac before
> > > regenerating the configure script will cause this functionality to be
> > > enabled for the copmiler (note that AC_CXX_COMPILE_STDCXX_0X would for
> > with
> > > somewhat older versions of autoconf-archive).
> > >
> > > If the responsible Trinity developer's autotools doesn't support either
> > > macro, then the option is generally -std=c++11 in newer compilers, but
> > for
> > > compatibility should probably start with -std=c++0x for older
> compilers:
> > >
> > > --- a/Inchworm/configure.ac
> > > +++ b/Inchworm/configure.ac
> > > @@ -5,9 +5,9 @@ AC_PROG_CXX
> > > #AC_OPENMP # requires autoconf >= 2.62
> > > AC_SUBST([AM_CXXFLAGS], [-m64])
> > > case $CXX in
> > > - g++*) AC_SUBST([AM_CXXFLAGS],["-pedantic -fopenmp -Wall -Wextra
> > -Wno-long-long -Wno-deprecated $AM_CXXFLAGS"]);;
> > > - sunCC*) AC_SUBST([AM_CXXFLAGS], ["-library=stlport4 -xopenmp -xvpara
> > -fast $AM_CXXFLAGS"]) ;;
> > > - icpc*) AC_SUBST([AM_CXXFLAGS], ["-Wall -openmp $AM_CXXFLAGS"]) ;;
> > > + g++*) AC_SUBST([AM_CXXFLAGS],["-std=c++0x -pedantic -fopenmp -Wall
> > -Wextra -Wno-deprecated $AM_CXXFLAGS"]);;
> > > + sunCC*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -library=stlport4
> > -xopenmp -xvpara -fast $AM_CXXFLAGS"]) ;;
> > > + icpc*) AC_SUBST([AM_CXXFLAGS], ["-std=c++0x -Wall -openmp
> > $AM_CXXFLAGS"]) ;;
> > > esac
> > > AC_SEARCH_LIBS([cos], [m])
> > > AC_CONFIG_HEADERS([config.h])
> > >
> > > Note that -std=c++0x obviates the need for -Wno-long-long in the g++
> > > CXXFLAGS, as "long long" is part of the C++11 standard.
> > >
> > > As an aside, I think it's probably safe to uncomment the AC_OPENMP
> option
> > > and remove the -fopenmp/-xopenmp/-openmp compiler options that are
> > > hard-coded in the various CXXFLAGS, since the Intel compiler recently
> > > deprecated -openmp in 15.0 (replaced with -qopenmp), and one may want
> to
> > > try compiling Inchworm with a compiler other than the three listed
> > > compilers.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/trinityrnaseq/trinityrnaseq/issues/15>.
> > >
> >
> >
> >
> > --
> > --
> > Brian J. Haas
> > The Broad Institute
> > http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/trinityrnaseq/trinityrnaseq/issues/15#issuecomment-74422346
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/15#issuecomment-74430983>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
It would be good to see that it compiles on mac-osx just fine too.

**Comment by nathanweeks** [comment]
Brian,

The autoconf-archive doesn't seem to be available as a package from the official RHEL repos, so it may be may be more trouble than it's worth to get the AX_CXX_COMPILE_STDCXX_11 macro in your development environment if RHEL 6 is your primary development platform (though for OS X, MacPorts has the autoconf-archive package).

For expediency, I'll submit a pull request for a modified configure.ac that will work with the RHEL 6 autotools, and that will result in a configure script that still works on OS X.

**Comment by brianjohnhaas** [comment]
That would be great!

I can try to pull down a newer version of autoconf via homebrew on mac, if
that might help...    I thought I did that not long ago, though, and the
option was still giving me trouble.

right - if you generate a pull request, I'll give that a try.   Also, I
think I remember you mentioning just dropping the gcc option directly into
the gcc build opts, which could be a viable option too.

much appreciated!

~brian


On Sun, Feb 15, 2015 at 5:40 PM, Nathan T. Weeks <notifications@github.com>
wrote:

> Brian,
>
> The autoconf-archive doesn't seem to be available as a package from the
> official RHEL repos, so it may be may be more trouble than it's worth to
> get the AX_CXX_COMPILE_STDCXX_11 macro in your development environment if
> RHEL 6 is your primary development platform (though for OS X, MacPorts has
> the autoconf-archive package).
>
> For expediency, I'll submit a pull request for a modified configure.ac
> that will work with the RHEL 6 autotools, and that will result in a
> configure script that still works on OS X.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/15#issuecomment-74441489>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Is this all taken care of?  Can we close it?

**Comment by nathanweeks** [comment]
Yes, it looks like it's been taken care of.
