### ISSUE TITLE
GraphFromFasta errors

### ISSUE THREAD

**Issue by chaosmaker** [trinityrnaseq/trinityrnaseq#150]
Hi All,

I have a quick question, my Trinity runs tend to fail when I get to the GraphFromFasta bit, I don't seem to be running out of memory so I'm not sure what is happening. What I did notice however is that when I run GraphFromFasta I get the following lines of code printed first:

```
$ ./GraphFromFasta_MPI
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
```

is that normal? If not am I missing something or should I recompile somehow differently?

Alternatively, here is the error I get during Trinity:

```
* Running CMD: /home/antczakp/git/trinityrnaseq/Chrysalis/GraphFromFasta -i /attached/TrinityAssembly/inchworm.K25.L25.DS.fa -r both.fa -min_contig_length 200 -min_glue 2 -glue_factor 0.05 -min_iso_ratio 0.05 -t 62 -k 24 -kk 48  -scaffolding /attached/TrinityAssembly/chrysalis/iworm_scaffolds.txt  > /attached/TrinityAssembly/chrysalis/GraphFromIwormFasta.out
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
*** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
-----------------------------------------
--- Chrysalis: GraphFromFasta -----------
-- (cluster related inchworm contigs) ---
-----------------------------------------

-setting num threads to: 62
-running on 62 threads
GraphFromFasta: Reading file: /attached/TrinityAssembly/inchworm.K25.L25.DS.fa
done!
Counting k-mers...
KmerAlignCore- Contigs: 182705142
done, assigning k-mers...
KmerAlignCore- Contigs: 182705142
done!
-setting omp for schedule chunksize to 29468 for 182705143 iworm contigs
Phase 1: Collecting candidate weldmers between iworm contig pairs sharing k-1mers
Processed: 100 % of iworm contigs.

...done Phase 1. (2260.43 seconds)
Captured: 50525504 weldmer candidates.
Allocating: 50525504
Resizing: 50525504
SortingDone.
Setting up reads for streaming...
Identifying reads that support welding of iworm contigs...
Reads: (unknown count: streaming-mode)


Done!
Phase 2: Reclustering iworm contigs using welds.
[69.3845% done]                terminate called after throwing an instance of 'SException'
Aborted (core dumped)
Trinity run failed. Must investigate error above.
```

Thanks

**Comment by brianjohnhaas** [comment]
Do you have an error message that's derived from your Trinity run?  This
MPI version of GraphFromFasta is no longer supported and needs to be
removed from the codebase.

~b

On Thu, Jun 16, 2016 at 8:10 AM, chaosmaker <notifications@github.com>
wrote:

> Hi All,
>
> I have a quick question, my Trinity runs tend to fail when I get to the
> GraphFromFasta bit, I don't seem to be running out of memory so I'm not
> sure what is happening. What I did notice however is that when I run
> GraphFromFasta I get the following lines of code printed first:
>
> $ ./GraphFromFasta_MPI
> *** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
> *** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
> *** unknown type for [10commandArgINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE]
>
> is that normal? If not am I missing something or should I recompile
> somehow differently?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/150>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX9DwkqOdKvO08DUz8YDcYGiz5Am6ks5qMT1LgaJpZM4I3UZ5>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by chaosmaker** [comment]
Thanks for getting back so quick. 

This is all I got from Trinity.
```
Phase 2: Reclustering iworm contigs using welds.
[69.3845% done]                terminate called after throwing an instance of 'SException'
Aborted (core dumped)
Trinity run failed. Must investigate error above.
```

I'm just running Trinity as per normal, it doesn't look like I'm running the MPI version, it seems to run the standard GraphFromFasta just with the -t option to parallelise it.

Thanks

**Comment by brianjohnhaas** [comment]
hmm....   I suspect it's a RAM problem.  Are you running it on a machine
that has ~1G RAM per ~1 M PE reads?

Also, have you run Trinity on other data sets successfully, such as running
the sample data set through to ensure that it can run end-to-end?

best,

~b

On Thu, Jun 16, 2016 at 8:45 AM, chaosmaker <notifications@github.com>
wrote:

> Thanks for getting back so quick.
>
> This is all I got from Trinity.
>
> Phase 2: Reclustering iworm contigs using welds.
> [69.3845% done]                terminate called after throwing an instance of 'SException'
> Aborted (core dumped)
> Trinity run failed. Must investigate error above.
>
> I'm just running Trinity as per normal, it doesn't look like I'm running
> the MPI version, it seems to run the standard GraphFromFasta just with the
> -t option to parallelise it.
>
> Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/150#issuecomment-226474418>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVXxbyErU96tgKLDZEiSBIdZ2KV_Wcks5qMUWCgaJpZM4I3UZ5>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by chaosmaker** [comment]
I have about 380GB of RAM and when I watch it during the assembly it never goes above 150GB. 
The Trinity example file ran through fine but I haven't tried any other dataset on this computer yet.

**Comment by brianjohnhaas** [comment]
I'd suggest trying to run it through our galaxy interface:

 https://galaxy.ncgas-trinity.indiana.edu/user/login

This way, if it breaks, we can directly explore the problem.

much appreciated,

~b



On Thu, Jun 16, 2016 at 9:06 AM, chaosmaker <notifications@github.com>
wrote:

> I have about 380GB of RAM and when I watch it during the assembly it never
> goes above 150GB.
> The Trinity example file ran through fine but I haven't tried any other
> dataset on this computer yet.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/150#issuecomment-226479238>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVXyLcKhXG9Yr_xHA-xE6nUHi4XGleks5qMUpbgaJpZM4I3UZ5>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by chaosmaker** [comment]
I have just submitted a registration request. I'll run it through your instance when I get access.

**Comment by chaosmaker** [comment]
I managed to get passed the previous error by reducing the number of parallel instances from 62 to 30 with GraphFromFasta - I wonder whether that had anything to do with the error...

**Comment by brianjohnhaas** [comment]
I see.  That could be.  I've not tried to scale to that many threads.  Glad
to hear it's working now.

~b

On Fri, Jun 17, 2016 at 10:38 AM, chaosmaker <notifications@github.com>
wrote:

> I managed to get passed the previous error by reducing the number of
> parallel instances from 62 to 30 with GraphFromFasta - I wonder whether
> that had anything to do with the error...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/150#issuecomment-226786651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVXw1jBp5sM93xivoU1VN9sZroNq52ks5qMrF3gaJpZM4I3UZ5>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
