### ISSUE TITLE
How limit memory usage of inchworm 

### ISSUE THREAD

**Issue by zhixingfeng** [trinityrnaseq/trinityrnaseq#152]
Hi, 

I tried to use inchworm of trinity analyze a large RNA-seq dataset, I set --max_memory 64G, but seems this parameter did not work. Inchworm used >200G memory and failed to complete. Is there any way to control memory usage of Inchworm? Thanks in advance.

Best

Zhixing

**Comment by brianjohnhaas** [comment]
The only way to keep the memory usage of inchworm down is to use

    --min_kmer_cov 2

but it will also reduce the contiguity of lowly expressed transcripts.
You're better off finding a higher memory machine  and/or including
normalization as part of your Trinity run (eg.  --normalize_reads)


~b



On Mon, Jun 20, 2016 at 2:34 PM, Zhixing Feng <notifications@github.com>
wrote:

> Hi,
>
> I tried to use inchworm of trinity analyze a large RNA-seq dataset, I set
> --max_memory 64G, but seems this parameter did not work. Inchworm used
> >200G memory and failed to complete. Is there any way to control memory
> usage of Inchworm? Thanks in advance.
>
> Best
>
> Zhixing
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/152>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX7EkCAKU6usjluP7rppcH3fZ9zvkks5qNt1AgaJpZM4I5_gC>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
