### ISSUE TITLE
Error in Parafly

### ISSUE THREAD

**Issue by domenico-simone** [trinityrnaseq/trinityrnaseq#155]
Hello,

I'm running Trinity on metatranscriptomic samples with the following command:

```
Trinity --seqType fq --max_memory 128G  \
         --left ${sampleName}_1.fastq.gz \
         --right ${sampleName}_2.fastq.gz \
         --CPU 16
         --output ../trinity/${sampleName}_trinity_outdir
```

this command works for all samples but one, whose run fails with this message:

```
--------------------------------------------------------------------------------
------------ Trinity Phase 2: Assembling Clusters of Reads ---------------------
--------------------------------------------------------------------------------

Friday, June 24, 2016: 11:12:11 CMD: /pica/sw/apps/bioinfo/trinity/2.1.0/milou/trinity-plugins/parafly/bin/ParaFly -c recursive_trinity.cmds -CPU 16 -v 
Number of Commands: 162811
succeeded(86258)   52.9804% completed.    Partitioning chrysalis graphs and reads
Error, cannot mkdir /pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/102_trinity_outdir/read_partitions/Fb_0/CBin_862/c86263.trinity.reads.fa.out/chrysalis/Component_bins at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/partition_chrysalis_graphs_n_reads.pl line 65, <$fh> line 1.
Trinity run failed. Must investigate error above.
succeeded(162810), failed(1)   100% completed.       
```

This sample was also the one taking more time than the others, I assume because of the high number of the transcripts that were to be assembled.

How can I solve this issue?

Thanks,
Domenico

**Comment by brianjohnhaas** [comment]
Hi

If you rerun the original Trinity command, does it still fail?  It should pick up where it left off.  Probably just a hiccup with the filer.

-Brian
(by iPhone)

**Comment by domenico-simone** [comment]
Hi Brian,

thanks for your suggestion, I re-run Trinity but:

- apparently it has repeated everything over;
- the process failed, again at the Parafly stage, with this message:
```
Monday, June 27, 2016: 23:01:50	CMD: /pica/sw/apps/bioinfo/trinity/2.1.0/milou/trinity-plugins/parafly/bin/ParaFly -c recursive_trinity.cmds -CPU 16 -v 
Number of Commands: 162822
succeeded(12372)   7.59848% completed.    ln: creating symbolic link `single.fa': File exists
Trinity run failed. Must investigate error above.
succeeded(75123), failed(1)   46.1387% completed.
```

Best,
Domenico

**Comment by brianjohnhaas** [comment]
That's very strange.  If you run the exact same original Trinity command,
it should just rerun the job(s) that failed earlier.

Do you see a 'failed command' file in the trinity_out_dir/ ?   You could
try running that command directly to see what happens.

If it continues to give you trouble, you could run Trinity here:
https://galaxy.ncgas-trinity.indiana.edu/user/login

best,

~b

On Tue, Jun 28, 2016 at 2:41 AM, Domenico Simone <notifications@github.com>
wrote:

> Hi Brian,
>
> thanks for your suggestion, I re-run Trinity but:
>
>    - apparently it has repeated everything over;
>    - the process failed, again at the Parafly stage, with this message:
>
> Monday, June 27, 2016: 23:01:50 CMD: /pica/sw/apps/bioinfo/trinity/2.1.0/milou/trinity-plugins/parafly/bin/ParaFly -c recursive_trinity.cmds -CPU 16 -v
> Number of Commands: 162822
> succeeded(12372)   7.59848% completed.    ln: creating symbolic link `single.fa': File exists
> Trinity run failed. Must investigate error above.
> succeeded(75123), failed(1)   46.1387% completed.
>
> Best,
> Domenico
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/155#issuecomment-228963122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX3vAJigs_qTrKk3iwL5shCrtrBVrks5qQMIOgaJpZM4I-9NF>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by domenico-simone** [comment]
Hi Brian,

indeed there was a little problem with folders. I repeated the run and it was successful, resuming the analysis from where it broke down. So I guess it was just some random problem with the process.

Thank you,
Domenico

**Comment by brianjohnhaas** [comment]
great!  thanks for the update

On Tue, Jun 28, 2016 at 9:26 AM, Domenico Simone <notifications@github.com>
wrote:

> Hi Brian,
>
> indeed there was a little problem with folders. I repeated the run and it
> was successful, resuming the analysis from where it broke down. So I guess
> it was just some random problem with the process.
>
> Thank you,
> Domenico
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/155#issuecomment-229048015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX2z-d-z2toQ5H97fNhoGscLTNndcks5qQSEigaJpZM4I-9NF>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
