### ISSUE TITLE
Error with java?

### ISSUE THREAD

**Issue by dcopetti** [trinityrnaseq/trinityrnaseq#156]
I am running Trinity 2.2.0 on a server with this command:
`/opt/trinityrnaseq-2.2.0/Trinity --seqType fq --min_kmer_cov 2 --left Sd5Db_20_R1p.fq --right Sd5Db_20_R2p.fq --CPU 12 --output Sd5D_trinity_20p --max_memory 130G --bfly_opts --bflyCalculateCPU`
 and I get this error:

```
Exception in thread "main" java.lang.NullPointerException
        at gnu.getopt.Getopt.checkLongOption(Getopt.java:869)
        at gnu.getopt.Getopt.getopt(Getopt.java:1119)
        at TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:309)
Exception in thread "main" java.lang.NullPointerException
        at gnu.getopt.Getopt.checkLongOption(Getopt.java:869)
        at gnu.getopt.Getopt.getopt(Getopt.java:1119)
        at TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:309)
Trinity run failed. Must investigate error above.
succeeded(10384), failed(117403)   100% completed.

We are sorry, commands in file: [FailedCommands] failed.  :-(

Trinity run failed. Must investigate error above.
```

Looking at the FailedCommands file, it contains
`/opt/trinityrnaseq-2.2.0/util/support_scripts/../../Trinity --single "/opt/bam_processing/dario/saguaromics/new_trinity_ass/Sd5D_trinity_20p/read_partitions/Fb_0/CBin_5/c583.trinity.reads.fa" --output "/opt/bam_processing/dario/saguaromics/new_trinity_ass/Sd5D_trinity_20p/read_partitions/Fb_0/CBin_5/c583.trinity.reads.fa.out" --CPU 1 --max_memory 1G --seqType fa --trinity_complete --full_cleanup --min_kmer_cov 2 --bfly_opts "--bflyCalculateCPU"`
Is it related to a java version? I am running

```
> java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Thanks.

**Comment by brianjohnhaas** [comment]
Try running it without the parameters

    --bfly_opts --bflyCalculateCPU

If you need to include one, you could try --bflyCalculateCPU, but the
--bfly_opts requires a different set of parameters.  I'd suggest just not
including either unless there's a good reason to.

If it fails due to Java8, you could drop to Java7, but that's the the
problem in this particular instance.

best,

~brian



On Mon, Jun 27, 2016 at 3:11 PM, dcopetti <notifications@github.com> wrote:
>
> I am running Trinity 2.2.0 on a server with this command:
> /opt/trinityrnaseq-2.2.0/Trinity --seqType fq --min_kmer_cov 2 --left
Sd5Db_20_R1p.fq --right Sd5Db_20_R2p.fq --CPU 12 --output Sd5D_trinity_20p
--max_memory 130G --bfly_opts --bflyCalculateCPU
> and I get this error:
>
> Exception in thread "main" java.lang.NullPointerException
>         at gnu.getopt.Getopt.checkLongOption(Getopt.java:869)
>         at gnu.getopt.Getopt.getopt(Getopt.java:1119)
>         at
TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:309)
> Exception in thread "main" java.lang.NullPointerException
>         at gnu.getopt.Getopt.checkLongOption(Getopt.java:869)
>         at gnu.getopt.Getopt.getopt(Getopt.java:1119)
>         at
TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:309)
> Trinity run failed. Must investigate error above.
> succeeded(10384), failed(117403)   100% completed.
>
> We are sorry, commands in file: [FailedCommands] failed.  :-(
>
> Trinity run failed. Must investigate error above.
>
> Looking at the FailedCommands file, it contains
> /opt/trinityrnaseq-2.2.0/util/support_scripts/../../Trinity --single
"/opt/bam_processing/dario/saguaromics/new_trinity_ass/Sd5D_trinity_20p/read_partitions/Fb_0/CBin_5/c583.trinity.reads.fa"
--output
"/opt/bam_processing/dario/saguaromics/new_trinity_ass/Sd5D_trinity_20p/read_partitions/Fb_0/CBin_5/c583.trinity.reads.fa.out"
--CPU 1 --max_memory 1G --seqType fa --trinity_complete --full_cleanup
--min_kmer_cov 2 --bfly_opts "--bflyCalculateCPU"
> Is it related to a java version? I am running
>
> > java -version
> openjdk version "1.8.0_91"
> OpenJDK Runtime Environment (build 1.8.0_91-b14)
> OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by dcopetti** [comment]
I am running it without both bfly parameters and the server (serial, 24 cores) has now a load if 68: do you think it is safe to continue or shall I kill it? Shall I add --bflyCalculateCPU next time?
![screenshot from 2016-06-29 09 56 19](https://cloud.githubusercontent.com/assets/13842014/16461834/5a0e717c-3de3-11e6-8f0c-3834588d9750.png)

**Comment by brianjohnhaas** [comment]
That load wouldn't phase me personally, but if it's causing you any
trouble, you could kill it and rerun with a smaller --CPU number. It'll
pick up where it left off.

Note, you can just run Trinity on our galaxy server and free up all your
resources:

https://galaxy.ncgas-trinity.indiana.edu/user/login

best,

~b

On Wed, Jun 29, 2016 at 1:22 PM, dcopetti <notifications@github.com> wrote:

> I am running it without both bfly parameters and the server (serial, 24
> cores) has now a load if 68: do you think it is safe to continue or shall I
> kill it? Shall I add --bflyCalculateCPU next time?
> [image: screenshot from 2016-06-29 09 56 19]
> <https://cloud.githubusercontent.com/assets/13842014/16461834/5a0e717c-3de3-11e6-8f0c-3834588d9750.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-229426842>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX_-NbpICU46ZPx1yXBaX139l8AdHks5qQqnygaJpZM4I_aRG>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by dcopetti** [comment]
After that step with 68 cpus, now since several days it is running with 
only 1-2 cores, the bottom of the terminal says
Tuesday, June 28, 2016: 19:04:26        CMD: 
/opt/trinityrnaseq-2.2.0/trinity-plugins/parafly/bin/ParaFly -c 
recursive_trinity.cmds -CPU 18 -v
Number of Commands: 127793
succeeded(127792)   99.9992% completed.
and from htop it seems to be running Butterfly.jar.
Is it worth killing and adding a --CPU parameter?

Uploading files on Trinity on Galaxy is taking a long time, and the jobs 
also stay queued for a while. Is it always like this?
thanks,

Dario

On 06/29/2016 06:25 PM, Brian Haas wrote:
> That load wouldn't phase me personally, but if it's causing you any
> trouble, you could kill it and rerun with a smaller --CPU number. It'll
> pick up where it left off.
>
> Note, you can just run Trinity on our galaxy server and free up all your
> resources:
>
> https://galaxy.ncgas-trinity.indiana.edu/user/login
>
> best,
>
> ~b
>
> On Wed, Jun 29, 2016 at 1:22 PM, dcopetti <notifications@github.com> 
> wrote:
>
> > I am running it without both bfly parameters and the server (serial, 24
> > cores) has now a load if 68: do you think it is safe to continue or 
> shall I
> > kill it? Shall I add --bflyCalculateCPU next time?
> > [image: screenshot from 2016-06-29 09 56 19]
> > 
> <https://cloud.githubusercontent.com/assets/13842014/16461834/5a0e717c-3de3-11e6-8f0c-3834588d9750.png>
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-229426842>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AHMVX_-NbpICU46ZPx1yXBaX139l8AdHks5qQqnygaJpZM4I_aRG>
> > .
> >
>
>
>
> -- 
> --
> Brian J. Haas
> The Broad Institute
> http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-229535744>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANM2Xp9W0z7nBJdVGpGvBZskYmX718Zrks5qQxsagaJpZM4I_aRG>.
>

-- 
Dario Copetti, PhD
Research Associate | Arizona Genomics Institute
University of Arizona | BIO5

1657 E. Helen St.
Tucson, AZ  85721, USA
www.genome.arizona.edu

**Comment by brianjohnhaas** [comment]
It's probably stuck on just one Butterfly command.  It should finish
eventually.  Sometimes it ends up with one out of the 100k or so jobs that
is very computationally intensive, and that one would benefit from having
more RAM available to it than the 1G default.   There are ways to
troubleshoot this get that last one to complete.  I'd just let it keep on
running for now, though - unless it crashes.

Did you include --normalize_reads for your run?  If not, that usually
mitigates this type of problem occurring.

~b

On Wed, Jul 6, 2016 at 3:07 PM, dcopetti <notifications@github.com> wrote:

> After that step with 68 cpus, now since several days it is running with
> only 1-2 cores, the bottom of the terminal says
> Tuesday, June 28, 2016: 19:04:26 CMD:
> /opt/trinityrnaseq-2.2.0/trinity-plugins/parafly/bin/ParaFly -c
> recursive_trinity.cmds -CPU 18 -v
> Number of Commands: 127793
> succeeded(127792) 99.9992% completed.
> and from htop it seems to be running Butterfly.jar.
> Is it worth killing and adding a --CPU parameter?
>
> Uploading files on Trinity on Galaxy is taking a long time, and the jobs
> also stay queued for a while. Is it always like this?
> thanks,
>
> Dario
>
> On 06/29/2016 06:25 PM, Brian Haas wrote:
> > That load wouldn't phase me personally, but if it's causing you any
> > trouble, you could kill it and rerun with a smaller --CPU number. It'll
> > pick up where it left off.
> >
> > Note, you can just run Trinity on our galaxy server and free up all your
> > resources:
> >
> > https://galaxy.ncgas-trinity.indiana.edu/user/login
> >
> > best,
> >
> > ~b
> >
> > On Wed, Jun 29, 2016 at 1:22 PM, dcopetti <notifications@github.com>
> > wrote:
> >
> > > I am running it without both bfly parameters and the server (serial, 24
> > > cores) has now a load if 68: do you think it is safe to continue or
> > shall I
> > > kill it? Shall I add --bflyCalculateCPU next time?
> > > [image: screenshot from 2016-06-29 09 56 19]
> > >
> > <
> https://cloud.githubusercontent.com/assets/13842014/16461834/5a0e717c-3de3-11e6-8f0c-3834588d9750.png
> >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > >
> > <
> https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-229426842
> >,
> > > or mute the thread
> > >
> > <
> https://github.com/notifications/unsubscribe/AHMVX_-NbpICU46ZPx1yXBaX139l8AdHks5qQqnygaJpZM4I_aRG
> >
> > > .
> > >
> >
> >
> >
> > --
> > --
> > Brian J. Haas
> > The Broad Institute
> > http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-229535744>,
>
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ANM2Xp9W0z7nBJdVGpGvBZskYmX718Zrks5qQxsagaJpZM4I_aRG
> >.
> >
>
> --
> Dario Copetti, PhD
> Research Associate | Arizona Genomics Institute
> University of Arizona | BIO5
>
> 1657 E. Helen St.
> Tucson, AZ 85721, USA
> www.genome.arizona.edu
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/156#issuecomment-230873381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX9XU3w93I5Wcn3CZhQzFy1IUQl7Tks5qS_0IgaJpZM4I_aRG>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
