### ISSUE TITLE
genome_guided_bam bam file is passed to util that is expecting a sam file

### ISSUE THREAD

**Issue by charmichaeld** [trinityrnaseq/trinityrnaseq#157]
Running Genome-guided Trinity version 2.2.0 as:
 Trinity --genome_guided_bam rnaseq_alignments.csorted.bam --max_memory 50G --genome_guided_max_intron 10000 --CPU 6

Trinity will pass the bam file directly to the following script which is expecting a sam file (at line 2673 of the perl script below):

prep_rnaseq_alignments_for_genome_assisted_assembly.pl --coord_sorted_SAM

**Comment by brianjohnhaas** [comment]
Hi Michael,

Is it not working for you with the bam file as input?  I'm pretty sure it
should use either bam or sam and not complain.

best,

~b

On Wed, Jun 29, 2016 at 6:22 PM, Michael Dickens <notifications@github.com>
wrote:

> Running Genome-guided Trinity version 2.2.0 as:
> Trinity --genome_guided_bam rnaseq_alignments.csorted.bam --max_memory 50G
> --genome_guided_max_intron 10000 --CPU 6
>
> Trinity will pass the bam file directly to the following script which is
> expecting a sam file (at line 2673 of the perl script below):
>
> prep_rnaseq_alignments_for_genome_assisted_assembly.pl --coord_sorted_SAM
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/157>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX8S_xX_vK2vXzfScxz9jM9z48tcaks5qQvAxgaJpZM4JBoE1>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by code4dna** [comment]
It works with a sam file. However, when specifying a sam file as the --genome_guided_bam file, there are some messages generated since a bam is expected:
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_index_core] Invalid BAM header.[bam_index_build2] fail to index the BAM file.

But using the command as described in the wiki by specifying a bam file does not work.
Trinity --genome_guided_bam rnaseq.coordSorted.bam

Thanks,
Michael

**Comment by charmichaeld** [comment]
I submitted that post logged in with a different account.

**Comment by el42008** [comment]
Running this command it does not recognice the option --genome_guided_bam
Trinity --genome_guided_bam merged.sort.bam --genome_guided_max_intron 15000 --SS_lib_type FR --max_memory 50G --CPU 6
Thanks

**Comment by brianjohnhaas** [comment]
at  trinityrnaseq/sample_data/test_GenomeGuidedTrinity

there's an example:

   run_genome-guided_Trinity_use_existing_bam.sh

where it runs Trinity like so:

 ../../Trinity --genome_guided_max_intron 1000 --genome_guided_bam SP2.chr.bam --max_memory 2G  --output test_GG_use_bam_trinity_outdir

and the input is a bam file.

It seems to work just fine, so I'm thinking there may have been something corrupt with the input bam fiel being used here.  If not, we can explore it further.  Please use the google group for tech support, though:

 https://groups.google.com/forum/#!forum/trinityrnaseq-users

thx!
