### ISSUE TITLE
How to minimize run time?

### ISSUE THREAD

**Issue by michaeldonaldson** [trinityrnaseq/trinityrnaseq#158]
Hi Brian, 

It's been a couple years since I used Trinity and I see there's a difference now in how the memory requirements are set. Wondering if you can comment on how to minimize run time for de novo assembly using a computer with 48G ram and 32 CPU. In the past, I used "--JM 5 --CPU 8 --normalize_reads", but I don't think "--JM" is used anymore? Reading other forums, perhaps: 

--max_memory 40G --CPU 30 --normalize_reads --bflyCPU 10 --bflyHeapSpaceMax 4G

Thanks, 
Mike

**Comment by brianjohnhaas** [comment]
sorry for the huge delay.  You probably figured it out by now... JM is replaced with --max_memory

all tech support goes through our google group:
https://groups.google.com/forum/#!forum/trinityrnaseq-users
