### ISSUE TITLE
Possible PR for code refactoring

### ISSUE THREAD

**Issue by jerowe** [trinityrnaseq/trinityrnaseq#159]
Hello,

I'm building a trinity package for bioconda, and I've been digging into the code quite a bit.

I am wondering if you would welcome/accept someone refactoring the code into a command line application framework, as opposed to a bunch of scripts calling a bunch of other scripts.  

```
Trinity assemble --seqtype fq --left --right --etc
Trinity estimate_abundance --trinity_out 
Trinity alignment_stats
... so on and so forth
```

The only code I would actually change would be to add some more verbose logging, but besides that I don't think anything really needs to be changed, just refactored to take advantage of more current best practices.

Trinity seems to be a very valuable project that has had a lot of impact on the scientific community. I'd love to contribute. Please let me know if you are interested.

Best,
Jillian

**Comment by brianjohnhaas** [comment]
Hi Jillian,

I'm certainly not against it.  I'd suggest posting this to the Trinity
google group to get a feel for how others in the community feel about it.
It would be disruptive to those that are used to the existing framework,
but after some adjustment period, I think everyone would benefit.

best,

~brian


On Sat, Jul 2, 2016 at 8:33 AM, Jillian Rowe <notifications@github.com>
wrote:

> Hello,
>
> I'm building a trinity package for bioconda, and I've been digging into
> the code quite a bit.
>
> I am wondering if you would welcome/accept someone refactoring the code
> into a command line application framework, as opposed to a bunch of scripts
> calling a bunch of other scripts.
>
> code
> Trinity assemble --seqtype fq --left --right --etc
> Trinity estimate_abundance --trinity_out
> Trinity alignment_stats
>
> The only code I would actually change would be to add some more verbose
> logging, but besides that I don't think anything really needs to be
> changed, just refactored to take advantage of more current best practices.
>
> Trinity seems to be a very valuable project that has had a lot of impact
> on the scientific community. I'd love to contribute. Please let me know if
> you are interested.
>
> Best,
> Jillian
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/159>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX-nTUfUVZXUZhgTZGGvflbtuBOiiks5qRlqIgaJpZM4JDqpT>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by jerowe** [comment]
Thanks for the quick response! I will definitely check in with the Google
group.

**Comment by jerowe** [comment]
Hi Brian,

I posted to the google group - 

https://groups.google.com/forum/#!topic/trinityrnaseq-users/QXIW7elVaAg

No opinions yet.

Best,
Jillian
