### ISSUE TITLE
Java version issue

### ISSUE THREAD

**Issue by emmamcl** [trinityrnaseq/trinityrnaseq#160]
Hi - I have been trying to run Trinity (V2.2.0 and V2.1.1.) and I keep getting an error message:
Error, Trinity requires access to Java version 1.6 or 1.7.  Currently installed version is: openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

I read that I should put in the --bypass_java_version_check but this doesn't seem to work  - I assume I am not putting it in correctly.  This is my script: 

Trinity  --seqType fq --SS_lib_type RF --left EM_10_R1_r.fastq.gz --right EM_10_R2_r.fastq.gz --bypass_java_version_check --CPU 2 --JM 1G

I also can't seem to use --max_memory 1G , it brings up an error message:

 Trinity  --seqType fq --SS_lib_type RF --left EM_10_R1_r.fastq.gz --right EM_10_R2_r.fastq.gz --CPU 2 --max_memory 1G
Error, do not understand options: --max_memory 1G

Thanks for your help,

Emma

**Comment by brianjohnhaas** [comment]
Hi Emma,

Can you try running the sample data provided at:

   trinityrnaseq/sample_data/test_Trinity_Assembly/

   sh runMe.sh

and see if that works ok?

My guess is that there are some version conflicts.   Try running Trinity
yourself by giving the full path to it as installed on your system

eg.    /full/path/to/trinityrnaseq/Trinity


best,

~b

On Mon, Jul 4, 2016 at 12:00 PM, emmamcl <notifications@github.com> wrote:

> Hi - I have been trying to run Trinity (V2.2.0 and V2.1.1.) and I keep
> getting an error message:
> Error, Trinity requires access to Java version 1.6 or 1.7. Currently
> installed version is: openjdk version "1.8.0_77"
> OpenJDK Runtime Environment (build 1.8.0_77-b03)
> OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
>
> I read that I should put in the --bypass_java_version_check but this
> doesn't seem to work - I assume I am not putting it in correctly. This is
> my script:
>
> Trinity --seqType fq --SS_lib_type RF --left EM_10_R1_r.fastq.gz --right
> EM_10_R2_r.fastq.gz --bypass_java_version_check --CPU 2 --JM 1G
>
> I also can't seem to use --max_memory 1G , it brings up an error message:
>
> Trinity --seqType fq --SS_lib_type RF --left EM_10_R1_r.fastq.gz --right
> EM_10_R2_r.fastq.gz --CPU 2 --max_memory 1G
> Error, do not understand options: --max_memory 1G
>
> Thanks for your help,
>
> Emma
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/160>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AHMVX6i4a7WTGPo2kdHudlvy1rP_Y5AIks5qSS4cgaJpZM4JEfCk>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by emmamcl** [comment]
Hi Brian,

Looks like that has solved the problem! 

Thanks again for your help! 

Emma

**Comment by brianjohnhaas** [comment]
Great to hear!

thanks,

~b

On Tue, Jul 5, 2016 at 9:38 AM, emmamcl <notifications@github.com> wrote:

> Hi Brian,
>
> Looks like that has solved the problem!
>
> Thanks again for your help!
>
> Emma
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/160#issuecomment-230480552>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX-ZUL5m_zEhqfaKFtzKEf7Ik3mT6ks5qSl5igaJpZM4JEfCk>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
