### ISSUE TITLE
error w/ grid node param propagation

### ISSUE THREAD

**Issue by bhaasIMM** [trinityrnaseq/trinityrnaseq#162]
Trinity --genome_guided_bam $HOME/scratch/data/bbmap_Lens_v1.0/sorted_BAMs/Lentils_all_samples_merged.rg.csorted.bam --CPU 12 \
--grid_conf=$TRINITY_HOME/hpc_conf/Trinity_PBSPro.conf --grid_node_CPU 4 --grid_node_max_memory 4G --max_memory 100G \
--genome_guided_max_intron 10000 --no_version_check --output $HOME/scratch/data/Trinity_GG_Lens_v1.0

Failed command:
/export/home/s2978925/etc/tools/Trinity/trinityrnaseq-2.2.0/util/support_scripts/../../Trinity --single "Dir_Lentils_all_samples_merged.rg.csorted.bam.minC1.gff/LcChr1/379/366924849_366925447.trinity.reads" --output "Dir_Lentils_all_samples_merged.rg.csorted.bam.minC1.gff/LcChr1/379/366924849_366925447.trinity.reads.out" --CPU 4 --max_memory 4G --seqType fa --trinity_complete --full_cleanup 4 --no_version_check

Error, do not understand options: 4 --no_version_check

Because this time I gave different values for --CPU (12) and --grid_conf_CPU (4), I can tell that the problem is that --grid_conf_CPU is being parsed and forwarded to ButterFly, but for some reason the value of --grid_conf_CPU is being printed again at the end.

**Comment by brianjohnhaas** [comment]
the grid exec has been completely revised for the new release.
