### ISSUE TITLE
Error in Parafly

### ISSUE THREAD

**Issue by domenico-simone** [trinityrnaseq/trinityrnaseq#163]
Hello,

I tried to run Trinity on six samples. The first time I tried, three were successful while three weren't. So I run it again on the failed datasets and it resumed the run and then immediately failed. Both times the error was this:

```
Number of Commands: 1
mv: impossibile fare stat di `/pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/104_trinity_outdir/read_partitions/Fb_0/CBin_133/c13385.trinity.reads.fa.out/inchworm.K25.L25.DS.fa.tmp': No such file or directory
Error, cmd: mv /pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/104_trinity_outdir/read_partitions/Fb_0/CBin_133/c13385.trinity.reads.fa.out/inchworm.K25.L25.DS.fa.tmp /pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/104_trinity_outdir/read_partitions/Fb_0/CBin_133/c13385.trinity.reads.fa.out/inchworm.K25.L25.DS.fa 2>tmp.5753.stderr died with ret 256 at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/PerlLib/Pipeliner.pm line 102
    Pipeliner::run('Pipeliner=HASH(0x2965dc0)') called at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/../../Trinity line 2054
    eval {...} called at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/../../Trinity line 2049
    main::run_inchworm('/pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/1...', 'single.fa', undef, '') called at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/../../Trinity line 1424
    main::run_Trinity() called at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/../../Trinity line 1206
    eval {...} called at /pica/sw/apps/bioinfo/trinity/2.1.0/milou/util/support_scripts/../../Trinity line 1205



If it indicates bad_alloc(), then Inchworm ran out of memory.  You'll need to either reduce the size of your data set or run Trinity on a server with more memory available.

succeeded(0), failed(1)   100% completed.    

We are sorry, commands in file: [FailedCommands] failed.  :-( 

Trinity run failed. Must investigate error above.

```

I don't know if this could be a memory issue (I couldn't find any `bad_alloc()` error). I'm using these settings: `--CPU 16 --max_memory 128G`. Indeed two of this three failing datasets have a way higher number of kmers (110M and 170M respectively, as counted in the `jellyfish.kmers.fa` files) than the others (average kmer number: 50M, including the third one failing).

What could be the issue?

Thanks
Domenico

**Comment by brianjohnhaas** [comment]
This type of error had shown up before when a file count quota was reached or if the file system has gotten very stressed. Trinity can generate a lot of files.  

If the run immediately fails like this on resume then it could be some other corruption issue with the corresponding mini job.  In this case, remove the mini job output directory

> /pica/v8/b2013127_nobackup/projects/domeni/aspo/RNA/trinity/104_trinity_outdir/read_partitions/Fb_0/CBin_133/c13385.trinity.reads.fa.out:

And then try resuming again.

Let's see how it goes

-Brian
(by iPhone)
