### ISSUE TITLE
assembly error

### ISSUE THREAD

**Issue by mhampton** [trinityrnaseq/trinityrnaseq#164]
Hi,

I've used Trinity many times in the past with no problems, now I am having assemblies fail on some new data.  I tried using the latest version and it fails the same way:

ERROR, no butterfly assemblies reported. at /home/mh/programs/trinityrnaseq-2.2.0/Trinity line 1262.

This is on the same computer I have used for other assemblies, and it works fine on the included test data, so I assume there is something wrong with my input.  The only difference I know of is that I am using paired-end 50bp reads, and in the past I have usually used 100bp reads.  Here is the head of one of my read files:

@700506R:580:HTTVHBCXX:1:1101:12322:1984 1:N:0:CTGAAGCT+CCTATCCT
AACAAAACAGACCAGCTGTTATTGCCACTACCGATAAACGACAAATTCACC
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@700506R:580:HTTVHBCXX:1:1101:12511:1990 1:N:0:CTGAAGCT+CCTATCCT
CTCATTTCTTGTTTTTCAGGTGTTGCCAGTTGGTTCAGTTGCAGTTGGTGT
+
DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIH

Any ideas?

Thanks,
Dr. Marshall Hampton
University of Minnesota Duluth

**Comment by mhampton** [comment]
OK now I am more confused: I just retried an assembly that I did a month ago and I now get the same error:
ERROR, no butterfly assemblies reported. at /home/mh/programs/trinityrnaseq-2.2.0/Trinity line 1262.

So presumably I have messed something up but I don't recall changing anything (e.g. I have not updated bowtie).  Also strange that it will still assemble the test data.

**Comment by mhampton** [comment]
After some random experimentation I seemed to have worked around the problem by not using the --output option; I have no idea why that should cause problems though.

**Comment by brianjohnhaas** [comment]
Sounds very strange.  I'm glad to hear it's working again.   If you learn more, I'm curious why it was acting up.  It will try to reuse output data if it was available from a previous run, which would be influenced by the output setting, in case that adds to any insights.

-Brian
(by iPhone)
