### ISSUE TITLE
can not found output folder

### ISSUE THREAD

**Issue by blithe0404** [trinityrnaseq/trinityrnaseq#165]
Hey there, I just ran trinityrnaseq on HPC with PBS script, but it is so strange that I can not find neither the  output folder nor e. file after job completed. Can you please give advice? Thanks!

Regards,
Daisy

**Comment by brianjohnhaas** [comment]
all tech support should go through the google group.  If this is still an issue, let's tackle it there:

https://groups.google.com/forum/#!forum/trinityrnaseq-users
