### ISSUE TITLE
no biological replicates && Error, not finding replicates corresponding to cond

### ISSUE THREAD

**Issue by tiramisutes** [trinityrnaseq/trinityrnaseq#166]
I am analyzing a transcriptome dataset, in which  not a  biological replicates. This mean that I haven't a tab-delimited text file indicating biological replicate relationships.
So, How can I run analyze_diff_expr.pl ?
I get an error when command with analyze_diff_expr.pl --matrix ../rsem_outdir/trans_counts_matrix.TMM.EXPR.matrix -P 1e-3 -C 2
###### 

erreo:
Error, not finding replicates corresponding to cond: counts.matrix.ALFFB_1d.  Please use the --samples parameter to specify sample/replicate relationships

Best regards
hope

**Comment by brianjohnhaas** [comment]
it's best to use our google group for tech support:

https://groups.google.com/forum/#!forum/trinityrnaseq-users

**Comment by brianjohnhaas** [comment]
the problem here was because 'matrix' was located twice in the filename.  The new release won't use filenames to extract info.
