### ISSUE TITLE
Makefile error in Chrysalis: missing -I.

### ISSUE THREAD

**Issue by hdevillers** [trinityrnaseq/trinityrnaseq#172]
While compiling Trinity (in the Chrysalis rep), I got this error message:

g++  -W -Wall -Wno-unused -Wno-deprecated -ansi -pedantic -Wno-long-long -fno-nonansi-builtins -Wctor-dtor-privacy -Wsign-promo -Woverloaded-virtual -Wendif-labels  -O3  -ggdb3 -DMAKE_DATE='"mar. sept.  6 12:09:17 CEST 2016  "' -DMAKE_OS_RELEASE='"4.7.2-201.fc24.x86_64"' -DMAKE_RELEASE='"3.0"' -DNEW_MAKEFILE -imacros system/BigFileDefines.h -pthread  -ftemplate-depth-30 -fno-strict-aliasing -mieee-fp   -fopenmp        -c ./analysis/AACodons.cc -o obj/analysis/AACodons.o
./analysis/AACodons.cc:3:32: erreur fatale : analysis/DNAVector.h : No such file or directory
 #include "analysis/DNAVector.h"

I saw in the gcc command line that there is no inlcusion instruction (-I) to include headers from the current path. By adding -I. in the Makefile corresponding to my arch (Makefile_g++_x86_64: SYS_INCS   += -I. ) complilation succeded. Not sure this is the right place to add that, I am not a makefile specialiste.

Regards

**Comment by germelcar** [comment]
Some minutes ago, I had a similar problem, and I have solved it by editing the file "Chrysalis/Makefile". I see that you also have GCC 6.X like me (I see that for the string 4.7.2-201.fc24.x86_64, that is Fedora 24 which comes with such GCC's version). You can check the issue that I just have openned and check if my solution also fix your problem at [https://github.com/trinityrnaseq/trinityrnaseq/issues/174](url).

Hope that helps.
Greetings.

**Comment by brianjohnhaas** [comment]
this should be fixed now
