### ISSUE TITLE
GCC 6 support

### ISSUE THREAD

**Issue by germelcar** [trinityrnaseq/trinityrnaseq#174]
Hello there:

I was trying to compiling Trinity 2.2.0 but it seems that there isn't support for GCC 6.X compiler. I have GCC 6.2.1 on  an Archlinux system, kernel 4.7.2.

I get the following error when I try to compile it:

> g++  -W -Wall -Wno-unused -Wno-deprecated -ansi -pedantic -Wno-long-long -fno-nonansi-builtins -Wctor-dtor-privacy -Wsign-promo -Woverloaded-virtual -Wendif-labels  -O3  -ggdb3 -DMAKE_DATE='"Fri Sep  9 19:11:22 PDT 2016  "' -DMAKE_OS_RELEASE='"4.7.2-1-ARCH"' -DMAKE_RELEASE='"3.0"' -DNEW_MAKEFILE -imacros system/BigFileDefines.h -pthread  -ftemplate-depth-30 -fno-strict-aliasing -mieee-fp   -fopenmp        -c ./aligns/KmerAlignCore.cc -o obj/aligns/KmerAlignCore.o
> ./aligns/KmerAlignCore.cc:6:34: fatal error: aligns/KmerAlignCore.h: No such file or directory
>  #include "aligns/KmerAlignCore.h"

I have checked the "KmerAlignCore.cc" file and it seems correct, later, I checked "Chrysalis/Makefile" and I saw that there isn't a validation for GCC major version 6, and then I have added the following code (I am not sure if this is the correct and professional way to do that) after line 308:

```
ifeq ($(GPP_MAJOR_VERSION),6)
       SYS_INCS        = -iquote . $(XERCES_INC)
endif
```

OK. That has solved the problem with "KmerAlignCore.h" file, but then, I have received another error:

> make[4]: Leaving directory '**...**/trinityrnaseq-2.2.0/trinity-plugins/samtools-0.1.19/misc'
> gcc -g -Wall -O2 -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o bam_tview_curses.o bam_tview_html.o  libbam.a -Lbcftools -lbcf -ltinfo -lcurses  -lm -lz -lpthread
> /usr/bin/ld: cannot find -ltinfo
> collect2: error: ld returned 1 exit status

And finally, I have solved it by installing "libtinfo" package. I don't know if this problem is for my system or something else, but I thought that it worth to mention how I have solved it in case of another Archlinux's user has the same problem.

I hope that helps.
Thanks.

**Comment by CosmikDebris** [comment]
@germelcar  I had the same errors on a Manjaro system. After applying the recommended changes and installation of "libtinfo" it worked nicely. Thanks for sharing your experience.

**Comment by germelcar** [comment]
Great. Happy to read that @CosmikDebris.

**Comment by germelcar** [comment]
Great. Happy to read that @CosmikDebris.
