### ISSUE TITLE
Differential expression

### ISSUE THREAD

**Issue by jiffen** [trinityrnaseq/trinityrnaseq#180]
Hi,
I have generated de novo assembly using trinity and did differential expression analysis using edgeR. I have 7000 transcripts which expressed deferentially. Now I want to filter out these transcripts for GO terms and I don't know how to filter from assembly. Please let me know how to obtain fasta sequences of differential expressed transcripts from assembly.

Thanks

**Comment by gringer** [comment]
$ samtools faidx myTranscripts.fa # create index for transcript fasta file
    $ cat listOfTranscripts.txt | parallel -m samtools faidx mytranscripts.fa {} > DETranscripts.fa # write out sequences
