### ISSUE TITLE
build: does automake have to be version specific (1.11)

### ISSUE THREAD

**Issue by sammyjava** [trinityrnaseq/trinityrnaseq#19]
Not a critical issue, obviously, but the current build throws this warning on my Fedora 21 system:
```
/home/sam/trinityrnaseq/Inchworm/missing: line 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
```
I've got automake, but it's version 1.14
```
Installed Packages
automake.noarch            1.14.1-5.fc21                                   installed
```
Just thought I'd mention it. :)

**Comment by brianjohnhaas** [comment]
Hi Sam,

Just to confirm - this is with Trinity v2.0.6?   I remember there was an issue with 2.0.5 but I was hoping we corrected it.

thx,

~brian

**Comment by sammyjava** [comment]
Ahhhh, you did! Build delay effect - I had done a git pull to get the 2.0.6 updates, but the Makefile was still the one built with 2.0.5 - so it threw the warning. But now when I make again, no warning! I guess the rule of thumb is "make twice". Cheers!

**Comment by brianjohnhaas** [comment]
fantastic! :)

On Sun, Mar 15, 2015 at 10:01 AM, Sam Hokin <notifications@github.com>
wrote:

> Ahhhh, you did! Build delay effect - I had done a git pull to get the
> 2.0.6 updates, but the Makefile was still the one built with 2.0.5 - so it
> threw the warning. But now when I make again, no warning! I guess the rule
> of thumb is "make twice". Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/19#issuecomment-81016384>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
