### ISSUE TITLE
Support for java 1.8

### ISSUE THREAD

**Issue by cboursnell** [trinityrnaseq/trinityrnaseq#20]
I get this error when running Trinity v2.0.6

```
Error, Trinity requires access to Java version 1.7.  Currently installed version is: java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```
I know there's a `--bypass_java_version_check` but could you just change
`if ($version_id != 7) {`
to
`if ($version_id < 7) {`
in the main script?

**Comment by brianjohnhaas** [comment]
We could certainly do this if you don't encounter any errors with v8.  In
the past, when we built the jar using v6, certain errors would occur with
v7, so I'm not sure how backwards compatible v8 will be.

best,

~brian


On Tue, Mar 31, 2015 at 9:37 AM, Chris Boursnell <notifications@github.com>
wrote:

> I get this error when running Trinity v2.0.6
>
> Error, Trinity requires access to Java version 1.7.  Currently installed version is: java version "1.8.0_31"
> Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
>
> I know there's a --bypass_java_version_check but could you just change
> if ($version_id != 7) {
> to
> if ($version_id < 7) {
> in the main script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/20>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
set check for min 1.7
