### ISSUE TITLE
New FASTA header format breaks parsers

### ISSUE THREAD

**Issue by Blahah** [trinityrnaseq/trinityrnaseq#21]
Our users (of transrate) have reported that Trinity has moved to using a hew FASTA header format that looks like:
`>TR18|c0_g1_i1 len=387 path=[365:0-386] [-1, 365, -2]`. (see issue https://github.com/Blahah/transrate/issues/127, some of which I have copied below).

In the example above, it's clear that `TR18|c0_g1_i1` is supposed to be the entry ID. However, many bio-library parsers will not interpret it that way. In 2003 or so, NCBI claimed that using the `>db_name|sequence_identifier` format was standard, but that system is very non-standard in practise, outside of the NCBI. Almost every other system uses `>sequence_identifier|other description`.

transrate uses the BioRuby FASTA parser, which has a pretty sensible design - it interprets everything before the first `|` or space as the sequence identifier, except in special cases for the NCBI databases. This accurately captures the FASTA header information for hundreds of pieces of bioinformatics software, but currently not for Trinity.

With this new Trinity setup we are forced to decide between adding another special case to BioRuby for Trinity, or hacking around this change in any software that wants to read Trinity sequence IDs. However, the third option is for the change in Trinity to be reverted. I would argue for this third option on the basis that it requires the least changes throughout the community. Would you consider this?

**Comment by brianjohnhaas** [comment]
I'm not against making it 'TR_c_g_i' and getting rid off the |

would that work?

best,

~brian


On Thu, Apr 2, 2015 at 4:12 PM, Richard Smith-Unna <notifications@github.com
> wrote:

> Our users (of transrate) have reported that Trinity has moved to using a
> hew FASTA header format that looks like:
> >TR18|c0_g1_i1 len=387 path=[365:0-386] [-1, 365, -2]. (see issue
> Blahah/transrate#127 <https://github.com/Blahah/transrate/issues/127>,
> some of which I have copied below).
>
> In the example above, it's clear that TR18|c0_g1_i1 is supposed to be the
> entry ID. However, many bio-library parsers will not interpret it that way.
> In 2003 or so, NCBI claimed that using the >db_name|sequence_identifier
> format was standard, but that system is very non-standard in practise,
> outside of the NCBI. Almost every other system uses >sequence_identifier|other
> description.
>
> transrate uses the BioRuby FASTA parser, which has a pretty sensible
> design - it interprets everything before the first | or space as the
> sequence identifier, except in special cases for the NCBI databases.
>
> With this new Trinity setup we are forced to decide between adding another
> special case to BioRuby for Trinity, or hacking around this change in any
> software that wants to read Trinity sequence IDs. However, the third option
> is for the change in Trinity to be reverted. I would argue for this third
> option on the basis that it requires the least changes throughout the
> community. Would you consider this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/21>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by sammyjava** [comment]
I'll chime in on this - BioJava's FastaReaderHelper also drops everything past the pipe character, so I've found myself having to write scripts in Python simply to avoid that happening. I've also replaced '|' in Trinity.fasta to be able to use BioJava, which isn't optimal. It's a shame, because I like the '|' syntax, but it seems a lot of progs consider that to be a comment delimiter as mentioned above.

**Comment by Blahah** [comment]
Great! Moving to `TR_c_g_i` would solve the issue.

**Comment by brianjohnhaas** [comment]
We'll definitely do this for the next release.

**Comment by Blahah** [comment]
Thanks very much @brianjohnhaas :)

**Comment by brianjohnhaas** [comment]
now reports accessions as TRINITY_DN$number_c$number2_g$number3_i$number4

or TRINITY_GG....  for genome-guided.   Pipes are gone.
