### ISSUE TITLE
Trinity 2.4.0 (Abundance estimation) Bowtie/RSEM problem - invalid BAM binary header

### ISSUE THREAD

**Issue by wasphunter** [trinityrnaseq/trinityrnaseq#225]
Hi. I attempted abundance estimation in two steps using RSEM but have encountered some problems. I ran the --prep_reference command first and obtained an rsem.prepped.ok file among others suggesting all went well. In my second run, I moved the sequence files to be mapped into the output file resulting from the --prep_reference run then used the following script: 

--transcripts Trinity.fasta --seqType fq --left R1_file01.fq --right R2_file01.fq --est_method RSEM --aln_method bowtie --trinity_mode --thread_count 4 --coordsort_bam --output_dir /test_rsem

I didn't receive any output from this second run.  The log file reports alignment statistics for my reads  followed by a number of errors.  Any suggestions you can offer to help me fix the problems would be appreciated.  

########
Reported 2744241 paired-end alignments to 1 output stream(s)
CMD: touch bowtie.bam.ok
CMD: rsem-calculate-expression  --paired-end   -p 4    --no-bam-output --bam bowtie.bam /local/904065/rsem.test.904065/Trinity.fasta.RSEM RSEM
rsem-parse-alignments /local/904065/rsem.test.904065/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM b bowtie.bam -t 3 -tag XM
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Fail to parse sam header!
"rsem-parse-alignments /local/904065/rsem.test.904065/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM b bowtie.bam -t 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!
Error, cmd: rsem-calculate-expression  --paired-end   -p 4    --no-bam-output --bam bowtie.bam /local/904065/rsem.test.904065/Trinity.fasta.RSEM RSEM  died with ret: 65280 at /opt/packages/trinity/2.4.0/util/align_and_estimate_abundance.pl line 766.
########

The "Trinity.fasta.RSEM RSEM" at the end of the rsem-calculate-expression command seems odd but it's not clear if I did something to create this problem.  For compatibility questions, I'm using the following:

module load bowtie/1.1.2
module load samtools/1.3
module load R/3.2.3-mkl
module load trinity/2.4.0
module load rsem/1.2.21

Thanks again for any help you can offer.

**Comment by nickxzshi** [comment]
Sorry,i meet the question too.did you solve it ?

**Comment by jiededav** [comment]
Sorry,i meet the question too.did you solve it ?

again & again
