### ISSUE TITLE
Disappearing unaligned reads file in align_and_estimate_abundance.pl

### ISSUE THREAD

**Issue by ddonnell** [trinityrnaseq/trinityrnaseq#234]
ISSUE: I'm experiencing poor mapping rates (~64%) of reads against my Trinity assembly and so interested in learning which read pairs don't align in my RSEM analysis. Consequently, I'm running the Trinity utility script "align_and_estimate_abundance.pl" with the --debug parameter so as to capture the intermediate files.

If I go into the output directory/RSEM.temp when the run is ~2/3 of the way towards completion, I can see the following:
RSEM_alignable_1.fq  RSEM_alignable_2.fq  RSEM.dat  RSEM_max_1.fq  RSEM_max_2.fq  RSEM.omit  RSEM_un_1.fq  RSEM_un_2.fq

The unaligned reads are presumably going to be collected in the last two files.  

If I wait for the run to finish then go into RSEM.temp I see the following:
RSEM_alignable_1.fq       RSEM_alignable_2.fq       RSEM.dat       RSEM.iso_res  RSEM.omit
RSEM_alignable_1.fq.ridx  RSEM_alignable_2.fq.ridx  RSEM.gene_res  RSEM.mparams

Note that some of the files present at mid-run are gone in the final version of the directory.  Most disconcertingly, the unaligned read files are gone. Does --debug have a bug or am I doing something wrong if I want to capture the unaligned reads?

Any advice would be appreciated.

BACKGROUND:
These are my script parameters:

--seqType fq \
--left DD01_R1_6mill_qtrim.P.fq.gz \
--right DD01_R1_6mill_qtrim.P.fq.gz \
--est_method RSEM \
--aln_method bowtie \
--trinity_mode \
--prep_reference \
--debug \
--coordsort_bam \
--output_dir /.........$name

**Comment by brianjohnhaas** [comment]
I'd suggest just running bowtie2 directly and collecting unaligned reads by using one of the bowtie2 parameter settings

-Brian
(by iPhone)
