### ISSUE TITLE
(ERR): bowtie2-align died with signal 13 (PIPE)

### ISSUE THREAD

**Issue by kamivain** [trinityrnaseq/trinityrnaseq#235]
Hello! When I run Trinity , I encountered an issue as following.

(ERR): bowtie2-align died with signal 13 (PIPE) 
bash: line 1: 17044 Exit 1                  bowtie2 --local -k 2 --threads 8 -f --score-min G,46,0 -x /home/user01/Desktop/YXR/rsequence/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 /home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa
     17045 Broken pipe             | samtools view -@ 8 -F4 -Sb -
     17046 Killed                  | samtools sort -m 1342177280 -@ 8 -no - - > /home/user01/Desktop/YXR/rsequence/trinity_out_dir/chrysalis/iworm.bowtie.nameSorted.bam
Error, cmd: bash -c " set -o pipefail;bowtie2 --local -k 2 --threads 8 -f --score-min G,46,0 -x /home/user01/Desktop/YXR/rsequence/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 /home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa  | samtools view -@ 8 -F4 -Sb - | samtools sort -m 1342177280 -@ 8 -no - - > /home/user01/Desktop/YXR/rsequence/trinity_out_dir/chrysalis/iworm.bowtie.nameSorted.bam"  2>tmp.16701.stderr died with ret 35072 at /home/user01/Desktop/YXR/rsequence/trinityrnaseq-Trinity-v2.4.0/PerlLib/Pipeliner.pm line 166
        Pipeliner::run('Pipeliner=HASH(0x126b8a0)') called at ./trinityrnaseq-Trinity-v2.4.0/Trinity line 1750
        main::run_chrysalis('/home/user01/Desktop/YXR/rsequence/trinity_out_dir/inchworm.K...', '/home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa', 200, 500, undef, '/home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa', '/home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa') called at ./trinityrnaseq-Trinity-v2.4.0/Trinity line 1595
        main::run_Trinity() called at ./trinityrnaseq-Trinity-v2.4.0/Trinity line 1262
        eval {...} called at ./trinityrnaseq-Trinity-v2.4.0/Trinity line 1261

Trinity run failed. Must investigate error above.

**Comment by brianjohnhaas** [comment]
It looks like this command was killed for some reason 


 bowtie2 --local -k 2 --threads 8 -f --score-min G,46,0 -x /home/user01/Desktop/YXR/rsequence/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 /home/user01/Desktop/YXR/rsequence/trinity_out_dir/both.fa

You might try running it directly and see if it gives you a more informative error message.  Just be sure to direct the output to a file 

   Ex. 
           Cmd   >  out


-Brian
(by iPhone)

**Comment by dbrowneup** [comment]
I just encountered the same problem. I found that the error occurred because the system ran out of memory. It was my own fault, as I had allocated only 900G of RAM, but set `--max_memory 1800G`.

**Comment by DevonJBoland** [comment]
@dbrowneup literally just ran into the same problem. Ended up in the same issue thread for the same reason.
