### ISSUE TITLE
remove transdecoder from trinity-plugins

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#24]
It's unnecessary to bundle it in at this point.

**Comment by kk86bioinfo** [comment]
So the documentation of https://trinityrnaseq.github.io/analysis/extract_proteins_from_trinity_transcripts.html will not working any more by now right?

**Comment by brianjohnhaas** [comment]
The documentation will be updated to point to using the latest version of
TransDecoder, which you can find at: http://transdecoder.github.io

On Wed, May 13, 2015 at 12:00 PM, kk_loke86 <notifications@github.com>
wrote:

> So the documentation of
> https://trinityrnaseq.github.io/analysis/extract_proteins_from_trinity_transcripts.html
> will not working any more by now right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/24#issuecomment-101482001>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by kk86bioinfo** [comment]
Thanks @brianjohnhaas

**Comment by brianjohnhaas** [comment]
documentation is now updated
