### ISSUE TITLE
Instructions for System-wide Install

### ISSUE THREAD

**Issue by DarioS** [trinityrnaseq/trinityrnaseq#255]
After compiling Trinity, what is the minimum set of executables which should be copied to somewhere like `/usr/local/bin/` to make the software runnable for everyone with an account on the server? I'd like to see these details on the [Installing Trinity](https://github.com/trinityrnaseq/trinityrnaseq/wiki/Installing-Trinity) webpage. Or do the various components rely on the directory structure being preserved? Perhaps the Installing Trinity webpage could also describe the `$TRINITY_HOME` variable and whether it's only a user variable for writing conveniently short commands or a required pipeline variable.

**Comment by brianjohnhaas** [comment]
in the upcoming release, we'll have a 'make install' that'll put the package at /usr/local/bin/trinityrnaseq
and indicate to set the env var to TRINITY_HOME

I'll add info in the documentation as well.   Also, the amount of test data has been de-bulked to better minimize the basic installation footprint.
