### ISSUE TITLE
Incomplete Refactoring of Python Scripts

### ISSUE THREAD

**Issue by DarioS** [trinityrnaseq/trinityrnaseq#256]
The code pattern

```
TRINITY_BASE_DIR = ""
if os.environ.has_key('TRINITY_HOME'):
    TRINITY_BASE_DIR = os.environ['TRINITY_HOME'];
else:
sys.stderr.write("You must set the environmental variable TRINITY_BASE_DIR to the base installation directory of Trinity before running this");
```

is used in a number of places. It checks for the environment variable `TRINITY_HOME` and, if it isn't present, it displays an error message telling the user to create a variable `TRINITY_BASE_DIR` which is set to empty before the `if` statement. Perhaps the message should recommend to create `TRINITY_HOME` rather than `TRINITY_BASE_DIR`. `TRINITY_BASE_DIR` may be set to `TRINITY_HOME` but is not used anywhere else in the Python scripts. It seems that some kind of refactoring was never completed.

**Comment by brianjohnhaas** [comment]
fixed
