### ISSUE TITLE
Trinity doesn't report errors very clearly.

### ISSUE THREAD

**Issue by jairly** [trinityrnaseq/trinityrnaseq#262]
Running out of RAM results in a very long output message that is difficult to understand. It could just say "I ran out of RAM" instead.

Providing fastq files with spaces in also gives a very long and complex error message output, with no mention of what the problem is. Took me six months to solve this problem, when Trinity could have just said "I don't like files with spaces in."

I think there are others too but I can't think of them now. Could Trinity errors be made clearer.

**Comment by brianjohnhaas** [comment]
feel free to report issues to our google forum.  Troubleshooting should ideally take minutes or hours not weeks or months.

cheers
