### ISSUE TITLE
collectl issues

### ISSUE THREAD

**Issue by SherryLab** [trinityrnaseq/trinityrnaseq#269]
Very minor issue but I though it might be worth reporting.
When Trinity is compiled, /Trinity/trinity-plugins/COLLECTL/collectl-4.1.0.src.tar.gz is not unpacked. When --monitoring is called on a Trinity run, the error is reported:
nohup: failed to run command '[path]/Trinity/trinity-plugins/COLLECTL/collectl/collectl': No such file or directory
Furthermore, the collectl subdirectory is created in the working directory, but collectl.dat is empty

To get collectl to work, you will need to do the following after installing Trinity
1) go to /path/to/Trinity/trinity-plugins/COLLECTL/
2) unzip the collectl-4.1.0.src.tar.gz
3) rename collectl-4.1.0 to collectl

Maybe those steps can be added to the makefile?

**Comment by brianjohnhaas** [comment]
Thx for pointing this out.  I added  a note to the progress monitoring documentation that you must type 'make plugins' to install the trinity plugins including collectl.

**Comment by wolfQK** [comment]
Hi,
    I installed Trinity-2.11.0 via conda, and I run Trinity with parameter “--monitoring”，but I cannot find anything about the output of collectl. How can I use it correctly?
     Thank you !
