### ISSUE TITLE
transcripts with abundance zero for every condition

### ISSUE THREAD

**Issue by santiagorevale** [trinityrnaseq/trinityrnaseq#276]
Hi there,

This is a question more than an issue. I've built a transcriptome using the PASA methodology (dnv assembly + reference assembly + PASA pipeline) using both control + condition samples together.

Later, I've performed the abundance estimation using the four described methods in the documentation (RSEM, eXpress, Salmon and Kallisto) and built the abundance estimation matrix. However, when I checked the files, I've realised that more than 5k transcripts had an abundance of zero for every condition. When I checked the alignment files no read was aligning against them.

My question then is: how is it possible that so many transcripts didn't have any hit at all if the transcriptome? I've noticed that most of these transcripts came from the reference assembly rather than from the de novo (reference or PASA assembly, the IDs start with ```asmbl``` instead of ```TRINITY_DN```, there are no ```TRINITY_GG```). Could it be that the reference and/or PASA assembly is producing many chimeras? Also, most of the sequences belong have the ```pasa``` description in the ```compreh_init_build.details```

These are the exact numbers:

```
Total transcripts : 54,892
Total unique transcripts with zero count : 12,965

           total  TRINITY_DN  asmbl
--------  ------  ----------  -----
 express   5,034         448  4,586
kallisto   5,990         964  5,026
    rsem  11,218       1,738  9,480
  salmon   5,722         872  4,850
```

I've also see the following comment in the documentation 

> Note that some transcripts may have artificially low (or zero) expression values simply because they are incompletely assembled and do not recruit both pairs of PE reads in order to be properly accounted for during abundance estimation.

but I don't think this is what's happening here. There are transcripts that don't have any read mapped and others which are very big (12kb) that have many reads mapped but still shown as no abundance.

Any insights on what could be going on would be really appreciated.

Thank you very much in advance.

Best regards,
Santiago

**Comment by brianjohnhaas** [comment]
Hi Santiago,

I'm curious why this is happening as well.  One thing you can try, for the sake of comparison, is to run htseq to quantify the asmbl types by the read-to-genome alignments (bam file).  It would be useful to know if the zero-entries from the transcript-based quantifications have the lowest read counts based on the genome alignments (as quant by htseq).
Other reasons why transcripts might show up w/ zero isoforms would include multi-mapping reads where one isoform is assigned all the reads.   Those isoforms that get zero expression values assigned across all conditions would, in theory, be the lowest quality reconstructions and could get filtered out.  Once I can find some time, I'd like to look into this further myself as well.
