### ISSUE TITLE
diff of min_pct_iso and min_pct_dom_iso

### ISSUE THREAD

**Issue by wangyugui** [trinityrnaseq/trinityrnaseq#281]
Hi.

${TRINITY_HOME}/util/abundance_estimates_to_matrix.pl  report both pct_iso_expr and pct_dom_iso_expr.
>TRINITY_DN795_c0_g1_i1 top_iso:1 pct_iso_expr=79.13 pct_dom_iso_expr=100.00

what is the diff?

And filter_low_expr_transcripts.pl support --min_pct_dom_iso and --highest_iso_only options.
(mutually exclusive with --min_pct_iso param)
should be
(mutually exclusive with --min_pct_dom_iso param) ?

**Comment by wangyugui** [comment]
And there other samples

```
>TRINITY_DN142767_c0_g2_i2 top_iso:0 pct_iso_expr=32.54 pct_dom_iso_expr=65.18
>TRINITY_DN142767_c0_g2_i3 top_iso:0 pct_iso_expr=14.07 pct_dom_iso_expr=28.18
>TRINITY_DN142767_c0_g2_i4 top_iso:1 pct_iso_expr=49.92 pct_dom_iso_expr=100.00
```

**Comment by wangyugui** [comment]
please fix the help output in next version.

(mutually exclusive with --min_pct_iso param)
should be
(mutually exclusive with --min_pct_dom_iso param)

**Comment by brianjohnhaas** [comment]
done
