### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by haoyanioz** [trinityrnaseq/trinityrnaseq#293]
Hi Brian,

I‘m sorry to say there‘s another error here as shown below.

warning, command: /home/quyh/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/../../Trinity --single "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275574.trinity.reads.fa" --output "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275574.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup   has successfully completed from a previous run.  Skipping it here.
warning, command: /home/quyh/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/../../Trinity --single "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275575.trinity.reads.fa" --output "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275575.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup   has successfully completed from a previous run.  Skipping it here.
warning, command: /home/quyh/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/../../Trinity --single "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275576.trinity.reads.fa" --output "/home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275576.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup   has successfully completed from a previous run.  Skipping it here.
Number of Commands: 2
/bin/sort: fflush failed: standard output: No such file or directory
/bin/sort: write error
Trinity run failed. Must investigate error above.

succeeded(0), failed(1)   50% completed.    bowtie2-align died with signal 11 (SEGV) (core dumped)
Trinity run failed. Must investigate error above.

succeeded(0), failed(2)   100% completed.    

We are sorry, commands in file: [FailedCommands] failed.  :-( 

Error, cmd: /home/quyh/trinityrnaseq-Trinity-v2.4.0/trinity-plugins/parafly/bin/ParaFly -c recursive_trinity.cmds -CPU 10 -v  died with ret 256 at /home/quyh/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.

Trinity run failed. Must investigate error above.

Could you please give me some suggestions? Many thanks.

Yan

**Comment by PatrickDouglasCP** [comment]
You tried to the the **Trinity_output_dir** folder to make sure that the commands creates new files?

**Comment by bhaasIMM** [comment]
The error 'bowtie2-align died with signal 11 (SEGV) (core dumped)'   is troubling.  You might update your bowtie2 installation if it's old, or skip the bowtie step w/ the Trinity --no_bowtie parameter.

If the job has corrupt output files for those mini-jobs, try deleting each failed command's output directories like:

  /home/quyh/tit_trinity/Heto_trinity/read_partitions/Fb_2/CBin_2755/c275575.trinity.reads.fa.out

before rerunning your original Trinity command to rerun them.

Sorry for the delay in responding.  This one escaped my attention for some reason.

best,

~b
