### ISSUE TITLE
Genome Guided Trinity Transcriptome Assembly Gene Names

### ISSUE THREAD

**Issue by DarioS** [trinityrnaseq/trinityrnaseq#296]
Transcriptome assembly guided by the genome is likely to have a detailed gene annotation available. Based on the Wiki explanation, there doesn't seem to be any way to provide a GTF or GFF3 file to easily annotate the assembled transcripts with putative gene symbols. Trinotate seems to be suitable for a different use case, where there is little annotation available for the organism sequenced.

**Comment by brianjohnhaas** [comment]
you can probably use a tool like cuffcompare or something similar.
