### ISSUE TITLE
direct reading of gzip files

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#31]
instead of dumping to uncompressed fastq first.

**Comment by benfulton** [comment]
When providing gzip'd files on command line

**Comment by brianjohnhaas** [comment]
Ben - we can close this, right?

**Comment by benfulton** [comment]
It should close automatically once the development branch is merged to master.

**Comment by brianjohnhaas** [comment]
Fancy!

I've just been closing them out one-by-one.   I'll merge everything into
the master soon.
