### ISSUE TITLE
Trinity with --PasaFly or --CuffFly fails to harvest assembled transcripts

### ISSUE THREAD

**Issue by zafu-lhuang** [trinityrnaseq/trinityrnaseq#312]
Code version: 750c624, File: Trinity, Line: 2129

The command constructed from
`my $cmd = "find read_partitions/  -name '*inity.fasta'  | $UTILDIR/support_scripts/partitioned_trinity_aggregator.pl TRINITY_DN > Trinity.fasta.tmp";`
fails to harvest assembled transcripts when Trinity is run with --PasaFly or --CuffFly, because the individual assembled transcripts are named Trinity.Pasafly.fasta or Trinity.Cufffly.fasta.

My Trinity command is:
```
${TRINITY_HOME}/Trinity \
    --no_version_check \
    --no_cleanup \
    --seqType fq --SS_lib_type RF  \
    --left RNASEQ_data/Sp_log.left.fq.gz,RNASEQ_data/Sp_hs.left.fq.gz,RNASEQ_data/Sp_ds.left.fq.gz,RNASEQ_data/Sp_plat.left.fq.gz \
    --right RNASEQ_data/Sp_log.right.fq.gz,RNASEQ_data/Sp_hs.right.fq.gz,RNASEQ_data/Sp_ds.right.fq.gz,RNASEQ_data/Sp_plat.right.fq.gz \
    --CPU 24 --max_memory 48G \
    --CuffFly
```
It seems the failure only shows up with --no_cleanup option. Without the option, the individual fasta files are c*.trinity.reads.fa.out.Trinity.fasta, and can be successfully found by the Trinity script.

**Comment by brianjohnhaas** [comment]
pasafly and cufffly are deprecated for the time being.  We might return to supporting them again at some point but it's taken too much effort to maintain them while the codebase has been heavily restructured.
