### ISSUE TITLE
Samples.txt sheet clarification

### ISSUE THREAD

**Issue by lfaller** [trinityrnaseq/trinityrnaseq#320]
Hi all,

I am curious about setting up the samples.txt file.

Your example reads as follows:

```
#      --samples_file <string>         tab-delimited text file indicating biological replicate relationships.
 #                                   ex.
 #                                        cond_A    cond_A_rep1    A_rep1_left.fq    A_rep1_right.fq
 #                                        cond_A    cond_A_rep2    A_rep2_left.fq    A_rep2_right.fq
 #                                        cond_B    cond_B_rep1    B_rep1_left.fq    B_rep1_right.fq
 #                                        cond_B    cond_B_rep2    B_rep2_left.fq    B_rep2_right.fq
```

What is the result of this analysis?

Will Trinity generate two assemblies, one for each condition?
Will these be put into two separate output directories?
Does the samples.txt file need the '#' in the beginning of the lines?

Thanks for clarifying!

**Comment by brianjohnhaas** [comment]
apologies for the delay in responding...

The format is just a simple tab-delimited formatting, without the # characters:

sample_name(tab)replicate_name(tab)path/to/left.fq(tab)path/to/right.fq

Trinity generates a single assembly from all of the reads.
