### ISSUE TITLE
Trinity fails during Jellyfish: "both.fa died with ret 9 at line 758"

### ISSUE THREAD

**Issue by awolfewood** [trinityrnaseq/trinityrnaseq#322]
Hi,

My assembly log file shows that Trinity dies during the Jellyfish step. It reports two errors, one with "trinity-plugins/jellyfish/bin/jellyfish" and one with "insilico_read_normalization.pl":

> -------------------------------------------
> ----------- Jellyfish  --------------------
> -- (building a k-mer catalog from reads) --
> -------------------------------------------
> 
> CMD finished (1 seconds)
> 
> CMD: /sw/med/centos7/trinity/2.4.0/util/..//trinity-plugins/jellyfish/bin/jellyfish count -t 8 -m 25 -s 6270985349  --canonical  both.fa
> 
> Error, cmd: /sw/med/centos7/trinity/2.4.0/util/..//trinity-plugins/jellyfish/bin/jellyfish count -t 8 -m 25 -s 6270985349  --canonical  both.fa died with ret 9 at /sw/med/centos7/trinity/2.4.0/util/insilico_read_normalization.pl line 758.
> 
> Error, cmd: /sw/med/centos7/trinity/2.4.0/util/insilico_read_normalization.pl --seqType fq --JM 46G  --max_cov 50 --CPU 8 --output /scratch/awwood_flux/awwood/assemblies/abb/new_assem/abb1_trinity/insilico_read_normalization   
> --max_pct_stdev 10000  --left abb1_R1.fastq.gz.PwU.qtrim.fq --right abb1_R2.fastq.gz.PwU.qtrim.fq 
> --pairs_together --PARALLEL_STATS   died with ret 512 at /sw/med/centos7/trinity/2.4.0/Trinity line 2462.

**********************
I am using Trinity on an HPC cluster, and there don't seem to be any problems with how it's installed: I downloaded sample data from the Trinity workshop, and it assembled flawlessly.

After reading some of the posts here and elsewhere, I thought my data may be formatted incorrectly, they _seem_ to be fine. Here's an example fastq header:

> @K00135:53:H5TFKBBXX:8:1101:1022:1121 1:N:0:NCTGAT

I've tried supplying my data to Trinity in a variety of different ways. I've tried running Trimmomatic separately and supplying only the _1P.fq/_2P.fq files as my --left and --right reads. I've tried converting the files to trinity fasta files using Fastool (--illumina-trinity command). And a few other ways.

I've attached the complete log file to provide more context.
[abb1.txt](https://github.com/trinityrnaseq/trinityrnaseq/files/1257224/abb1.txt)

I'm new to this, and I'm not sure what to try next.  Any ideas about what's going on?

Thanks very much for your time,

Andrew Wood

**Comment by brianjohnhaas** [comment]
handled through the google forum.
