### ISSUE TITLE
How to do DE analysis considering ‘sex’ as a random-effects factor?

### ISSUE THREAD

**Issue by hao091012** [trinityrnaseq/trinityrnaseq#327]
Hi Brain，
Thanks for your script (run_DE_analysis.pl). I use your script to do differential expression analysis based on four methods you provided. But I noticed it didn't consider "sex" or other factors. If I wanna consider the random-effects factor, what should I do? And what criteria do you recommend to determine the DEG?(fold change: ?, padj: ?)
Any help will be appreciated. 

Sincerely
Yan

**Comment by DarioS** [comment]
Why do you consider gender as a random effect? There are only two possible factor levels (male, female) and you have measurements for both. Therefore, it should be modelled as a fixed effect.
