### ISSUE TITLE
align_and_estimate_abundance.pl default set to coordsort_bam_flag to 0?

### ISSUE THREAD

**Issue by kk86bioinfo** [trinityrnaseq/trinityrnaseq#33]
For the abundance estimation documentation, the following is not longer valid as the coordsort_bam_flag is set to 0 by default.

``
The alignment step generates the file bowtie.bam, which is then fed directly into either RSEM or eXpress. Note, the alignment step also generates a bowtie.csorted.bam file, which is a coordinate-sorted bam file that can be used for visualization using IGV (see below).
``

Is the documentation going to be updated or the perl script need to change?

**Comment by brianjohnhaas** [comment]
will update the documentation for next release.

**Comment by brianjohnhaas** [comment]
documentation is now updated
