### ISSUE TITLE
align_and_estimate_abundance script to make use of strandness when kallisto is used

### ISSUE THREAD

**Issue by rspreafico** [trinityrnaseq/trinityrnaseq#330]
Hi,

congrats for this great tool!

Kallisto now supports RF and FR strandness for PE reads. I was wondering whether the align_and_estimate_abundance.pl script can honor the `--SS_lib_type` parameter even when `--est_method kallisto`. For SE, since Kallisto does not support strandness, it may warn the user (as opposed to silently ignore the `--SS_lib_type` parameter).

Thank you!

**Comment by brianjohnhaas** [comment]
Thanks for pointing this out.  I'm adding it to the next release.
