### ISSUE TITLE
is scaffold_iworm_contigs still used ?

### ISSUE THREAD

**Issue by EricDeveaud** [trinityrnaseq/trinityrnaseq#334]
While looking at the code of trinityrnaseq-2.4.0 

I see that scaffold_iworm_contigs is not built  (and can't be built using the actual Makefile)

but Trinity code holds the following

```
            ## generate the scaffold info
            $ENV{'LD_LIBRARY_PATH'} .= ":$ROOTDIR/trinity-plugins/htslib";
            
            if ($USE_PERL_SCAFFOLDER) {
                $cmd = "$ROOTDIR/util/support_scripts/scaffold_iworm_contigs.pl $bowtie_sam_file $inchworm_file > $iworm_scaffolds_file";
            }
            else {
                $cmd = "$ROOTDIR/trinity-plugins/scaffold_iworm_contigs/scaffold_iworm_contigs $bowtie_sam_file $inchworm_file > $iworm_scaffolds_file"; # important, must use original inchworm file because positions are indexed for later use by GraphFromFasta
            }
```

nor trinity-plugins/htslib, nor  trinity-plugins/scaffold_iworm_contigs/scaffold_iworm_contigs are created

regards

Eric

**Comment by brianjohnhaas** [comment]
Thanks for pointing this out.  At some point I need to revisit the c++ code there and leverage instead of the perl code, but the perl code was easier to tweak as we need it right now.   I've updated the wrapper accordingly for now.
