### ISSUE TITLE
Error while assemble single fastq files 

### ISSUE THREAD

**Issue by patrick-douglas** [trinityrnaseq/trinityrnaseq#335]
Since trinity 2.4 version there is an error while I try assembly Ion Torrent single and fastq files, see log below.
```
~/trinityrnaseq-Trinity-v2.4.0/Trinity --seqType fq --single /local/BACK_UP_3/todos_um.fastq --max_memory 120G --CPU 12 -grid_node_CPU 12 --grid_node_max_memory 30G --grid_exec "/home/me/HpcGridRunner/hpc_cmds_GridRunner.pl --grid_conf /home/me/HpcGridRunner/PBS.trinity.conf --parafly -c" --output /home/me/trimed-test/todos_um_trimed_trinity_out --no_bowtieSingle read files: $VAR1 = [
          '/local/BACK_UP_3/todos_um.fastq'
        ];
Trinity version: Trinity-v2.4.0
-currently using the latest production release of Trinity.

Tuesday, September 26, 2017: 09:51:54	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/me/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ExitTester.jar 0
Tuesday, September 26, 2017: 09:51:54	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/me/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ExitTester.jar 1
Tuesday, September 26, 2017: 09:51:55	CMD: mkdir -p /home/me/trimed-test/todos_um_trimed_trinity_out
Tuesday, September 26, 2017: 09:51:55	CMD: mkdir -p /home/me/trimed-test/todos_um_trimed_trinity_out/chrysalis


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

---------------------------------------------------------------
------------ In silico Read Normalization ---------------------
-- (Removing Excess Reads Beyond 50 Coverage --
---------------------------------------------------------------

# running normalization on reads: $VAR1 = [
          [
            '/local/BACK_UP_3/todos_um.fastq'
          ]
        ];


Tuesday, September 26, 2017: 09:51:55	CMD: /home/me/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl --seqType fq --JM 120G  --max_cov 50 --CPU 12 --output /home/me/trimed-test/todos_um_trimed_trinity_out/insilico_read_normalization   --max_pct_stdev 10000  --single /local/BACK_UP_3/todos_um.fastq
CMD: seqtk-trinity seq -A /local/BACK_UP_3/todos_um.fastq >> single.fa
Error, not recognizing read name formatting: [LPMLF:07992:00549]

If your data come from SRA, be sure to dump the fastq file like so:

	SRA_TOOLKIT/fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files file.sra 

Error, cmd: seqtk-trinity seq -A /local/BACK_UP_3/todos_um.fastq >> single.fa died with ret 512 at /home/me/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl line 758.
Error, cmd: /home/me/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl --seqType fq --JM 120G  --max_cov 50 --CPU 12 --output /home/me/trimed-test/todos_um_trimed_trinity_out/insilico_read_normalization   --max_pct_stdev 10000  --single /local/BACK_UP_3/todos_um.fastq died with ret 512 at /home/me/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.

```

**Comment by brianjohnhaas** [comment]
To get your reads to work with Trinity, it needs to know if it's  the left
/1 or right /2 fragment, and usually (at least with Illumina) there is a
way to figure it out based on the read name definition line in the fastq
file.

In your case, assuming the read name line just has the read name on it like
so '@readname', we can just tack on a /1 to the end like so:

 cat reads.fq | perl -lane '$x++; if ($x % 4 == 1) { print "$_/1";} else {
print;}'  >  reads.adj.fq

and then use those with Trinity.

best of luck,

~b


On Tue, Sep 26, 2017 at 8:55 AM, Patrick Douglas <notifications@github.com>
wrote:
>
> Since trinity 2.4 version there is an error while I try assembly Ion
Torrent single and fastq files, see log below.
>
> ~/trinityrnaseq-Trinity-v2.4.0/Trinity --seqType fq --single
/local/BACK_UP_3/todos_um.fastq --max_memory 120G --CPU 12 -grid_node_CPU
12 --grid_node_max_memory 30G --grid_exec
"/home/me/HpcGridRunner/hpc_cmds_GridRunner.pl --grid_conf
/home/me/HpcGridRunner/PBS.trinity.conf --parafly -c" --output
/home/me/trimed-test/todos_um_trimed_trinity_out --no_bowtieSingle read
files: $VAR1 = [
>           '/local/BACK_UP_3/todos_um.fastq'
>         ];
> Trinity version: Trinity-v2.4.0
> -currently using the latest production release of Trinity.
>
> Tuesday, September 26, 2017: 09:51:54 CMD: java -Xmx64m
-XX:ParallelGCThreads=2 -jar
/home/me/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ExitTester.jar 0
> Tuesday, September 26, 2017: 09:51:54 CMD: java -Xmx64m
-XX:ParallelGCThreads=2 -jar
/home/me/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ExitTester.jar 1
> Tuesday, September 26, 2017: 09:51:55 CMD: mkdir -p
/home/me/trimed-test/todos_um_trimed_trinity_out
> Tuesday, September 26, 2017: 09:51:55 CMD: mkdir -p
/home/me/trimed-test/todos_um_trimed_trinity_out/chrysalis
>
>
>
----------------------------------------------------------------------------------
> -------------- Trinity Phase 1: Clustering of RNA-Seq Reads
 ---------------------
>
----------------------------------------------------------------------------------
>
> ---------------------------------------------------------------
> ------------ In silico Read Normalization ---------------------
> -- (Removing Excess Reads Beyond 50 Coverage --
> ---------------------------------------------------------------
>
> # running normalization on reads: $VAR1 = [
>           [
>             '/local/BACK_UP_3/todos_um.fastq'
>           ]
>         ];
>
>
> Tuesday, September 26, 2017: 09:51:55 CMD:
/home/me/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl
--seqType fq --JM 120G  --max_cov 50 --CPU 12 --output
/home/me/trimed-test/todos_um_trimed_trinity_out/insilico_read_normalization
  --max_pct_stdev 10000  --single /local/BACK_UP_3/todos_um.fastq
> CMD: seqtk-trinity seq -A /local/BACK_UP_3/todos_um.fastq >> single.fa
> Error, not recognizing read name formatting: [LPMLF:07992:00549]
>
> If your data come from SRA, be sure to dump the fastq file like so:
>
> SRA_TOOLKIT/fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files
file.sra
>
> Error, cmd: seqtk-trinity seq -A /local/BACK_UP_3/todos_um.fastq >>
single.fa died with ret 512 at /home/me/trinityrnaseq-Trinity-v2.4.0/util/
insilico_read_normalization.pl line 758.
> Error, cmd: /home/me/trinityrnaseq-Trinity-v2.4.0/util/
insilico_read_normalization.pl --seqType fq --JM 120G  --max_cov 50 --CPU
12 --output
/home/me/trimed-test/todos_um_trimed_trinity_out/insilico_read_normalization
  --max_pct_stdev 10000  --single /local/BACK_UP_3/todos_um.fastq died with
ret 512 at /home/me/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
