### ISSUE TITLE
Jaccard clip option and single end ?

### ISSUE THREAD

**Issue by ptranvan** [trinityrnaseq/trinityrnaseq#339]
Hi,

I have an insect genome that I expect to have high gene density. 
I have used the option `--jaccard_clip` before. 

Now with my study, I have to assemble a transcriptome but I have only single reads.
The manual give a me a doubt:

> --jaccard_clip                  :option, set if you have paired reads and
>                                    you expect high gene density with UTR
>                                  overlap (use FASTQ input file format
>                                    for reads).
>                                    (note: jaccard_clip is an expensive
>                                    operation, so avoid using it unless
>                                    necessary due to finding excessive fusion
>                                    transcripts w/o it.)

Can I still use this option with single reads or no ?

**Comment by brianjohnhaas** [comment]
Hi

Sorry, the jaccard clip only works with read pairings.  

-Brian
(by iPhone)
