### ISSUE TITLE
[Suggestion] Better align_estimate_abundance with trimmomatic trimmed reads

### ISSUE THREAD

**Issue by kk86bioinfo** [trinityrnaseq/trinityrnaseq#34]
Hi,

    We have experimenting align_estimate_abundance.pl in trinity with both raw reads and trimmomatic generated PwU.trim.fq. 
    We notice an increment of about 10% mappable reads in trimmomatic trimmed fastq. Perhaps in trinity pipeline should allow a parameter to use the trimmed reads or mention in documentation?

**Comment by brianjohnhaas** [comment]
We'll need to investigate the trimmomatic & normalization compatibiities (again) and how we can better leverage qual-trimmed reads in downstream processes.

**Comment by brianjohnhaas** [comment]
With the quality trimming enabled, the quality trimmed files are left for users to leverage.  I'll add a note in the documentation that users might consider using the quality trimmed files instead of the raw files for the abundance estimation procedure.
