### ISSUE TITLE
How to get the Transcript Quantification results?

### ISSUE THREAD

**Issue by wangzhennan14** [trinityrnaseq/trinityrnaseq#340]
Hi brain,
     After I ran trinity to get the transcript, I wanted to obtain the transcript quantification. So I ran the command as follows:
     /home/lill/wangzhn/software/trinityrnaseq/util/align_and_estimate_abundance.pl --transcripts /home/lill/wangzhn/meelab/meelab-RNA-Seq-data-trinity-strand-noref.fa --seqType fq --thread_count 24 --SS_lib_type RF --left /home/lill/wangzhn/meelab/left/150204-MmR1FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD14Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD28Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD29Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD35Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150204-MmR1FD7Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1CD28Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1CD7Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1FD0S_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1FD0X_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1FD28M_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1FD28S_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR1FD28X_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2CD28Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2CD7Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD14Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD28Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD29Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD35Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150708-MmR2FD7Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150819-MmR1FD35X_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/150819-MmR1FD49X_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR1FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR1FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR2FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD35Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD42Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD63Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD64Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR3FD71Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD35Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD42Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD64Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160318-MmR4FD71Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR2FD0Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR3FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR3FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR3FD56Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR3FD64Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR4FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR4FD35Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR4FD56Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160415-MmR4FD63Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160629-MmR1FD21Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160629-MmR3FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160629-MmR4FD49Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160629-MmR4FD56Z_QC_1.fastq.gz,/home/lill/wangzhn/meelab/left/160629-MmR4FD71Z_QC_1.fastq.gz --right /home/lill/wangzhn/meelab/right/150204-MmR1FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD14Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD28Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD29Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD35Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150204-MmR1FD7Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1CD28Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1CD7Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1FD0S_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1FD0X_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1FD28M_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1FD28S_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR1FD28X_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2CD28Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2CD7Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD14Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD28Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD29Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD35Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150708-MmR2FD7Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150819-MmR1FD35X_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/150819-MmR1FD49X_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR1FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR1FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR2FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD35Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD42Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD63Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD64Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR3FD71Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD35Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD42Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD64Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160318-MmR4FD71Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR2FD0Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR3FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR3FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR3FD56Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR3FD64Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR4FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR4FD35Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR4FD56Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160415-MmR4FD63Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160629-MmR1FD21Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160629-MmR3FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160629-MmR4FD49Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160629-MmR4FD56Z_QC_2.fastq.gz,/home/lill/wangzhn/meelab/right/160629-MmR4FD71Z_QC_2.fastq.gz --est_method RSEM --aln_method bowtie --trinity_mode --prep_reference --output_dir /home/lill/wangzhn/meelab/output
     And there are some errors and I don't know. I just got the results like this:
     
![default](https://user-images.githubusercontent.com/17285718/31133479-3813e104-a892-11e7-8b86-a8436ff7a39a.PNG)
     In the RSEM.temp dir, 9 files were there:
     
![default](https://user-images.githubusercontent.com/17285718/31133557-7899a556-a892-11e7-91ba-f459599c766f.PNG)
     How can I get the file RSEM.isoforms.results ?   Please help me to solve this. Thank you very much!

Wang

**Comment by brianjohnhaas** [comment]
Hi

If RSEM is giving you trouble then it's easier to just try running kallisto or salmon

-Brian
(by iPhone)
