### ISSUE TITLE
analyze_diff_expr error 

### ISSUE THREAD

**Issue by asis2** [trinityrnaseq/trinityrnaseq#346]
Hi there,
I keep getting the following error when I try to run the analyze_diff_expr script...

Error, no differentially expressed transcripts identified at cuttoffs: P:0.001, C:2 at /usr/local/src/Trinity/trinityrnaseq-Trinity-v2.4.0/Analysis/DifferentialExpression/analyze_diff_expr.pl line 203.

When I look at my DE.results file I think I can see that there are transcripts which should be meeting the criteria.
I have tried this with edgeR and DESeq2 results. With DESeq2 I can get some results based on my isoform matrix (only 72) but not with the gene matrix, neither work with edgeR, although I think that the results files of all of these suggest thats there should be some. Could you advise me on what could be going wrong - I am afraid I am a bioinformatics Newb.

This is the command I have been using.
/usr/local/src/Trinity/trinityrnaseq-Trinity-v2.4.0/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix ../gTrans.TMM.EXPR.matrix --samples ../RSEM_table_DESeq.txt

I attach one of the failed DE_results files (with .txt added to make it possible to attach with my browser)
[gTrans_counts.matrix.Dom_vs_Rec.DESeq2.DE_results.txt](https://github.com/trinityrnaseq/trinityrnaseq/files/1379786/gTrans_counts.matrix.Dom_vs_Rec.DESeq2.DE_results.txt)

Many thanks!
Asis

**Comment by brianjohnhaas** [comment]
The padj column is what is used to ascertain statistical significance after accounting for multiple hypothesis testing, and based on that value, the results were not found to be significant.
