### ISSUE TITLE
color-space support?

### ISSUE THREAD

**Issue by biocyberman** [trinityrnaseq/trinityrnaseq#35]
I aligned libraries with third-party aligners and use the BAM files with genome-based workflow of Trinity. This works if I am satisfied with the alignment step. Unfortunately, the reference genome I have is of low quality. So, is there any hope I can get Trinity to work with color-space FASTQ files?

**Comment by brianjohnhaas** [comment]
Hi,

sorry - we only support Illumina fastq for Trinity assembly.

On Tue, Jun 9, 2015 at 3:50 PM, biocyberman <notifications@github.com>
wrote:

> I aligned libraries with third-party aligners and use the BAM files with
> genome-based workflow of Trinity. This works if I am satisfied with the
> alignment step. Unfortunately, the reference genome I have is of low
> quality. So, is there any hope I can get Trinity to work with color-space
> FASTQ files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/35>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by biocyberman** [comment]
Thank you for the confirmation.
