### ISSUE TITLE
Inchworm CPU utilization bug

### ISSUE THREAD

**Issue by dbrowneup** [trinityrnaseq/trinityrnaseq#37]
Something I noticed - Inchworm uses 6 CPUs regardless of the --CPU option. However, when you specify the --inchworm_cpu option, you can change how many CPUs Inchworm uses. But based on the documentation, it seems like Inchworm should use the same number of CPUs specified by the --CPU option.

**Comment by benfulton** [comment]
Retest before changing. Older tests show that 6 is the optimum number to use.

**Comment by benfulton** [comment]
Assemble time in minutes
|CPUs|1|2|4|8|16|
|--|-|-|-|-|-|
|GNU Compiler|85|83|64|57|71|
|Intel Compiler	|191|	95|65|53|66|

**Comment by brianjohnhaas** [comment]
I guess we'll just keep it at 6.
