### ISSUE TITLE
Error with bowtie 2

### ISSUE THREAD

**Issue by achalneupane** [trinityrnaseq/trinityrnaseq#371]
Hi I am running Trinity invoking the following command : 
`Trinity --seqType fq --max_memory 100G --right /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897_1.fastq --left /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897_2.fastq --CPU 16 --output /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output`

This however generates the following error posted below. Could someone please help me resolve this problem. Thanks!

Error: 

```
put/chrysalis/inchworm.K25.L25.DS.fa.min100 /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output/chrysalis/inchworm.K25.L25.DS.fa.min100 1>/dev/null
bowtie2-build: unrecognized option '--threads'
Bowtie 2 version 2.2.4 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)
Usage: bowtie2-build [options]* <reference_in> <bt2_index_base>
    reference_in            comma-separated list of files with ref sequences
    bt2_index_base          write bt2 data to files with this dir/basename
*** Bowtie 2 indexes work only with v2 (not v1).  Likewise for v1 indexes. ***
Options:
    -f                      reference files are Fasta (default)
    -c                      reference sequences given on cmd line (as
                            <reference_in>)
    --large-index           force generated index to be 'large', even if ref
                            has fewer than 4 billion nucleotides
    -a/--noauto             disable automatic -p/--bmax/--dcv memory-fitting
    -p/--packed             use packed strings internally; slower, less memory
    --bmax <int>            max bucket sz for blockwise suffix-array builder
    --bmaxdivn <int>        max bucket sz as divisor of ref len (default: 4)
    --dcv <int>             diff-cover period for blockwise (default: 1024)
    --nodc                  disable diff-cover (algorithm becomes quadratic)
    -r/--noref              don't build .3/.4 index files
    -3/--justref            just build .3/.4 index files
    -o/--offrate <int>      SA is sampled every 2^<int> BWT chars (default: 5)
    -t/--ftabchars <int>    # of chars consumed in initial lookup (default: 10)
    --seed <int>            seed for random number generator
    -q/--quiet              verbose output (for debugging)
    -h/--help               print detailed description of tool and its options
    --usage                 print this usage message
    --version               print version information and quit
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --threads 16 -o 3 /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output/chrysalis/inchworm.K25.L25.DS.fa.min100 /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output/chrysalis/inchworm.K25.L25.DS.fa.min100 
Error, cmd: bowtie2-build --threads 16 -o 3 /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output/chrysalis/inchworm.K25.L25.DS.fa.min100 /media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal-mycovirus/achal_sra/SRR915897/SRR915897-trinity-output/chrysalis/inchworm.K25.L25.DS.fa.min100 1>/dev/null 2>tmp.138488.stderr died with ret 256 at /home/owner/Desktop/Achal/executables/trinityrnaseq-Trinity-v2.5.1/PerlLib/Pipeliner.pm line 166.
	Pipeliner::run('Pipeliner=HASH(0x229eee8)') called at /home/owner/Desktop/Achal/executables/trinityrnaseq-Trinity-v2.5.1//Trinity line 1827
	main::run_chrysalis('/media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal...', '/media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal...', 200, 500, undef, '/media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal...', '/media/owner/b54f3251-5380-4288-9ddf-fa3357ea8294/mycorrhizal...') called at /home/owner/Desktop/Achal/executables/trinityrnaseq-Trinity-v2.5.1//Trinity line 1667
	main::run_Trinity() called at /home/owner/Desktop/Achal/executables/trinityrnaseq-Trinity-v2.5.1//Trinity line 1320
	eval {...} called at /home/owner/Desktop/Achal/executables/trinityrnaseq-Trinity-v2.5.1//Trinity line 1319

Trinity run failed. Must investigate error above.
```

```

**Comment by achalneupane** [comment]
Additionally, it is generating the same error for `make test_Trinity_Assembly` provided in the Trinity package itself.

**Comment by achalneupane** [comment]
Ok. I finally figured out the problem for this: Trinity works well with Java version 7. So before running Trinity, we need to make sure we set java version 7 like this:

To get a list of your installed Java platforms, run the following command from the terminal:

sudo update-alternatives --config java

This will give you a list output similar to this:

There are 2 choices for the alternative java (providing /usr/bin/java).
   Selection    Path                                           Priority   Status
  ------------------------------------------------------------
  0            /usr/lib/jvm/java-6-oracle/jre/bin/java         1070      auto mode
  1            /usr/lib/jvm/java-7-openjdk-i386/jre/bin/java   1051      manual mode
* 2            /usr/lib/jvm/java-6-openjdk-i386/jre/bin/java   1069      manual mode
Press enter to keep the current choice[*], or type selection number:
Here select the number that represent java-7, so chose 1.

Now, Trinity should be running properly. Check by invoking this command: make test_trinity

###################################################################
Butterfly assemblies are written to /home/owner/Desktop/executables/trinityrnaseq-2.0.6/sample_data/test_Trinity_Assembly/trinity_out_dir/Trinity.fasta
###################################################################



##### Done Running Trinity #####

**Comment by magadancito** [comment]
Hi I have the same problem, I fix it delete the option --thread for bowtie2 in the Trinity scrip and it work.

Pardon me for my bad English is not may native language

**Comment by C-Pauli** [comment]
The delete --thread hack seems to work, but it's on line 1909 and 1920 of Trinity v2.8.4. 

I hope this saves someone from going through the script to find where it calls bowtie....

**Comment by phil-grayson** [comment]
I just had the same problem with v2.8.5.  The line is:
`$cmd = "$bowtie2_build_path --threads $CPU -o 3 $iworm_min100_fa_file $iworm_min100_fa_file 1>/dev/null"; #-o 3 / defaut is 5, less use more ram but is faster when mapping the reads
`
...and it's at 1950 in the Trinity code.
