### ISSUE TITLE
Trinity v2.4.0 error ret 512 at ./Trinity line 2462

### ISSUE THREAD

**Issue by luca-peruz** [trinityrnaseq/trinityrnaseq#380]
Hello Trinity community.
I was trying to assemble a transcriptome with a great amount of sequences but my run stops with this error:

```
CMD: /home/local/software/trinity/trinityrnaseq-Trinity-v2.4.0/util/..//trinity-plugins/jellyfish/bin/jellyfish count -t 112 -m 25 -s 51073424622  both.fa
terminate called after throwing an instance of 'jellyfish::large_hash::array_base<jellyfish::mer_dna_ns::mer_base_static<unsigned long, 0>, unsigned long, atomic::gcc, jellyfish::large_hash::array<jellyfish::mer_dna_ns::mer_base_static<unsigned long, 0>, unsigned long, atomic::gcc, allocators::mmap> >::ErrorAllocation'
  what():  Failed to allocate 189701291520 bytes of memory
Error, cmd: /home/local/software/trinity/trinityrnaseq-Trinity-v2.4.0/util/..//trinity-plugins/jellyfish/bin/jellyfish count -t 112 -m 25 -s 51073424622  both.fa died with ret 6 at /home/local/software/trinity/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl line 758.
Error, cmd: /home/local/software/trinity/trinityrnaseq-Trinity-v2.4.0/util/insilico_read_normalization.pl --seqType fq --JM 400G  --max_cov 50 --CPU 112 --output /scratch/lp6c17/assembly_1/trinity_out_dir/insilico_read_normalization   --max_pct_stdev 10000  --SS_lib_type FR  --left /scratch/lp6c17/assembly_1/trimmed.ALL.P1.left.fastq.gz --right /scratch/lp6c17/assembly_1/trimmed.ALL.P2.right.fastq.gz --pairs_together --PARALLEL_STATS   died with ret 512 at /local/software/trinity/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.

```

The command I used was:
`Trinity --seqType fq --max_memory 400G --bflyCalculateCPU --left trimmed.ALL.P1.left.fastq.gz --right trimmed.ALL.P2.right.fastq.gz --CPU 112 --SS_lib_type FR
`
I saw a post with a similar problem (https://github.com/trinityrnaseq/trinityrnaseq/issues/341) but in my case the sequences were not downloaded from SRA. The first lines of my fastq files are:

trimmed.ALL.P2.right.fastq.gz :
@E00502:107:ZA20170508213:5:1101:6614:1872 2:N:0:ACTTGA
GGCGGCACATCTGTAAACCATAACGCAGGTGTCCTAAGGGGGACTCATGGAGAACAGAAATCTCCAGTAGAGCAAAAGGGCAAAAGTCCCCTTGATTTTGATTT
+
AAAA7A<FFJJJJJJJF<<FF7F-AJJJJFFJ-FJJJFJJFJJFJJJJJF-<AJJJJJAJJ7-AAJJAJJFJFJJFFJJFA7<FAJJ77--AAFA-AF7F7FF7
@E00502:107:ZA20170508213:5:1101:8481:1872 2:N:0:ACTTGA
TCGTGATTTTCTTCATTTTCTCCCTGTCTATTCCTTCCTTGGATTTCTCTTCCTCCCCCTTTCCCTCTCTTTCTTTCCCCTTTTTCT
+
AAAA-FFFFFFFJJJJJJJ<FJJJFAF-FFJJ7JFF<JJJJJFFJJ<FFF-AFF7AF<-AAJ<AFFFJJJJJFFF<<AFFJ<FJJA<

trimmed.ALL.P1.left.fastq.gz :
@E00502:107:ZA20170508213:5:1101:6614:1872 1:N:0:ACTTGA
CCTTGTGGTAACTTTTCTGGCACCTCTAGCCTCAAATTTCGAGGGACTAAAGGATCGATAGGCCACACTTTCATGGTTTGTATTCACACTGAAAATCAAAATCAAGGGG
+
AAAAFJJJJJFAFFJJFAJ77AFFFFJFJJFF7A7FFJJFJFJJJFFJJ<JJJFJJJ<JJJFFAJ<JAFJJJ7FF-AFFJJJJJ-AJAJ7-FAAFJJFJ--FAF-FAFA
@E00502:107:ZA20170508213:5:1101:8481:1872 1:N:0:ACTTGA
GNGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGGG
+
A#AAAFJJJJFJJFFJJJJJ7FF7FFJAAAF-AFAFJFJ<JAFFFJFJJ7FFF-FAAAFAJ7FFFAJ-A-F<JFJ<A<F<F<F7FAJ-F-<-A7777-7

Does anyone have any idea what could be causing this issue?

Thanks!

Luca

**Comment by manuelsmendoza** [comment]
I think that it may be a memory error...

**Comment by brianjohnhaas** [comment]
yes, out of memory error.  Sorry for missing this ticket!
