### ISSUE TITLE
Variant calling

### ISSUE THREAD

**Issue by jiffen** [trinityrnaseq/trinityrnaseq#387]
Hi Brian,

I am doing the variant calling and it gave me following error. How to fix it?

RuntimeError: Error while running command "['STAR', '--runThreadN', '4', '--runMode', 'genomeGenerate', '--genomeDir', 'star_genome_idx', '--genomeFastaFiles', '/Volumes/scratch/macknightlab/jiffin/CUDH2107/trinity_300/super_transcripts/trinity_genes.fasta', '--sjdbGTFfile', '/Volumes/scratch/macknightlab/jiffin/CUDH2107/trinity_300/super_transcripts/trinity_genes.gtf', '--sjdbOverhang', '150', '--limitGenomeGenerateRAM', '50000000000']":

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=50000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 148009325269 and make that much RAM available

Jan 16 11:30:21 ...... FATAL ERROR, exiting
Thanks
Jiffin

**Comment by brianjohnhaas** [comment]
Hi Jiffin,

sorry for the delayed response...  I must have missed this thread.    In the current version, you'll need to edit the run_variant_calling.py script to include

 --limitGenomeGenerateRAM  148009325269

under 'star_genome_generate_cmd'

The next release (soon) will have a command-line parameter that will allow you to easily adjust this.

**Comment by brianjohnhaas** [comment]
--STAR_genomeGenerate_opts STAR_GENOMEGENERATE_OPTS  added to run_variant_calling.py
