### ISSUE TITLE
Normalization with gzipped FastQ files fails in release 20140717

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#4]
Issue involving --trimmomatic. A fix is available with a replacement insilico_read_normalization.pl script

**Comment by brianjohnhaas** [comment]
this works ok now, right?

**Comment by benfulton** [comment]
I don't remember if the replacement script got checked in. I'll check it.

**Comment by benfulton** [comment]
The sample_data_trimmed_and_normalized test checks this.
