### ISSUE TITLE
Trouble at GG_write_trinity_cmds.pl step

### ISSUE THREAD

**Issue by criles25** [trinityrnaseq/trinityrnaseq#45]
Hello Brian,

I run Trinity with the following command:

./Trinity --seqType fq --max_memory 3G --single ../../Desktop/Ath_PAT.fastq,../../Desktop/srr1105823.fastq --CPU 3 --verbose

Inchworm completes successfully, and then Chrysalsis runs. I get the following error when I reach the step that calls the GG_write_trinity_cmds.pl script:

CMD: /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl --reads_list_file partitioned_reads.files.list --CPU 1 --max_memory 1G  --full_cleanup --seqType fa --trinity_complete --verbose  > recursive_trinity.cmds

####################################################################################
#
#  usage: /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl --reads_list_file <string> [Trinity params]
#
# Required:
#
# --reads_list_file <string>      file containing list of filenames corresponding 
#                                  to the reads.fasta
#
#
#####################################################################################

Error, cmd: /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl --reads_list_file partitioned_reads.files.list --CPU 1 --max_memory 1G  --full_cleanup --seqType fa --trinity_complete --verbose  > recursive_trinity.cmds died with ret 65280 at ./Trinity line 2116.

I checked the partitioned_reads.files.list and noticed it was empty. Do you have any ideas? 

Thank you for your help.

P.S. I ran Trinity with the test data in the sample folder and it was able to produce contigs/no errors. Also, I am using 2.0.6 version.

**Comment by brianjohnhaas** [comment]
Hi Charles,

Is this a very small input data set?  This error could happen if there are
no clusters of contigs that are large enough to produce an assembled contig
at least 200 bases in length.

~b

On Sun, Aug 2, 2015 at 9:33 PM, Charles Riley <notifications@github.com>
wrote:

> Hello Brian,
>
> I run Trinity with the following command:
>
> ./Trinity --seqType fq --max_memory 3G --single
> ../../Desktop/Ath_PAT.fastq,../../Desktop/srr1105823.fastq --CPU 3 --verbose
>
> Inchworm completes successfully, and then Chrysalsis runs. I get the
> following error when I reach the step that calls the
> GG_write_trinity_cmds.pl script:
>
> CMD:
> /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl
> --reads_list_file partitioned_reads.files.list --CPU 1 --max_memory 1G
> --full_cleanup --seqType fa --trinity_complete --verbose >
> recursive_trinity.cmds
>
>
> ####################################################################################
> #
> usage:
> /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl
> --reads_list_file [Trinity params]
>
> #
> Required:
>
> #
> --reads_list_file file containing list of filenames corresponding to the
> reads.fasta
>
> #
> #
>
> #####################################################################################
>
> Error, cmd:
> /home/charles/Downloads/trinityrnaseq-2.0.5/util/support_scripts/GG_write_trinity_cmds.pl
> --reads_list_file partitioned_reads.files.list --CPU 1 --max_memory 1G
> --full_cleanup --seqType fa --trinity_complete --verbose >
> recursive_trinity.cmds died with ret 65280 at ./Trinity line 2116.
>
> I checked the partitioned_reads.files.list and noticed it was empty. Do
> you have any ideas?
>
> Thank you for your help.
>
> P.S. I ran Trinity with the test data in the sample folder and it was able
> to produce contigs/no errors. Also, I am using 2.0.6 version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/45>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
We can continue to pursue this on the mailing list.

thanks!
