### ISSUE TITLE
Compilation failure with gcc 5

### ISSUE THREAD

**Issue by osallou** [trinityrnaseq/trinityrnaseq#47]
Hi,
it seems that Inchworm fails to compile gcc5.
I compiled on my Ubuntu with gcc 4.x and it was fine. When I tried to compile on latest Debian, which uses gcc 5.x, it fails. 

      sequenceUtil.cpp: In function ‘std::__cxx11::string read_sequence_from_file(std::__cxx11::string)’:
      sequenceUtil.cpp:55:18: error: no match for ‘operator==’ (operand types are ‘std::ifstream {aka std::basic_ifstream<char>}’ and ‘int’)

Here is compilation extract:

    make[1]: Entering directory '/home/vagrant/trinityrnaseq-2.0.6'
    cd Inchworm && make
    make[2]: Entering directory '/home/vagrant/trinityrnaseq-2.0.6/Inchworm'
     cd . && /bin/bash /home/vagrant/trinityrnaseq-2.0.6/Inchworm/missing --run automake-1.11 --foreign
    /home/vagrant/trinityrnaseq-2.0.6/Inchworm/missing: ligne 52: automake-1.11 : commande introuvable
    WARNING: `automake-1.11' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
     cd . && /bin/bash ./config.status Makefile 
    config.status: creating Makefile
    make  all-recursive
    make[3]: Entering directory '/home/vagrant/trinityrnaseq-2.0.6/Inchworm'
    Making all in src
    make[4]: Entering directory '/home/vagrant/trinityrnaseq-2.0.6/Inchworm/src'
     cd .. && /bin/bash ./config.status src/Makefile depfiles
    config.status: creating src/Makefile
    config.status: executing depfiles commands
    g++ -DHAVE_CONFIG_H -I. -I..   -D_FORTIFY_SOURCE=2 -std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -MT Fasta_entry.o -MD -MP -MF .deps/Fasta_entry.Tpo -c -o Fasta_entry.o Fasta_entry.cpp
    mv -f .deps/Fasta_entry.Tpo .deps/Fasta_entry.Po
    g++ -DHAVE_CONFIG_H -I. -I..   -D_FORTIFY_SOURCE=2 -std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -MT IRKE_run.o -MD -MP -MF .deps/IRKE_run.Tpo -c -o IRKE_run.o IRKE_run.cpp
    mv -f .deps/IRKE_run.Tpo .deps/IRKE_run.Po
    g++ -DHAVE_CONFIG_H -I. -I..   -D_FORTIFY_SOURCE=2 -std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -MT sequenceUtil.o -MD -MP -MF .deps/sequenceUtil.Tpo -c -o sequenceUtil.o sequenceUtil.cpp
    sequenceUtil.cpp: In function ‘bool contains_non_gatc(std::__cxx11::string)’:
    sequenceUtil.cpp:35:20: warning: array subscript has type ‘char’ [-Wchar-subscripts]
      if (_base_to_int[c] > 3)
                    ^
    sequenceUtil.cpp: In function ‘std::__cxx11::string read_sequence_from_file(std::__cxx11::string)’:
    sequenceUtil.cpp:55:18: error: no match for ‘operator==’ (operand types are ‘std::ifstream {aka std::basic_ifstream<char>}’ and ‘int’)
       if (fileReader == 0) { // couldn't open file
   ....

**Comment by osallou** [comment]
By the way Chrysalis also fails (differently with gcc5, ok with gcc4)

    g++  -W -Wall -Wno-unused -Wno-deprecated -ansi -pedantic -Wno-long-long -fno-nonansi-builtins -Wctor-dtor-privacy -Wsign-promo -Woverloaded-virtual -Wendif-labels  -O3  -ggdb3 -DMAKE_DATE='"jeudi 20 août 2015, 07:55:02 (UTC+0000)"' -DMAKE_OS_RELEASE='"4.1.0-2-amd64"' -DMAKE_RELEASE='"3.0"' -DNEW_MAKEFILE -imacros system/BigFileDefines.h -pthread  -ftemplate-depth-30 -fno-strict-aliasing -mieee-fp   -fopenmp       -c ./aligns/KmerAlignCore.cc -o obj/aligns/KmerAlignCore.o
    ./aligns/KmerAlignCore.cc:6:34: fatal error: aligns/KmerAlignCore.h: Aucun fichier ou dossier de ce type (no such file or directory) => I confirm it is present
    compilation terminated.

**Comment by osallou** [comment]
Please find patch to fix the issues with GCC5


    Date: Thu, 20 Aug 2015 10:07:43 +0000
    Subject: fix_gcc5.patch
    
    Add code for GCC 5 Compilation
    ---
     Chrysalis/Makefile | 4 ++++
     1 file changed, 4 insertions(+)
    
    diff --git a/Chrysalis/Makefile b/Chrysalis/Makefile
    index 448b2d1..11eae21 100644
    --- a/Chrysalis/Makefile
    +++ b/Chrysalis/Makefile
    @@ -302,6 +302,10 @@ ifeq ($(COMPILER),g++)
       ifeq ($(GPP_MAJOR_VERSION),4)
            SYS_INCS	= -iquote . $(XERCES_INC)
       endif
    +  ifeq ($(GPP_MAJOR_VERSION),5)
    +       SYS_INCS = -iquote . $(XERCES_INC)
    +  endif
    +
     endif
     
    Date: Thu, 20 Aug 2015 13:05:48 +0000
    Subject: fix_istream_failure_call
    
    Upstream is using wrong test gor file open failure, comparing an int instead
    of calling fail() method
    ---
     Inchworm/src/sequenceUtil.cpp | 3 ++-
     1 file changed, 2 insertions(+), 1 deletion(-)
    
    diff --git a/Inchworm/src/sequenceUtil.cpp b/Inchworm/src/sequenceUtil.cpp
    index 7ba9c1f..a24c250 100644
    --- a/Inchworm/src/sequenceUtil.cpp
    +++ b/Inchworm/src/sequenceUtil.cpp
    @@ -52,7 +52,8 @@ bool contains_non_gatc (string kmer) {
     string read_sequence_from_file (string filename) {
       
       ifstream fileReader (filename.c_str());
    -  if (fileReader == 0) { // couldn't open file
    +  //if (fileReader == 0) { // couldn't open file
    +  if (fileReader.fail()) { // couldn't open file
     	throw

**Comment by brianjohnhaas** [comment]
Thanks!  We'll include this in the next release.

**Comment by hamidashrafi** [comment]
I am also getting the following error: Is there any immediate solution to it? I am not the root user. 

make[1]: Entering directory `/home/ashrafi/bin/trinityrnaseq-2.0.6/Inchworm'
Making install in src
make[2]: Entering directory `/home/ashrafi/bin/trinityrnaseq-2.0.6/Inchworm/src'
g++ -DHAVE_CONFIG_H -I. -I..    -std=c++0x -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2 -MT Fasta_entry.o -MD -MP -MF .deps/Fasta_entry.Tpo -c -o Fasta_entry.o Fasta_entry.cpp
cc1plus: error: unrecognized command line option "-std=c++0x"
make[2]: *** [Fasta_entry.o] Error 1
make[2]: Leaving directory `/home/ashrafi/bin/trinityrnaseq-2.0.6/Inchworm/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/ashrafi/bin/trinityrnaseq-2.0.6/Inchworm'
make: *** [inchworm_target] Error 2

**Comment by benfulton** [comment]
hamidashrafi, "std=c++0x" has been supported since g++ 4.3. If you're using an older compiler than that you will have to ask your sysadmin to upgrade. If you are using that compiler or later, what kind of system are you using?

**Comment by hamidashrafi** [comment]
Thanks, I guess we are ending up doing this but it is a lot of hassle to upgrade the whole system just for one program. 

Hamid
