### ISSUE TITLE
align_and_estimate_abundance.pl error

### ISSUE THREAD

**Issue by Worarado** [trinityrnaseq/trinityrnaseq#471]
Dear Dr. Brian,

I try to mapping my paired read with reference genome using align_and_estimate_abundance.pl in trinity program. TRANSCRIPT is the **V_corymbosum_scaffold_May_2013.fasta**
However, the result showed Mapping info is not correct, cannot find scaffold and cannot build gene_trans_map. 

Please give me suggestion.

Best regards,
KAN

**Comment by brianjohnhaas** [comment]
Hi,

If the file V_corymbosum_scaffold_May_2013.fasta  is a Trinity assembly, it
should work unless you changed the identifiers somehow.

For any transcriptome assembly (regardless of whether Trinity was used or
not), you can use CORSET to generate a gene-to-transcript mapping:

https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0410-6

best,

~brian

On Wed, May 16, 2018 at 4:04 AM, Worarado <notifications@github.com> wrote:
>
> Dear Dr. Brian,
>
> I try to mapping my paired read with reference genome using
align_and_estimate_abundance.pl in trinity program. TRANSCRIPT is the
V_corymbosum_scaffold_May_2013.fasta
> However, the result showed Mapping info is not correct, cannot find
scaffold and cannot build gene_trans_map.
>
> Please give me suggestion.
>
> Best regards,
> KAN
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by Worarado** [comment]
Than you for your suggestion.
