### ISSUE TITLE
Trinotate Genomic Coordinates of Transcripts Calculation

### ISSUE THREAD

**Issue by DarioS** [trinityrnaseq/trinityrnaseq#484]
Now that Trinity has genome-guided assembly built-in, could Trinotate offer to estimate the genomic coordinates of them? This could assist in determining which transcripts are in intergenic regions of the genome, short-listing novel genes not yet in databases like GENCODE. This could produce interesting results, even for human samples utilising hg38.

**Comment by brianjohnhaas** [comment]
Trinity v3 will do this eventually.  For now, try using PASA w/ trinity transcripts:
https://github.com/PASApipeline/PASApipeline/wiki
