### ISSUE TITLE
Trinity Error, cmd: /path/to/miniconda2/bin/bowtie2-build...

### ISSUE THREAD

**Issue by mariamoteiro** [trinityrnaseq/trinityrnaseq#503]
Hi everyone,

I am running trinity with the following command:

Trinity --seqType fq --max_memory 50G --left /home/mariamoteiro/Resultados_Trim_16_102/0_mM_KNO3_plus_1.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/200_mM_KNO3_plus_1.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/400_mM_KNO3_plus_1.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/600_mM_KNO3_plus_1.trimP.fastq.gz --right /home/mariamoteiro/Resultados_Trim_16_102/0_mM_KNO3_plus_2.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/200_mM_KNO3_plus_2.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/400_mM_KNO3_plus_2.trimP.fastq.gz,/home/mariamoteiro/Resultados_Trim_16_102/600_mM_KNO3_plus_2.trimP.fastq.gz --SS_lib_type RF --CPU 12 --ouput /home/mariamoteiro/outTrinity

Im not sure what error is this (bellow).

Can you help me? I am very new to using Trinity.

Thanks in advance, 

Maria Móteiro

-- (building a k-mer catalog from reads) --
-------------------------------------------

Running CMD: jellyfish count -t 10 -m 25 -s 100000000  /home/mariamoteiro/outTrinity/both.fa
Running CMD: jellyfish dump -L 1 mer_counts.jf > jellyfish.kmers.fa
Running CMD: jellyfish histo -t 10 -o jellyfish.kmers.fa.histo mer_counts.jf
----------------------------------------------
--------------- Inchworm ---------------------
-- (Linear contig construction from k-mers) --
----------------------------------------------
 Running CMD: /home/mariamoteiro/miniconda2/opt/trinity-2.6.6/Inchworm/bin//inchworm --kmers jellyfish.kmers.fa --run_inchworm -K 25 -L 25 --monitor 1   --num_threads 6  --PARALLEL_IWORM  > /home/mariamoteiro/outTrinity/inchworm.K25.L25.fa.tmp
Running CMD: mv /home/mariamoteiro/outTrinity/inchworm.K25.L25.fa.tmp /home/mariamoteiro/outTrinity/inchworm.K25.L25.fa
Wednesday, June 20, 2018: 23:59:56      CMD: touch /home/mariamoteiro/outTrinity/inchworm.K25.L25.fa.finished
--------------------------------------------------------
-------------------- Chrysalis -------------------------
-- (Contig Clustering & de Bruijn Graph Construction) --
--------------------------------------------------------

inchworm_target: /home/mariamoteiro/outTrinity/both.fa
bowite_reads_fa: /home/mariamoteiro/outTrinity/both.fa
chrysalis_reads_fa: /home/mariamoteiro/outTrinity/both.fa
Running CMD: /home/mariamoteiro/miniconda2/opt/trinity-2.6.6/util/support_scripts/filter_iworm_by_min_length_or_cov.pl /home/mariamoteiro/outTrinity/inchworm.K25.L25.fa 100 10 > /home/mariamoteiro/outTrinity/chrysalis/inchworm.K25.L25.fa.min100
 Running CMD: /home/mariamoteiro/miniconda2/bin/bowtie2-build --threads 10 -o 3 /home/mariamoteiro/outTrinity/chrysalis/inchworm.K25.L25.fa.min100 /home/mariamoteiro/outTrinity/chrysalis/inchworm.K25.L25.fa.min100 1>/dev/null
Building a SMALL index
Segmentation fault (core dumped)
Error, cmd: /home/mariamoteiro/miniconda2/bin/bowtie2-build --threads 10 -o 3 /home/mariamoteiro/outTrinity/chrysalis/inchworm.K25.L25.fa.min100 /home/mariamoteiro/outTrinity/chrysalis/inchworm.K25.L25.fa.min100 1>/dev/null 2>tmp.32846.stderr died with ret 35584 at /home/mariamoteiro/miniconda2/opt/trinity-2.6.6/PerlLib/Pipeliner.pm line 166.
        Pipeliner::run(Pipeliner=HASH(0x55dfaed57e78)) called at /home/mariamoteiro/miniconda2/bin/Trinity line 1864
        main::run_chrysalis("/home/mariamoteiro/outTrinity/inchworm.K25.L25.fa", "/home/mariamoteiro/outTrinity/both.fa", 200, 500, "RF", "/home/mariamoteiro/outTrinity/both.fa", "/home/mariamoteiro/outTrinity/both.fa") called at /home/mariamoteiro/miniconda2/bin/Trinity line 1664
        main::run_Trinity() called at /home/mariamoteiro/miniconda2/bin/Trinity line 1317
        eval {...} called at /home/mariamoteiro/miniconda2/bin/Trinity line 1316

**Comment by brianjohnhaas** [comment]
Hi

You might need to upgrade your bowtie2 installation or run trinity with the —no_bowtie flag.

Best

-Brian
(by iPhone)
