### ISSUE TITLE
Error in EC.david produced from prep_n_run_GOplot.pl

### ISSUE THREAD

**Issue by yihanwu** [trinityrnaseq/trinityrnaseq#505]
Hi Trinity Group,

I'm trying to generate goplots using the results of an edgeR analysis after doing go enrichment using max 1000 DE genes using analyze_diff_expr.pl. I'm using the updated prep_n_run_GOplot.pl file from the trinity google group and I get the warnings:

Warning messages:
1: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  number of items read is not a multiple of the number of columns

when generating the pdfs. As a result, there are missing values passed to goplot and the pdf figures are incomplete. 

Warning messages:
1: Removed 30 rows containing missing values (geom_point).
2: Removed 1 rows containing missing values (geom_text).
3: Removed 2 rows containing missing values (geom_text).
Warning messages:
1: Removed 30 rows containing missing values (geom_point).
2: Removed 2 rows containing missing values (geom_text).
Warning messages:
1: Removed 30 rows containing missing values (geom_point).
2: Removed 2 rows containing missing values (geom_text).
Warning messages:
1: Removed 15 rows containing missing values (geom_point).
2: Removed 1 rows containing missing values (geom_text).
3: Removed 2 rows containing missing values (geom_text).
Warning messages:
1: Removed 30 rows containing missing values (geom_point).
2: Removed 30 rows containing missing values (geom_point).
Warning messages:
1: Removed 30 rows containing missing values (geom_point).
2: Removed 30 rows containing missing values (geom_point).

When I re-run the command repeatedly, sometimes these ggplot warnings do not show up. Other times, I get an error like the one below.

Error in f(..., self = self) : Breaks and labels are different lengths
Calls: GOCircle ... guide_train -> guide_train.colorbar -> <Anonymous> -> f
In addition: Warning messages:
1: Removed 17 rows containing missing values (geom_point).
2: Removed 17 rows containing missing values (geom_point).
Execution halted
Error, CMD: $HOME/RNAAlliaria/Trinity/transcript_abundance/GOplot.Rscript --EC_david tmp/EC.david --EC_genelist tmp/EC.genelist --pdf_outfile CL_vs_TL_11.pdf died with ret 256 at ../prep_n_run_GOplot.pl line 247.

I'm using Trinity 2.6.5 with r/3.5.0 and perl/5.22.4.

Any help would be appreciated!

Thanks,
Yihan

**Comment by brianjohnhaas** [comment]
go-plot is only weakly supported here. Best to try to run it directly if it gives trouble.
