### ISSUE TITLE
Error, bam file doesn't appear to be coordinate sorted. Scaffold:  is out of order. 

### ISSUE THREAD

**Issue by Liyi56** [trinityrnaseq/trinityrnaseq#509]
I use  the command “Trinity --genome_guided_bam merged_sorted_bam --output genomeguide_trinity_out ”, and then I got the error "Error, bam file doesn't appear to be coordinate sorted. Scaffold:  is out of order. " .
so,I think  it is because of the problem of  merged_sorted_bam.   but I don't know why the error happen!  
I  got the merged_sorted_bam file from the two command;
one is  "samtools  merge -@ 20 ./merged_bam input1.bam input2.bam input3.bam..."
and another one is "samtools sort -@ 20 -o merged_sorted_bam merged_bam"
I use the samtools which version is 1.3, the trinityrnaseq's version is 2.4.0.

Friday, June 29, 2018: 09:41:43 CMD: /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl merged_bam
Use of uninitialized value in hash element at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 31, <__ANONIO__> line 2.
Use of uninitialized value in string eq at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 36, <__ANONIO__> line 3.
Use of uninitialized value in string eq at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 36, <__ANONIO__> line 4.
Use of uninitialized value in hash element at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 56, <__ANONIO__> line 4.
Use of uninitialized value in concatenation (.) or string at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 57, <__ANONIO__> line 4.
Error, bam file doesn't appear to be coordinate sorted. Scaffold:  is out of order.  at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 57, <__ANONIO__> line 4.
Error, cmd: /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl merged_bam died with ret 6400 at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.

**Comment by Liyi56** [comment]
Friday, June 29, 2018: 09:41:43 CMD: /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl merged_bam
Use of uninitialized value in hash element at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 31, <__ANONIO__> line 2.
Use of uninitialized value in string eq at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 36, <__ANONIO__> line 3.
Use of uninitialized value in string eq at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 36, <__ANONIO__> line 4.
Use of uninitialized value in hash element at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 56, <__ANONIO__> line 4.
Use of uninitialized value in concatenation (.) or string at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 57, <__ANONIO__> line 4.
Error, bam file doesn't appear to be coordinate sorted. Scaffold:  is out of order.  at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl line 57, <__ANONIO__> line 4.
Error, cmd: /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/util/support_scripts/ensure_coord_sorted_sam.pl merged_bam died with ret 6400 at /share/workplace/home/stu_huiyanan/my_software/trinityrnaseq-Trinity-v2.4.0/Trinity line 2462.

**Comment by brianjohnhaas** [comment]
I think you want to use the merged_sorted_bam file and not the other bam that's not sorted.
