### ISSUE TITLE
reduce number of files retained that take up *lots* of storage.

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#51]
Why keep both.fa and both.fa.wLongReads.fa ?  
Is there a reason why "both.fa.wLongReads.fa" is not used by bowtie (they would need to be renamed, the 1024 name char limit) ?

**Comment by g1o** [comment]
Hello, I did a patch for this, the pull request is names as Long reads

**Comment by brianjohnhaas** [comment]
patch merged
