### ISSUE TITLE
ExN50 Calc - RSEM problem with length

### ISSUE THREAD

**Issue by manuelsmendoza** [trinityrnaseq/trinityrnaseq#518]
Hi!

I am trying yo calculate ExN50 for a transcriptome assembled using multiple samples by alignment-based method (RSEM + Bowtie2). However I have the following problem:

```
rsem-scan-for-paired-end-reads 1 bowtie2.bam.for_rsem.tmp.bam bowtie2.bam.for_rsem.bam
.
Finished!

Conversion is completed. bowtie2.bam.for_rsem.bam will be checked by 'rsem-sam-validator'.
rsem-sam-validator bowtie2.bam.for_rsem.bam
.
Read All have different read/mate lengths!
The input file is not valid!
``` 

This problem was reported in RSEM Git repo but nobody has already answered it ([#56](https://github.com/deweylab/RSEM/issues/56) and [#82](https://github.com/deweylab/RSEM/issues/82)). Does anyone know what is happening?

**Comment by brianjohnhaas** [comment]
not sure.  Kallisto or salmon could work here.
