### ISSUE TITLE
Error [...] died with ret 256 at trinityrnaseq-v2.4.0/Trinity line 2462.

### ISSUE THREAD

**Issue by Bherran** [trinityrnaseq/trinityrnaseq#519]
Hello,
I am currently trying to assemble a (big) transcriptome (de novo) but there is one of the command which keeps failing. I have tried to lauch it several times but I always get the same error (see below). Should I suppress all files and start all over ?

"We are sorry, commands in file: [failed_butterfly_commands.11346.txt] failed.  :-(
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at jaligner.NeedlemanWunschGotoh.align(NeedlemanWunschGotoh.java:89)
        at NWalign.run_NW_alignment(NWalign.java:165)
        at TransAssembly_allProbPaths.getPrevCalcNumMismatches(TransAssembly_allProbPaths.java:10895)
        at TransAssembly_allProbPaths.twoPathsAreTooSimilar(TransAssembly_allProbPaths.java:10523)
        at TransAssembly_allProbPaths.reduce_cdhit_like(TransAssembly_allProbPaths.java:15367)
        at TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:1304)
Trinity run failed. Must investigate error above.
succeeded(0), failed(1)   100% completed.
We are sorry, commands in file: [FailedCommands] failed.  :-(
Error, cmd: /usr/local/bioinf/TRINITY/trinityrnaseq-v2.4.0/trinity-plugins/parafly/bin/ParaFly -c recursive_trini ty.cmds -CPU 12 -v  died with ret 256 at /usr/local/bioinf/TRINITY/trinityrnaseq-v2.4.0/Trinity line 2462.
Trinity run failed. Must investigate error above."

**Comment by brianjohnhaas** [comment]
Hi,

This is unfortunate.  If you can find that FailedCommand file in the
trinity output directory, you can try running it directly and adjust the
java heap size in the command to a higher value.  If it completes
successfully, then simply

    cp  recursive_trinity.cmds   recursive_trinity.cmds.completed

rerun your original Trinity command, and it should wrap up and generate the
final output.

best,

~brian



On Thu, Jul 19, 2018 at 1:12 PM Bherran <notifications@github.com> wrote:
>
> Hello,
> I am currently trying to assemble a (big) transcriptome (de novo) but
there is one of the command which keeps failing. I have tried to lauch it
several times but I always get the same error (see below). Should I
suppress all files and start all over ?
>
> "We are sorry, commands in file: [failed_butterfly_commands.11346.txt]
failed. :-(
> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit
exceeded
> at jaligner.NeedlemanWunschGotoh.align(NeedlemanWunschGotoh.java:89)
> at NWalign.run_NW_alignment(NWalign.java:165)
> at
TransAssembly_allProbPaths.getPrevCalcNumMismatches(TransAssembly_allProbPaths.java:10895)
> at
TransAssembly_allProbPaths.twoPathsAreTooSimilar(TransAssembly_allProbPaths.java:10523)
> at
TransAssembly_allProbPaths.reduce_cdhit_like(TransAssembly_allProbPaths.java:15367)
> at TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:1304)
> Trinity run failed. Must investigate error above.
> succeeded(0), failed(1) 100% completed.
> We are sorry, commands in file: [FailedCommands] failed. :-(
> Error, cmd:
/usr/local/bioinf/TRINITY/trinityrnaseq-v2.4.0/trinity-plugins/parafly/bin/ParaFly
-c recursive_trini ty.cmds -CPU 12 -v died with ret 256 at
/usr/local/bioinf/TRINITY/trinityrnaseq-v2.4.0/Trinity line 2462.
> Trinity run failed. Must investigate error above."
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by brianjohnhaas** [comment]
the next release will have a --FORCE option to help here.
