### ISSUE TITLE
Suggestion for contig_ExN50_statistic.pl 

### ISSUE THREAD

**Issue by manuelsmendoza** [trinityrnaseq/trinityrnaseq#523]
Hi!

The `contig_ExN50_statistic.pl` script attaches `edgeR` package directly and, if the user hasn't installed it, the output will be an error so, maybe it would be a good idea make a conditional statement like, attach it if it's installed OR if it isn't, install it and then attach. 

```
if (!require(edgeR)){
source("https://bioconductor.org/biocLite.R")
biocLite("edgeR")
library(edgeR)
}
```

**Comment by brianjohnhaas** [comment]
It's now integrated into the run_DE_analysis.pl script.  thanks!
