### ISSUE TITLE
Error during Transcript expression quantitation using RSEM

### ISSUE THREAD

**Issue by vivekabarath** [trinityrnaseq/trinityrnaseq#555]
Hi Brian,

A Good day to you.

I am trying to do transcript expression quantitation for a transcriptome generated from paired-end RNA-seq data from 24 files. I have run into an error which I can't understand 

I ran the align_and_estimate_abundance.pl using the following parameters:

align_and_estimate_abundance.pl --seqType fq \
        --samples_file /scratch/Trinity_Run_3/Sample_File_1.txt \
         --transcripts trinity_out_dir/Trinity.fasta  \
         --est_method RSEM  --aln_method bowtie2 \
         --trinity_mode --prep_reference \
         --output_dir RSEM \
	 > Transcript_expression_quantitation_using_RSEM.log 2>&1 & 

The output saved in Transcript_expression_quantitation_using_RSEM.log is as attached. The Sample_File_1.txt is also attached. 
[Transcript_expression_quantitation_using_RSEM.log](https://github.com/trinityrnaseq/trinityrnaseq/files/2307749/Transcript_expression_quantitation_using_RSEM.log)
[Sample_File_1.txt](https://github.com/trinityrnaseq/trinityrnaseq/files/2307748/Sample_File_1.txt)

Kindly Help.

With best regards

Baradwaj

**Comment by vivekabarath** [comment]
Hi,

Any pointers from any one will be of great use. I am unable to resolve this issue as of now.

Please Help.

Baradwaj

**Comment by brianjohnhaas** [comment]
hi - can you try using the kallisto or salmon options for quantification and see how that goes?  Debugging rsem issues isn't much fun.

**Comment by vivekabarath** [comment]
Thank you very much Brian Kallisto Worked like a charm :)
