### ISSUE TITLE
E90N50

### ISSUE THREAD

**Issue by jiffen** [trinityrnaseq/trinityrnaseq#566]
Hi Brian,

I did E90N50 analysis . I am just wondering I am not getting big improvement in N50 value of E90 over total assembly. How should I interpret this? Whether my assembly is of good or bad quality?
N50: 1450bp
E90N50:1701bp

**Comment by brianjohnhaas** [comment]
Probably fine.  If you sequence really deep then you’ll tend too see a big difference.  Let’s see what your exn50 plot looks like

-Brian
(by iPhone)

**Comment by jiffen** [comment]
[ExN50.stats.plot.pdf](https://github.com/trinityrnaseq/trinityrnaseq/files/2358719/ExN50.stats.plot.pdf)
Please find plot. Please let me know what I interpret from this?
