### ISSUE TITLE
align_and_estimate_abundance.pl parameters

### ISSUE THREAD

**Issue by tomas-pluskal** [trinityrnaseq/trinityrnaseq#580]
Hi,

The ```align_and_estimate_abundance.pl```  script has a parameter called ```--output_prefix ```, while the ```abundance_estimates_to_matrix.pl``` script has a parameter called ```--out_prefix```. Why not name the parameters the same?

Also, I wonder if it is possible to specify a prefix like "expression/kallisto" to get all the related files produced in the "expression" folder.

**Comment by tomas-pluskal** [comment]
Correction: it seems the ```--output_prefix``` parameter is gone in the current version of Trinity..?

I got it from here: https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Transcript-Quantification#estimating-transcript-abundance

**Comment by brianjohnhaas** [comment]
right, out prefix is gone so that all files will have the same names, but put into directories that are sample-specific.
