### ISSUE TITLE
TMM normalization result might be incorrect

### ISSUE THREAD

**Issue by xinbindai** [trinityrnaseq/trinityrnaseq#61]
TMM normalization need take raw count as input and output norm factor to adjust final FPKM. 

However, the line #217 of util/abundance_estimates_to_matrix.pl only send fpkm matrix file into run_TMM_scale_matrix.pl and the latter take the FPKM matrix as input to calculate TMM norm factor. So the norm factor is totally different from the old version (r2013). I would say the old r2013 version is correct although it calculate FPKM based on fixed transcript length per sample. 

Suggestion: run_TMM_scale_matrix.pl need two parameters, one for count matrix file and one for fpkm matrix file. The count matrix file should be used to calculate TMM factor and the fpkm matrix file will be next loaded and adjusted by norm factor.

**Comment by brianjohnhaas** [comment]
Thanks for your comments.    This was done this way mainly because I wanted to separate the cross-sample normalization of FPKMs from that done based on the counts, since there are several methods for doing abundance estimation and each computes FPKMs differently based on estimated effective transcript length values.   I essentially don't want to have to recompute FPKM (or TPM) and instead leverage the values already computed by the more sophisticated software tools.  Given any matrix of expression values (counts, FPKM, whatever), you can then rescale the matrices using any favorite scaling normalization method, of which TMM is  just one variety.   The math behind TMM normalization should work fine when applied to FPKM or other matrices, similarly to other choices (ie. upper quartile).

I'll make this more clear in the documentation for our next release.

thanks again!

**Comment by xinbindai** [comment]
Thank you for quick response. I spent a few days understanding basic principle behind TMM. It will be great if we can normalize FPKM by simply introducing a adjust factor. However, I am still confused by some opposed opinions on published paper for this possibility:

In edgeR user guide, Page 11: "Note that normalization in edgeR is model-based, and the original read counts are not themselves transformed. This means that users should not transform the read counts in any way before inputing them to edgeR. For example, users should not enter RPKM or FPKM values to edgeR in place of read counts. Such quantities will prevent edgeR from correctly estimating the mean-variance relationship in the data, which is a crucial to the statistical strategies underlying edgeR."
I actually saw similar sentences in DEseq manual for Median normalization. So it may not suitable to use FPKM stead of raw count for these kind of normalization although it relieve us from calculating program-specific FPKM.

Secondly, supposedly we can directly input FPKM to calculate norm factor, there is one more issue: The normalization factor from edgeR is targeted to calculate effective lib size, therefore the normalized value = the raw count (or FPKM in current run_TMM_scale_matrix.pl) /(library size x norm factor). The denominator is effective lib size in this equation. The normalized value can be re-scaled to a legible region later. The current implementation of run_TMM_scale_matrix.pl ignore the variance of library size(the sum of FPKM is inconsistent over libraries).

Please check this link (https://stat.ethz.ch/pipermail/bioconductor/2012-July/046795.html) for detail and a published paper(PMID:22988256) also mentioned this: "According to the hypothesis of low DE, this TMM should be close to 1. If it is not, its value provides an estimate of the correction factor that must be applied to the library sizes (and not the raw counts) in order to fulfill the hypothesis. The calcNormFactors() function in the edgeR Bioconductor package provides these scaling factors. To obtain normalized read counts, these normalization factors are re-scaled by the mean of the normalized library sizes. Normalized read counts are obtained by dividing raw read counts by these re-scaled normalization factors."

So I still suggest the method on the top: inputting raw count to calculate norm factor then divide FPKM (from RSEM) by the norm factor.

**Comment by brianjohnhaas** [comment]
The TMM normalization that happens in the DE analysis is entirely separate
from the one we use for doing cross-normalization on the FPKM values.

All of the edgeR methodology is adhered to properly.

On Fri, Sep 25, 2015 at 4:09 PM, xinbindai <notifications@github.com> wrote:

> Thank you for quick response. I spent a few days understanding basic
> principle behind TMM. It will be great if we can normalize FPKM by simply
> introducing a adjust factor. However, I am still confused by some opposed
> opinions on published paper for this possibility:
>
> In edgeR user guide, Page 11: "Note that normalization in edgeR is
> model-based, and the original read counts are not themselves transformed.
> This means that users should not transform the read counts in any way
> before inputing them to edgeR. For example, users should not enter RPKM or
> FPKM values to edgeR in place of read counts. Such quantities will prevent
> edgeR from correctly estimating the mean-variance relationship in the data,
> which is a crucial to the statistical strategies underlying edgeR."
> I actually saw similar sentences in DEseq manual for Median normalization.
> So it may not suitable to use FPKM stead of raw count for these kind of
> normalization although it relieve us from calculating program-specific FPKM.
>
> Secondly, supposedly we can directly input FPKM to calculate norm factor,
> there is one more issue: The normalization factor from edgeR is targeted to
> calculate effective lib size, therefore the normalized value = the raw
> count (or FPKM in current run_TMM_scale_matrix.pl) /(library size x norm
> factor). The denominator is effective lib size in this equation. The
> normalized value can be re-scaled to a legible region later. The current
> implementation of run_TMM_scale_matrix.pl ignore the variance of library
> size(the sum of FPKM is inconsistent over libraries).
>
> Please check this link (
> https://stat.ethz.ch/pipermail/bioconductor/2012-July/046795.html) for
> detail and a published paper(PMID:22988256) also mentioned this: "According
> to the hypothesis of low DE, this TMM should be close to 1. If it is not,
> its value provides an estimate of the correction factor that must be
> applied to the library sizes (and not the raw counts) in order to fulfill
> the hypothesis. The calcNormFactors() function in the edgeR Bioconductor
> package provides these scaling factors. To obtain normalized read counts,
> these normalization factors are re-scaled by the mean of the normalized
> library sizes. Normalized read counts are obtained by dividing raw read
> counts by these re-scaled normalization factors."
>
> So I still suggest the method on the top: inputting raw count to calculate
> norm factor then divide FPKM (from RSEM) by the norm factor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/61#issuecomment-143340480>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
