### ISSUE TITLE
what is the best transcript？

### ISSUE THREAD

**Issue by cushionXY** [trinityrnaseq/trinityrnaseq#616]
I read the manual ”Defining a reduced 'best' transcript set“. 
In my understanding, you only keep the orf of  per unigene as transcript. Is this correct?

**Comment by brianjohnhaas** [comment]
I think David Mathog picked this up on the forum.  His updated description is here:
https://github.com/trinityrnaseq/trinity_community_codebase/wiki/Trinity-best-transcript-set
