### ISSUE TITLE
The difference of max_hit option (-k) in bowtie2 

### ISSUE THREAD

**Issue by yiyian-Lee** [trinityrnaseq/trinityrnaseq#622]
Hello！
I just have some problem about using bowtie2 with Trinity.

When we need to test RNA-Seq read representation, it needs to use bowtie2 and have -k 20
But in the examing strand-specific, the parameter of -k is 10
Is this difference important?
It does not influence my work, but I am interesting about whether I have to keep them to use  analysis programs of Trinity.

Can you help me?

Thankful, 
Have a nice day.                             ~Lee, Yi-Yan

**Comment by brianjohnhaas** [comment]
The setting is somewhat arbitrary

You just want it to be high enough so it'll capture alignments to multiple
isoforms in regions of shared sequence

-via googleFi

**Comment by yiyian-Lee** [comment]
Thanks for your help,
I will try to use another -k numbers

Good luck
