### ISSUE TITLE
strip cntrl-M chars from input fqs

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#64]
perhaps this goes into fastool?

**Comment by anuj2054** [comment]
I installed trinity but when I run trinity it says that bowtie is needed
along with it. I also installed bowtie 1 and bowtie 2 and made sure it was
in the $PATH.
Then I ran trinity with a --no-bowtie option but it still gives an error
along the lines of " phase 1 , thread1 died with ret 768 at line 2177".
Could someone please help me.
Thanks,
Anuj

**Comment by brianjohnhaas** [comment]
Hi

You'll want to use the google group for support:

https://groups.google.com/forum/#!forum/trinityrnaseq-users

In this instance, you'll want to post the full output of what you see
including the error message.

On Tue, Sep 29, 2015 at 5:28 PM, anuj2054 <notifications@github.com> wrote:

> I installed trinity but when I run trinity it says that bowtie is needed
> along with it. I also installed bowtie 1 and bowtie 2 and made sure it was
> in the $PATH.
> Then I ran trinity with a --no-bowtie option but it still gives an error
> along the lines of " phase 1 , thread1 died with ret 768 at line 2177".
> Could someone please help me.
> Thanks,
> Anuj
>
> On Tue, Sep 29, 2015 at 4:21 PM, Brian Haas <notifications@github.com>
> wrote:
>
> > perhaps this goes into fastool?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/trinityrnaseq/trinityrnaseq/issues/64>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/64#issuecomment-144196486>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Still an issue that needs to be fixed for the next version.
