### ISSUE TITLE
Trinity default configuration for reads trimming

### ISSUE THREAD

**Issue by manuelsmendoza** [trinityrnaseq/trinityrnaseq#645]
Hi folk,

After reading [MacManes' paper](https://www.frontiersin.org/articles/10.3389/fgene.2014.00013/full) I disagree with the default configuration for reads trimming that is using Trinity at now. At supplementary data of [Trimmomatic's paper](https://academic.oup.com/bioinformatics/article/30/15/2114/2390096), the authors said that the best option to "clean" the reads data set for *de novo* assembly is using **maximum information** strategy. Which is your opinion about? 

Cheers,
~MM.

**Comment by brianjohnhaas** [comment]
If anyone has better parameters for trimming, we could use those as defaults.  The evidence should support whatever is chosen, and Matt's paper currently sets the standard for what we do.  The parameter can be changed via the command line pretty easily to explore other settings.  Or, you can do the trimming separately and run Trinity on the reads as you provide them w/o doing any additional trimming.
