### ISSUE TITLE
In silico normailisation issue

### ISSUE THREAD

**Issue by sofiapar265** [trinityrnaseq/trinityrnaseq#646]
Dear Brian,
       I try to assemble 12 libraries from one species and seems that I have issues with normalization. A huge number of reads are discarded during that process.

10205696 / 393835024 = 2.59% reads selected during normalization.
0 / 393835024 = 0.00% reads discarded as likely aberrant based on coverage profiles.
0 / 393835024 = 0.00% reads missing kmer coverage (N chars included?).

[trinity.txt](https://github.com/trinityrnaseq/trinityrnaseq/files/2803270/trinity.txt)

Any advice of how to proceed will be helpful
Thanks a lot in advance!

**Comment by SamMcGreig** [comment]
Hi Sofiapar, I've also got this issue:

12004 / 931488 = 1.29% reads selected during normalization.
0 / 931488 = 0.00% reads discarded as likely aberrant based on coverage profiles.
0 / 931488 = 0.00% reads missing kmer coverage (N chars included?).
0 / 931488 = 0.00% reads discarded as below minimum coverage threshold=1

Did you ever work out what was causing it?

Sam

**Comment by brianjohnhaas** [comment]
If only 1.3% of reads are being selected, it might be that you have mostly rRNA or some super highly abundant transcripts that are comprising the reads.  Is this a typical whole transcriptome RNA-seq or something targeted?
