### ISSUE TITLE
bugfixes for installing trinity under CentOS 6.5 with OpenMP support

### ISSUE THREAD

**Issue by samfux84** [trinityrnaseq/trinityrnaseq#65]
I installed trinity on our HPC cluster and encountered a few problems during the installation, which I would like to report here. In order to get proper OpenMP support, I had to fix a few things in the Makefiles that I would like to share with you.

trinityrnaseq-2.0.6/Makefile:

Here I had to add the follwoing line to the makefile (I added it at line 14):

INCHWORM_CONFIGURE_FLAGS = CXXFLAGS="-fopenmp"

trinityrnaseq-2.0.6/trinity-plugins/Makefile:

Here I had to replace line 41:

cd ${PARAFLY_CODE} && sh ./configure --prefix=`pwd` && $(MAKE) install
by
cd ${PARAFLY_CODE} && sh ./configure --prefix=`pwd` CXXFLAGS="-fopenmp" && $(MAKE)

With this two changes, trinity compiled without giving errors any more. When running "make plugins", I again encountered a problem. I had to fix a problem in

trinityrnaseq-2.0.6/trinity-plugins/TransDecoder_r20140704/Makefile (this is stored in TransDecoder_r20140704.tar.gz):

Here I had to replace line 10:

cd 3rd_party/parafly && ./configure --prefix=`pwd`/../../util && $(MAKE) install

by

cd 3rd_party/parafly && ./configure --prefix=`pwd`/../../util LDFLAGS="-lgomp" && $(MAKE) install

afterwards the plugins were compiling without errors.

Best regards

Sam

**Comment by benfulton** [comment]
Hi Sam,

In both Inchworm and Parafly, there are configure commands that are run by the Trinity make that are intended to add the openmp libraries if they are available. Do you have any idea why they might not have been found on your system?

**Comment by samfux84** [comment]
Hi Ben,

I think I have found the cause of the problem. For some reason, the $CXX variable was not set on the system where I tried to install Trinityseq. Both, Inchworm and Parafly check for this variable and only add -fopenmp if the variable is set:

> case $CXX in
>   g++*) AM_CXXFLAGS="-pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated $AM_CXXFLAGS"
> ;;
>   sunCC*) AM_CXXFLAGS="-library=stlport4 -xopenmp -xvpara -fast $AM_CXXFLAGS"
>  ;;
>   icpc*) AM_CXXFLAGS="-Wall -openmp $AM_CXXFLAGS"
>  ;;
> esac

Therefore it does not seem to be a general problem of Trinityseq. One just has to make sure that the $CXX variable is set correctly.

**Comment by benfulton** [comment]
Thanks for following up! I don't think we need to make any changes at this time then.

**Comment by samfux84** [comment]
Hi Ben,

sorry for reopening this issue. I have just an additional comment about the -fopenmp issue. When the gcc compiler is installed in a non-standard location, then setting the $CXX variable does not solve the problem. The Inchworm configure script only checks for $CXX=g++. But if gcc is installed in a non-standard location, then the variable contains the full path to g++. For instance on our system:

```
[sfux@euler02 Inchworm]$ echo $CXX
/cluster/apps/gcc/4.8.2/bin/g++
[sfux@euler02 Inchworm]$ 
```
Therefore the configure script of inchworm skips the following part:

```
[sfux@euler02 Inchworm]$ grep -B1 -A1 fopenmp configure
case $CXX in
  g++*) AM_CXXFLAGS="-ansi -pedantic -fopenmp -Wall -Wextra -Wno-deprecated $AM_CXXFLAGS"
;;
[sfux@euler02 Inchworm]$
```
When I change

`g++*)`

to

`*g++)`

then it works.
