### ISSUE TITLE
--illumina-trinity parameter fail

### ISSUE THREAD

**Issue by tomas-pluskal** [trinityrnaseq/trinityrnaseq#66]
Hi,

I'm trying to run Trinity v2.1.0 on fastq file downloaded from the NCBI Sequence Read Archive (id SRR688037). I downloaded the raw reads using this command

     fastq-dump -v SRR688037 --split-files --gzip

then I try to run Trinity as (below line is slightly simplified from the actual script) 

     Trinity --seqType fq --left SRR688037_1.fastq.gz --right SRR688037_2.fastq.gz 

but it fails at the stage of converting fastq to fasta using fastool. I found that Trinity always calls the fastool with the --illumina-trinity parameter. The following line is in Trinity source:

     $fastool_cmd .= " --illumina-trinity --to-fasta >> $file_prefix.fa 2> $f.readcount ";

However, the --illumina-trinity parameter causes the fastool to fail on these files with the following message:

     Error, cannot convert fastq file to fasta since cannot recognize read orientation as /1 or /2 (instead: H)

I believe this is because the fastq headers are not in the Illumina format, but in the NCBI format. Example fastq entry is below:

```
@SRR688037.1 HWI-ST521:78:D0MBFACXX:6:1101:1201:1163 length=100
CGCTGATGTNTCCTTCAATGTAGCCTCCAGTCTTGCGACCAGCCAAGACATCCATAAGAGTTGTCTTCCCCGCTCCACTAACACCCATCAGTGCTGTCAG
+SRR688037.1 HWI-ST521:78:D0MBFACXX:6:1101:1201:1163 length=100
B@CFFFFDF#2AFHIHIIJJHHFHHIIJJIHIJIIJJIJJIIGIDGII>GGDHDFH@HIIECC?AHHEFFFDDDB3:ACCDDDCBDDDCCDCDAACACCA
```

What is the purpose of the --illumina-trinity parameter and why is it always set by default? Can I safely remove this parameter in the Trinity source code?

**Comment by brianjohnhaas** [comment]
Here's the way to go with SRA data:

https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-FAQ#ques_sra_fq_conversion

best,

~brian


On Tue, Oct 13, 2015 at 11:31 AM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi,
>
> I'm trying to run Trinity v2.1.0 on fastq file downloaded from the NCBI
> Sequence Read Archive (id SRR688037). I downloaded the raw reads using this
> command
>
>  fastq-dump -v SRR688037 --split-files --gzip
>
> then I try to run Trinity as (below line is slightly simplified from the
> actual script)
>
>  Trinity --seqType fq --left SRR688037_1.fastq.gz --right SRR688037_2.fastq.gz
>
> but it fails at the stage of converting fastq to fasta using fastool. I
> found that Trinity always calls the fastool with the --illumina-trinity
> parameter. The following line is in Trinity source:
>
>  $fastool_cmd .= " --illumina-trinity --to-fasta >> $file_prefix.fa 2> $f.readcount ";
>
> However, the --illumina-trinity parameter causes the fastool to fail on
> these files with the following message:
>
>  Error, cannot convert fastq file to fasta since cannot recognize read orientation as /1 or /2 (instead: H)
>
> I believe this is because the fastq headers are not in the Illumina
> format, but in the NCBI format. Example fastq entry is below:
>
> @SRR688037.1 HWI-ST521:78:D0MBFACXX:6:1101:1201:1163 length=100
> CGCTGATGTNTCCTTCAATGTAGCCTCCAGTCTTGCGACCAGCCAAGACATCCATAAGAGTTGTCTTCCCCGCTCCACTAACACCCATCAGTGCTGTCAG
> +SRR688037.1 HWI-ST521:78:D0MBFACXX:6:1101:1201:1163 length=100
> B@CFFFFDF#2AFHIHIIJJHHFHHIIJJIHIJIIJJIJJIIGIDGII>GGDHDFH@HIIECC?AHHEFFFDDDB3:ACCDDDCBDDDCCDCDAACACCA
>
> What is the purpose of the --illumina-trinity parameter and why is it
> always set by default? Can I safely remove this parameter in the Trinity
> source code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/66>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by tomas-pluskal** [comment]
Thanks a lot!
Can you please still answer my original question - what is the purpose of the  --illumina-trinity parameter?
Would the results be affected if I run fastool without this parameter?

**Comment by brianjohnhaas** [comment]
Francesco (fastool author) - can you tackle this question please?

many thx,

~b

On Tue, Oct 13, 2015 at 3:37 PM, Tomáš Pluskal <notifications@github.com>
wrote:

> Thanks a lot!
> Can you please still answer my original question - what is the purpose of
> the --illumina-trinity parameter?
> Would the results be affected if I run fastool without this parameter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/66#issuecomment-147826044>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by fstrozzi** [comment]
Hi! 
The --illumina-trinity option was specifically designed to directly converts Casava 1.8+ FastQ headers to Fasta input format expected by Trinity (appending /1 and /2 for PE reads). If you have already FastQ files with headers properly formatted (i.e. with /1 and /2) this option should return the sequences in Fasta format without changing the headers.

For SRA files they follow a different headers format and as pointed out by Brian you need to threat them differently.
The issue parsing SRA files was also discussed on the Fastool repository few months ago: https://github.com/fstrozzi/Fastool/issues/5

Cheers
Francesco

**Comment by brianjohnhaas** [comment]
Thanks, Francesco!

~b

On Wed, Oct 14, 2015 at 4:00 AM, Francesco Strozzi <notifications@github.com
> wrote:

> Hi!
> The --illumina-trinity option was specifically designed to directly
> converts Casava 1.8+ FastQ headers to Fasta input format expected by
> Trinity (appending /1 and /2 for PE reads). If you have already FastQ files
> with headers properly formatted (i.e. with /1 and /2) this option should
> return the sequences in Fasta format without changing the headers.
>
> For SRA files they follow a different headers format and as pointed out by
> Brian you need to threat them differently.
> The issue parsing SRA files was also discussed on the Fastool repository
> few months ago: fstrozzi/Fastool#5
> <https://github.com/fstrozzi/Fastool/issues/5>
>
> Cheers
> Francesco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/66#issuecomment-147967215>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by macmanes** [comment]
FYI: This is also a problem with files downloaded from the ENA - here, you're downloading FQ files directly. Easy enough to fix with a sed command to get rid of the spaces in the file names, but generalizing the FASTOOL fastq parser to allow for spaces in the header line might be easier given this bug will trip up lots of people.

More generally, almost the entire Trinity pipeline supports FASTQ at this point, with just a few things needing 'minor' mod. Particularly in mapping reads, leveraging the quality scores could be valuable.

**Comment by benfulton** [comment]
This is a bit of a pain with Galaxy as we don't allow our users to run tools like sed. If there's no objection I'll modify Trinity to always use "append /1" on left files and "append /2" on right files, and only use the illumina-trinity flag on single files.

**Comment by brianjohnhaas** [comment]
We'll move to seqtk in a future release

**Comment by benfulton** [comment]
I made the modifications I proposed.

**Comment by yannickwurm** [comment]
forcing the user to add /1 and /2 is redundant with providing --left  and --right. This is a bit awkward...

**Comment by brianjohnhaas** [comment]
agreed.  We'll revise all of this in the next release.

~b

On Thu, Mar 24, 2016 at 5:10 AM, Yannick Wurm <notifications@github.com>
wrote:

> forcing the user to add /1 and /2 is redundant with providing --left and
> --right. This is a bit awkward...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/66#issuecomment-200747809>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
