### ISSUE TITLE
 The 'factor_labeling.txt' file in run_GOseq.pl

### ISSUE THREAD

**Issue by yuhe4046** [trinityrnaseq/trinityrnaseq#663]
Hi,
we're working on a eukaryotic genome (fish) with no reference genome. 

But I am not sure about the 'factor_labeling.txt' file in run_GOseq.pl, could you show me an example file about the  'factor_labeling.txt' file. 

thanks
Felice

**Comment by yuhe4046** [comment]
My email is yuhe2046@126.com, thank you so much!

**Comment by brianjohnhaas** [comment]
Hi,

I have some more extensive examples in the subdirectory:

 trinity_ext_sample_data/

of the Trinity distribution.  It's not populated by default.

There is a __pull_trinity_ext_sample_data.sh  script in the base Trinity
directory that you can run and it should populate the data there.

In that subdirectory, you'll find:

trinity_ext_sample_data/test_GOSeq_trinotate_pipe/Spombe_runGOseqOnly

which contains a simple example for you to test with.

best,

~b


On Mon, Mar 25, 2019 at 1:27 AM yuhe4046 <notifications@github.com> wrote:
>
> My email is yuhe2046@126.com, thank you so much!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
