### ISSUE TITLE
Some questions about "--jaccard_clip"

### ISSUE THREAD

**Issue by yangfanLiu1995** [trinityrnaseq/trinityrnaseq#669]
Hi:
 I have read your paper about trinity. When the genome has a high gene density with UTR overlap,we should use this parameter: 

> --jaccard_clip.

This methods reduce the numbers of complete transcripts. Now we want to use some softwares to splice the assembled transcript contigs, depending on the overlap region.(My transcripts are got from rumen protozoa)
1)How does the parameter work?
2)Will the parameter affect the results of assembly based on my transcript contigs.

**Comment by brianjohnhaas** [comment]
the best thing to do would be to run it with and then without this option and see how the results compare.
