### ISSUE TITLE
Trinity fail on the sample test data in the Chrysalis step

### ISSUE THREAD

**Issue by Lesdormis** [trinityrnaseq/trinityrnaseq#672]
Dear all,

I am trying to run Trinity with the sample test data to see if it can work in my machine, but after 4 days running it has still not finished. Which I think it is stuck in the Chrysalis step.
![image](https://user-images.githubusercontent.com/30546732/55500932-5f9ef400-5617-11e9-91c6-3c4c2a7897e2.png)

And here is the code that I ran with the test data
![image](https://user-images.githubusercontent.com/30546732/55500970-79403b80-5617-11e9-9df0-a1719a8aa61e.png)

And I installed Trinity with miniconda,
Here is the list of my conda enviroment
![image](https://user-images.githubusercontent.com/30546732/55501041-95dc7380-5617-11e9-9334-c62e870cd3e9.png)

Any helps or suggestion would be appreciated!

Thanks

**Comment by brianjohnhaas** [comment]
bowtie2 can hang up in a grid computing framework when it is running as multithreaded but there's only one thread allocated.  That might be the issue here.
