### ISSUE TITLE
quick question - comparing assembled transcript to close relative

### ISSUE THREAD

**Issue by frymor** [trinityrnaseq/trinityrnaseq#674]
In the wiki page under **Counting Full Length Trinity Transcripts** you mentioned the possibility of comparing an assembled transcript to a close relative. This is the case I have too and I would like to ask for your suggestion. 
I have done the assembly using trinity and I also have a close relative with an annotated genome (gtf file). 

Can you please recommend a way to do this comparison?

thanks

**Comment by brianjohnhaas** [comment]
Sure.  You can use the set of protein sequences from your annotated
reference genome of interest.  Same commands, just different target protein
database

-via googleFi

**Comment by frymor** [comment]
I'll give it a try.
