### ISSUE TITLE
Genome-Guided Trinity fails if BAM file is not sorted

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#7]
"-warning, no read partitions defined for scaffold: <name of scaffold>" error messages appear for all of scaffolds, resulting in empty "...minC1.gff.listing" and "read_files.list" files.

Unsuccessful fixes:
I've tried resorting the files, but the error persists. I thought it might be an issue with the read groups, so I've re-mapped each sample separately, added a unique read groups ID for each, along with other read group tags (SM, CN, PL, PU, LB). I then sorted and merged the bam files and re-run GG-guided trinity, using this bam file with --genome_guided_use_bam <combined_with_RG.csorted.bam>, but I still get the same error.
I'm using picard to do the sorting and to add the read groups. I also validated the bam file using picard ValidateSamFile, which didn't return any error

**Comment by brianjohnhaas** [comment]
Yes, make sure it's coordinate sorted.  The bam-reader in Trinity should do this check and error out with a useful error message when expectations are not met.

**Comment by brianjohnhaas** [comment]
closed, this is addressed in another ticket and will be tackled in the next release
