### ISSUE TITLE
Adding unpaired reads when having more than one paired library

### ISSUE THREAD

**Issue by JPascualAnaya** [trinityrnaseq/trinityrnaseq#70]
So, this is not quite an issue, but more of a question on how to include unpaired reads (for instance, those that remain when a pair is discarded when preprocessing data). If I have, let's say 5 libs, and for each of them I have a unpaired.fastq file, should I cat them to the left reads in each of the lib paired_1.fastq files? Or should I cat all the paired_1.fastq first, then at the end add the unpaired.fastq, and last on a second file cat all the paired_2.fastq? In other words

1)
cat A_paired_1.fastq A_unpaired.fastq > A_all_1.fastq
cat B_paired_1.fastq B_unpaired.fastq > B_all_1.fastq
Trinity --seqType fq --left A_all_1.fastq,B_all_1.fastq --right A_paired_2.fastq,B_paired_2.fastq <options>

OR

2)
cat A_paired_1.fastq B_paired_1.fastq A_unpaired.fastq B_unpaired.fastq > all_1.fastq
cat A_paired_2.fastq B_paired_2.fastq > all_2.fastq
Trinity --seqType fq --left all_1.fastq --right all_2.fastq <options>

Thanks,
Juan

**Comment by brianjohnhaas** [comment]
Hi Juan

If you're not going to do quality trimming or normalization, then either
should be fine.

If you are going to do trimming or normalization, then there's no good way
to include the dual data types as part of our process.

best,

~b

On Fri, Oct 23, 2015 at 1:40 AM, Juan Pascual-Anaya <
notifications@github.com> wrote:

> So, this is not quite an issue, but more of a question on how to include
> unpaired reads (for instance, those that remain when a pair is discarded
> when preprocessing data). If I have, let's say 5 libs, and for each of them
> I have a unpaired.fastq file, should I cat them to the left reads in each
> of the lib paired_1.fastq files? Or should I cat all the paired_1.fastq
> first, then at the end add the unpaired.fastq, and last on a second file
> cat all the paired_2.fastq? In other words
>
> 1)
> cat A_paired_1.fastq A_unpaired.fastq > A_all_1.fastq
> cat B_paired_1.fastq B_unpaired.fastq > B_all_1.fastq
> Trinity --seqType fq --left A_all_1.fastq,B_all_1.fastq --right
> A_paired_2.fastq,B_paired_2.fastq
>
> OR
>
> 2)
> cat A_paired_1.fastq B_paired_1.fastq A_unpaired.fastq B_unpaired.fastq >
> all_1.fastq
> cat A_paired_2.fastq B_paired_2.fastq > all_2.fastq
> Trinity --seqType fq --left all_1.fastq --right all_2.fastq
>
> Thanks,
> Juan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/70>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by JPascualAnaya** [comment]
Thanks Brian!

I plan to do two assemblies, with normalization, and without normalization. No trimming within Trinity, since I used a different program from trimmomatic for preprocessing. Then, in case of normalization, if I leave the unpaired data out, all should be fine, right? Can I still keep track of the samples, in a comma-separated list of files?

Best,
Juan

**Comment by brianjohnhaas** [comment]
I think it should be fine.

Also, unless you have a lot of SE reads you want to bundle it, it probably
won't make much of a difference.

best of luck!

On Sun, Oct 25, 2015 at 10:09 PM, Juan Pascual-Anaya <
notifications@github.com> wrote:

> Thanks Brian!
>
> I plan to do two assemblies, with normalization, and without
> normalization. No trimming within Trinity, since I used a different program
> from trimmomatic for preprocessing. Then, in case of normalization, if I
> leave the unpaired data out, all should be fine, right? Can I still keep
> track of the samples, in a comma-separated list of files?
>
> Best,
> Juan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/70#issuecomment-151002343>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
