### ISSUE TITLE
Error in Chrysalis phase

### ISSUE THREAD

**Issue by hidvegin** [trinityrnaseq/trinityrnaseq#713]
I tried Illumina 150 bp paired-end reads de novo assembly with Trinity 2.8.3 from homebrew-bio. I used this parameters for Trinity: Trinity --seqType fq --left LC06_1.fq.gz --right LC06_2.fq.gz --CPU 6 --max_memory 60G --no_salamon

I get this error message under the Chrysalis phase:

--------------------------------------------------------
-------------------- Chrysalis -------------------------
-- (Contig Clustering & de Bruijn Graph Construction) --
--------------------------------------------------------

inchworm_target: /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa
bowite_reads_fa: /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa
chrysalis_reads_fa: /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa
* Running CMD: /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/util/support_scripts/filter_iworm_by_min_length_or_cov.pl /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/inchworm.K25.L25.DS.fa 100 10 > /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100
* Running CMD: /home/linuxbrew/.linuxbrew/bin/bowtie2-build --threads 6 -o 3 /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 1>/dev/null
Error, cmd: /home/linuxbrew/.linuxbrew/bin/bowtie2-build --threads 6 -o 3 /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 /HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/chrysalis/inchworm.K25.L25.DS.fa.min100 1>/dev/null 2>tmp.7463.1563104940.stderr died with ret 62720  at /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/PerlLib/Pipeliner.pm line 186.
	Pipeliner::run(Pipeliner=HASH(0x27f3ee0)) called at /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Trinity line 1935
	main::run_chrysalis("/HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/inchw"..., "/HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa", 200, 500, undef, "/HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa", "/HDD2/de_novo_pohanka/Trinity_illesztes/trinity_out_dir/both.fa") called at /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Trinity line 1701
	main::run_Trinity() called at /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Trinity line 1340
	eval {...} called at /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Trinity line 1339

Trinity run failed. Must investigate error above.

Can somebody suggest to me a solution for my problem?

**Comment by brianjohnhaas** [comment]
Hi

Looks like bowtie is having trouble.  Try including --no_bowtie

Also, change salamon to salmon

Best

-via googleFi

**Comment by hidvegin** [comment]
Hello,

Thank you for your help. I tried yesterday what you mentioned and Trinity assembly was good with --no_bowtie and --no_salmon.

Best.
