### ISSUE TITLE
Trinity Error in Read Names

### ISSUE THREAD

**Issue by twohrdrive** [trinityrnaseq/trinityrnaseq#721]
Hello,

I have completed a pipeline that has taken me quite some time, and I really hope I can find a solution without going back to step one.

I pulled down data from an SRA with the following command:
`fastq-dump --skip-technical --split-3 --readids --clip SRR5396442 --read-filter pass -v -v -v SRR5396442.sra`

I then used Rconnector, then a python script for fixing the appended read names from Rconnector, passed this on to TrimGalore!, and finally on to Trinity. 

Here's what a fastq sequence looks like after all of this work (showing left only):

@SRR5396442.816.1 816 length=153
GTGTGTACAAAGGGCAGGGACGTAATCATTGCAGGTTGATGACCTGCAATTACTAGGAATTCCTCGTTCAAGAGCAATAATTTCAATGCTCTATCCCCATCACGACGCACTTTAAAAAGATTTCCCAACCCCATCGGGACAGGAATTTTAAAC
+
C@@CCGFEDC9FDE7FCCE8CC@<FG<<CAEFG9FEA,CF9E9,CC,;FCFGFA,6E6E@DGG9CC<<,CF9@FG<EFAFADF<<EG9,A5,,CFDCFF@4,A:>=C:FFCA?<<?AECFGDF,FCAF++C+4==8BE++@D6DD=>9D,8@D`

Error, not recognizing read name formatting: [SRR5396442.816.2]

I know that you need a /1 and /2 in left and right sequence headers.  If I used `--defline '@$sn[_$rn]/$ri'` with the above fastq-dump, the fastq sequences then start with @/1, and contain no additional information.

Is there a way to fix this without re-pulling SRA data? If I need to pull the data, is it okay if my left file looks like this? (sorry, this example still has untrimmed/removed sequences)

`@1/1
CGGTCATAGGTAACTGAGGTTGTATGCGAGGTCCCTGTCGCAAGATGGGAGCTGAGTGTGCTTCTTTGGCCCTATGACGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGACTGTTTAATNAAAANANNACGTTGTGTNNGNCTNNNNNNNTTNNGTNNNNNNN
+SRR5396442.1.1 1 length=248
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGECEF################################################################################################################3/3944=89@9#)2:>#-##(/0(((66(##(#,,#######//##((#######`

**Comment by brianjohnhaas** [comment]
sorry for missing this old ticket.

Including   --defline-seq '@$sn[_$rn]/$ri'    in the fastq-dump parameter should give it the formatting that Trinity wants.

https://github.com/trinityrnaseq/trinityrnaseq/wiki/How-do-I-use-reads-I-downloaded-from-SRA%3F
