### ISSUE TITLE
error while plotting heatmap in ana

### ISSUE THREAD

**Issue by abhisheksinghnl** [trinityrnaseq/trinityrnaseq#723]
Hi,

 I am running following command 

analyze_diff_expr.pl --matrix TPM.All.txt -C 1 -P 0.001 --output DEG --samples sample_file.txt --max_DE_genes_per_comparison 5000 --order_columns_by_samples_file

It all runs fine and even generates the file but at the last section where the heatmap is to be plotted I run into errors. Could someone suggest a source of error or a quick fix.

 sample_cor = cor(data, method='pearson', use='pairwise.complete.obs')
> write.table(sample_cor, file="DEG.5000_max_DE_eachcompare.matrix.log2.centered.sample_cor.dat", quote=F, sep='        ')
> sample_dist = dist(t(data), method='euclidean')
> pdf("DEG.5000_max_DE_eachcompare.matrix.log2.centered.sample_cor_matrix.pdf")
> sample_cor_for_plot = sample_cor
> heatmap.3(sample_cor_for_plot, dendrogram='both', Rowv=as.dendrogram(hc_samples), Colv=as.dendrogram(hc_samples), col = myheatcol, scale='none', symm=TRUE, key=TRUE,density.info='none', trace='none', symkey=FALSE, symbreaks=F, margins=c(10,10), cexCol=1, cexRow=1, cex.main=0.75, main=paste("sample correlation matrix
+ ", "DEG.5000_max_DE_eachcompare.matrix.log2.centered") , ColSideColors=sampleAnnotations, RowSideColors=t(sampleAnnotations))
Error in as.dendrogram(hc_samples) : object 'hc_samples' not found
Calls: heatmap.3 -> as.dendrogram
Execution halted
Error, cmd: R --no-save --no-restore --no-site-file --no-init-file -q < DEG.5000_max_DE_eachcompare.matrix.R died with ret 256 at /packages/Miniconda3/envs/trinity/opt/trinity-2.8.5/Analysis/DifferentialExpression/PtR line 1697.
Error, Error, cmd: /packages/Miniconda3/envs/trinity/opt/trinity-2.8.5/Analysis/DifferentialExpression/PtR -m DEG.5000_max_DE_eachcompare.matrix --log2 --heatmap --min_colSums 0 --min_rowSums 0 --gene_dist euclidean --sample_dist euclidean --sample_cor_matrix --center_rows --save  -s sample_file.txt --order_columns_by_samples_file --sample_clust none  died with ret 6400 at /packages/Miniconda3/envs/trinity/bin/analyze_diff_expr.pl line 272.

**Comment by brianjohnhaas** [comment]
this ticket was overlooked accidentally.  If it's still relevant, please reopen.  Apologies for missing this one.

**Comment by AlvaroHHM** [comment]
Good morning Mr.Hass, i have the same problem when i enter the command --order_columns_by_samples_file
