### ISSUE TITLE
Trinity error under de novo RNA-seq

### ISSUE THREAD

**Issue by hidvegin** [trinityrnaseq/trinityrnaseq#726]
I run the Trinity 2.8.3 from homebrew. I used this code:

`Trinity --seqType fq --left R1 --right R2 --CPU 12 --max_memory 40G --no_salmon`

I used 100M reads for the de novo RNA-seq.

After this code I get this error message:

Trinity run failed. Must investigate error above.
warning, cmd: /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/util/support_scripts/../../Trinity --single "/HDD1/de_novo_RNA_lencse_illesztes/Trinity_LC01/trinity_out_dir/read_partitions/Fb_0/CBin_903/c90332.trinity.reads.fa" --output "/HDD1/de_novo_RNA_lencse_illesztes/Trinity_LC01/trinity_out_dir/read_partitions/Fb_0/CBin_903/c90332.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup --no_salmon   failed with ret: 65280, going to retry.
succeeded(370), failed(1159)   1.47196% completed.    

Error encountered::  <!----
CMD: /home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py --trinity_fasta /HDD1/de_novo_RNA_lencse_illesztes/Trinity_LC01/trinity_out_dir/read_partitions/Fb_1/CBin_1022/c102288.trinity.reads.fa.out/Trinity.tmp.fasta --out_prefix /HDD1/de_novo_RNA_lencse_illesztes/Trinity_LC01/trinity_out_dir/read_partitions/Fb_1/CBin_1022/c102288.trinity.reads.fa.out/Trinity.tmp.fasta.ST --incl_cdna 2>tmp.27345.1567189888.stderr

Errmsg:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/trinity/2.8.3_1/libexec/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py", line 11, in <module>
    import numpy
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/linuxbrew/.linuxbrew/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named _multiarray_umath

I installed the python and numpy from homebrew. I used Ubuntu 18.04.2 OS. Can you suggest something how can I resolve this issue?

**Comment by brianjohnhaas** [comment]
perhaps use conda to set up a python environment rather than homebrew
