### ISSUE TITLE
v2.0.5/2.1.1 cannot locate file; 

### ISSUE THREAD

**Issue by qingl0331** [trinityrnaseq/trinityrnaseq#74]
Hi guys,
I've had success running Trinity on our linux server , but have recently run into this error with my latest attempts to run assemblies:
Error, cannot locate file: /data1/qli/conus_transcriptome/data/2015_6sp/11878X1_151030_D00550_0300_BC7HM8ANXX_5.adqtrim_1.fq  at /home/qli/tool/trinityrnaseq-2.0.5/Trinity line 2084.
        main::create_full_path('ARRAY(0x161fcf0)', 1) called at /home/qli/tool/trinityrnaseq-2.0.5/Trinity line 998
my command line is : /home/qli/tool/trinityrnaseq-2.0.5/Trinity --seqType fq --max_memory 30G --left /data1/qli/conus_transcriptome/data/2015_6sp/11878X1_151030_D00550_0300_BC7HM8ANXX_5.adqtrim_1.fq  --right /data1/qli/conus_transcriptome/data/2015_6sp/11878X1_151030_D00550_0300_BC7HM8ANXX_5.adqtrim_2.fq  --CPU 26 --bflyHeapSpaceMax 5G --bflyCPU 19 --KMER_SIZE 32 --min_contig_length 75 --SS_lib_type RF --output 11878X1_151030_D00550_0300_BC7HM8ANXX_5.trinity --min_per_id_same_path 99 --max_diffs_same_path 1 --max_internal_gap_same_path 3 --full_cleanup
 I thought maybe  new version can overcome this problem, so I pull the 2.1.1 version, which is the latest , but it still gives me similar errors...
Would anyone know this? Thank you!
By the way, when I tried to install the new version, it complains:
JellyFish:               has been Installed Properly
Inchworm:                has been Installed Properly
Chrysalis Installation appears to have FAILED
QuantifyGraph Installation appears to have FAILED
GraphFromFasta Installation appears to have FAILED
ReadsToTranscripts Installation appears to have FAILED
fastool:                 has been Installed Properly
parafly:                 has been Installed Properly
samtools-0.1.19          has been Installed Properly
I did make and make plugins as suggested, but don't know whether this fix the problem...

**Comment by avahoffman** [comment]
I'm not 100% sure, but I think this means you need more memory. I got a similar message when trying to run with eight fastq files on a 4 CPU 32GB vm. When I made it two, it started running no problem.

**Comment by qingl0331** [comment]
Thnx~ that's what I did too~

2016-01-25 16:25 GMT-07:00 avahoffman <notifications@github.com>:

**Comment by brianjohnhaas** [comment]
user support issues are handled on the google forum:
https://groups.google.com/forum/#!forum/trinityrnaseq-users

In this case, definitely 'make clean' followed by 'make' to rebuild everything.
