### ISSUE TITLE
minor cluster problem

### ISSUE THREAD

**Issue by abelew** [trinityrnaseq/trinityrnaseq#75]
Greetings,
  If I run trinity on a torque/slurm cluster where I specify a large amount of memory and >1 cpu, my jobs get consistently removed because of samtools (notably line 1558 of Trinity.pl) which includes the amount of memory I gave to trinity and number of processes.
  Unfortunately, this means that if I run on a queue (for instance) which allows 60 Gb of memory used and 10 CPUs,  and I tell trinity to use 50Gb and 10 CPUs; then the samtools invocation ends up asking for 50Gb for each of the 10 CPUs, passing my allowed limit by 440Gb and getting kicked off.

  Since I didn't feel like modifying the '$PARALLEL_SAMTOOLS_SORT_TOKEN' to do floor(mem/cpus), I just modified those lines to look like the following: 

..  | samtools view  -F4 -Sb - | samtools sort -no - - > .../chrysalis/iworm.bowtie.nameSorted.bam"

  samtools takes longer, but now I don't get kicked off.  I figured this might be of interest to you.

**Comment by brianjohnhaas** [comment]
we're now splitting up the RAM among the number of samtools sort threads
