### ISSUE TITLE
Wiki: `--min_rowSum_counts <int>` is deprecated

### ISSUE THREAD

**Issue by hmontenegro** [trinityrnaseq/trinityrnaseq#758]
The wiki page [Differential Expression Analysis Using a Trinity Assembly](https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Differential-Expression) is outdated, showing the deprecated parameter `--min_rowSum_counts` instead of the current `--min_reps_min_cpm`.

**Comment by brianjohnhaas** [comment]
thanks!  updated now.
