### ISSUE TITLE
Missing RSEM Plugin

### ISSUE THREAD

**Issue by jsage8** [trinityrnaseq/trinityrnaseq#76]
It seems that the RSEM pluggin was removed from the plugins in this release? There's no directory for it in plugins after extracting the tar and the make plugins command doesn't report it as having been Installed Properly.

I rolled back to 2.0.6 and everything worked as expected with the same commands, so I don't think I'm doing anything incorrectly.

**Comment by jsage8** [comment]
Note this issue is for v2.1.1

**Comment by brianjohnhaas** [comment]
Thanks, Jonathan.  That's right, RSEM is no longer bundled with the Trinity
distro.  The installation checker shouldn't be looking for RSEM now. If it
is, we'll update it for the next release.

best,

~b

On Fri, Dec 4, 2015 at 4:33 PM, Jonathan Sage <notifications@github.com>
wrote:

> Note this issue is for v2.1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/76#issuecomment-162087486>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by mossmatters** [comment]
Hi, I also ran into an issue with 2.1.1 because Trinity is expecting rsem-calculate-expression in the $PATH. The Trinity installation documentation suggests that RSEM will be installed with ```make plugins``` but that is incorrect:

https://github.com/trinityrnaseq/trinityrnaseq/wiki/Installing%20Trinity

**Comment by brianjohnhaas** [comment]
Thanks for the info!   I've updated the documentation to remove the mention
about RSEM being incorporated since we no longer do this.



On Tue, Mar 22, 2016 at 1:18 AM, Matt Johnson <notifications@github.com>
wrote:

> Hi, I also ran into an issue with 2.1.1 because Trinity is expecting
> rsem-calculate-expression in the $PATH. The Trinity installation
> documentation suggests that RSEM will be installed with make plugins but
> that is incorrect:
>
> https://github.com/trinityrnaseq/trinityrnaseq/wiki/Installing%20Trinity
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/76#issuecomment-199642353>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
