### ISSUE TITLE
Gene Expression Matrix Output Directory Error 

### ISSUE THREAD

**Issue by sperkins21** [trinityrnaseq/trinityrnaseq#767]
Hello, 
I am attempting to use trinity to build a gene expression matrix on .tsv files generated with kallisto. When I am running the following command: 
/usr/local/Cellar/trinity/2.8.3_1/libexec/util/abundance_estimates_to_matrix.pl --est_method kallisto \
    --gene_trans_map /Users/My_Name/Downloads/Trinity.blubber.fasta.gene_trans_map \
    --out_prefix kallisto \
    --name_sample_by_basedir \
    /Users/My_Name/Downloads/SampleA/S56/abundances.tsv \
    /Users/My_Name/Downloads/SampleA/S59/abundances.tsv \
    /Users/My_Name/Downloads/SampleR/S57/abundances.tsv \
    /Users/My_Name/Downloads/SampleR/S60/abundances.tsv 

It seems to be running correctly, but yields the following output with an error at the end: 
-reading file: /Users/My_Name/Downloads/SampleA/S56/abundances.tsv
-reading file: /Users/My_Name/Downloads/SampleA/S59/abundances.tsv
-reading file: /Users/My_Name/Downloads/SampleR/S57/abundances.tsv
-reading file: /Users/My_Name/Downloads/SampleR/S60/abundances.tsv

* Outputting combined matrix.

Error, cannot write file kallisto.isoform.counts.matrix at /usr/local/Cellar/trinity/2.8.3_1/libexec/util/abundance_estimates_to_matrix.pl line 241.

I noticed that there is not a way to specify an output directory with this plugin. Is there a way I might be able to fix this problem? 
Thank you!

**Comment by brianjohnhaas** [comment]
apologies, we missed this.  If it's still an issue, we can revisit.
