### ISSUE TITLE
normalization with TPM value using abundance_estimates_to_matrix.pl ??

### ISSUE THREAD

**Issue by xflicsu** [trinityrnaseq/trinityrnaseq#77]
Hello trinity developers,
    I use utils of trinity to estimate abundance of gene expression.
    As we know we always use TMM or UpperQuartile method to normalize count value among several libraries. But I find the input matrix of "abundance_estimates_to_matrix.pl" are TPM values calculated with eXpress or RSEM.
    So, my question is : did this TPM matrix suitable for normalization with TMM or UpperQuartile method?

**Comment by brianjohnhaas** [comment]
I think you should be able to run the cross-sample normalization given the
expression matrix derived from any of the tools.


best,

~b

On Mon, Dec 7, 2015 at 3:07 AM, Xianfeng Li <notifications@github.com>
wrote:

> Hello trinity developers,
> I use utils of trinity to estimate abundance of gene expression.
> As we know we always use TMM or UpperQuartile method to normalize count
> value among several libraries. But I find the input matrix of "
> abundance_estimates_to_matrix.pl" are TPM values calculated with eXpress
> or RSEM.
> So, my question is : did this TPM matrix suitable for normalization with
> TMM or UpperQuartile method?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/77>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by xflicsu** [comment]
Thanks for your response!
Actually, I only have a matrix of read count produced by TEtranscripts ( estimate expression of transposone element). I want to normalize that matrix. So, what is the best way to choose?

**Comment by brianjohnhaas** [comment]
If all you have are read counts, then the simplest thing to do is to
convert them to CPM (counts per million). Then, you can run your favorite
cross-sample normalization method on them.

If you want FPKM or TPM, then you'd have to do a little more math to take
into account the feature lengths.

On Mon, Dec 7, 2015 at 8:33 AM, Xianfeng Li <notifications@github.com>
wrote:

> Thanks for your response!
> Actually, I only have a matrix of read count produced by TEtranscripts (
> estimate expression of transposone element). I want to normalize that
> matrix. So, what is the best way to choose?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/77#issuecomment-162525737>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
