### ISSUE TITLE
Jellyfish Version check fails

### ISSUE THREAD

**Issue by nterhoeven** [trinityrnaseq/trinityrnaseq#789]
Hi, 

I have a strange issue with the jellyfish version check:

First, the error message:

```
Found samtools at: /cluster/apps/gdc/samtools/1.8/bin/samtools

Found jellyfish at: /cluster/home/nterhoeven/software/jellyfish/jellyfish-2.3.0/bin/jellyfish

Can't exec "jellyfish": No such file or directory at /cluster/home/nterhoeven/software/Trinity/trinityrnaseq-v2.9.1/Trinity line 3878.
Use of uninitialized value $version_info in split at /cluster/home/nterhoeven/software/Trinity/trinityrnaseq-v2.9.1/Trinity line 3879.
Use of uninitialized value $version in pattern match (m//) at /cluster/home/nterhoeven/software/Trinity/trinityrnaseq-v2.9.1/Trinity line 3880.
Use of uninitialized value $version_info in concatenation (.) or string at /cluster/home/nterhoeven/software/Trinity/trinityrnaseq-v2.9.1/Trinity line 3881.
Error, need jellyfish v2, instead found  ; Get it here: http://www.genome.umd.edu/jellyfish.html at /cluster/home/nterhoeven/software/Trinity/trinityrnaseq-v2.9.1/Trinity line 3881.
```

As you can see, Trinity can find jellyfish in the `PATH`, but calling `jellyfish --version` in line 3878 fails. Running `jellyfish --version` outside Trinity returns `jellyfish 2.3.0` as expected.

Do you have any idea, what the problem might be here?

**Comment by brianjohnhaas** [comment]
I'm not sure.  From looking at the code, it should have recognized it fine.

If you need to, you can comment out the line in Trinity: 
&check_required_3rd_party_tool_installations(); # bowtie2, salmon, jellyfish, samtools

and it'll not examine all the different software versions.
