### ISSUE TITLE
Fully implementing thread_count parameter in align_and_estimate_abundance.pl

### ISSUE THREAD

**Issue by kk86bioinfo** [trinityrnaseq/trinityrnaseq#79]
Hi, I noticed that `rsem-calculate-expression` cmd in `align_and_estimate_abundance.pl` is always running with 4 threads no matter of how many more `thread_count` is set when running the script, is there any concern to default only 4 threads?

**Comment by brianjohnhaas** [comment]
nice catch!  This was a complete oversight.  Fixed now.
