### ISSUE TITLE
Error in as.dendrogram(hc_samples) : 'object 'hc_samples' not found

### ISSUE THREAD

**Issue by hndmrgl** [trinityrnaseq/trinityrnaseq#790]
Hi 
When i'm running analyze_diff_expr.pl i got this error below, can someone please help me fix this issue.

+ **** Sorry, at least two columns are required for this matrix.
+ 
+ ");}
> sample_cor = cor(data, method='pearson', use='pairwise.complete.obs')
> write.table(sample_cor, file="diffExpr.P1e-3_C2_GO.1000_max_DE_eachcompare.matrix.log2.centered.sample_cor.dat", quote=F, sep='	')
> sample_dist = dist(t(data), method='euclidean')
> pdf("diffExpr.P1e-3_C2_GO.1000_max_DE_eachcompare.matrix.log2.centered.sample_cor_matrix.pdf")
> sample_cor_for_plot = sample_cor
> heatmap.3(sample_cor_for_plot, dendrogram='both', Rowv=as.dendrogram(hc_samples), Colv=as.dendrogram(hc_samples), col = myheatcol, scale='none', symm=TRUE, key=TRUE,density.info='none', trace='none', symkey=FALSE, symbreaks=F, margins=c(10,10), cexCol=1, cexRow=1, cex.main=0.75, main=paste("sample correlation matrix
+ ", "diffExpr.P1e-3_C2_GO.1000_max_DE_eachcompare.matrix.log2.centered") , ColSideColors=sampleAnnotations, RowSideColors=t(sampleAnnotations))
Error in as.dendrogram(hc_samples) : 'object 'hc_samples' not found

**Comment by brianjohnhaas** [comment]
unhandled issue.  If still of interest, please reopen and will investigate. Need inputs to explore.
