### ISSUE TITLE
Results of run_variant_calling.py does not contain read group

### ISSUE THREAD

**Issue by haleycglass** [trinityrnaseq/trinityrnaseq#795]
Hello, 

I was successfully able to perform the run_variant_calling.py analysis on several sets of paired end reads. However, when I tried to perform some downstream analyses on the resulting VCF files I realized the "read groups" are not included. I looked into the .py script and see that is has the following lines:

Pipeliner.Command("java -jar " + PICARD_HOME + "/picard.jar " +
                          " AddOrReplaceReadGroups " +
                          "I=Aligned.sortedByCoord.out.bam " +
                          "O=rg_added_sorted.bam " +
                          " VALIDATION_STRINGENCY=SILENT " +
                          "SO=coordinate RGID=id RGLB=library RGPL=platform RGPU=machine RGSM=sample",
                          "add_read_groups.ok"),

After running:
samtools view -H splitNCigar.bam | grep '@RG'

The output is:
@RG     ID:id   LB:library      PL:platform     SM:sample       PU:machine

So it looks like it works, but only these generic names are carried over to the VCF output files, rather than information specific to the samples. In my case, I ran the run_variant_calling.py script separately for different sets of paired reads from samples I would like to identify variants in. I want the sample ID's, names. etc to be specified based on the input files so they can be differentiated in downstream analyses.

Thanks,
Haley

**Comment by brianjohnhaas** [comment]
thanks for posting, Haley.  We'll definitely get this for the next release.

**Comment by brianjohnhaas** [comment]
code is updated, will go into the next release.

commit b4f524298dd1bba1c3014997da0c6532397b193b (HEAD -> devel, origin/devel)
Author: Brian Haas <brianjohnhaas@gmail.com>
Date:   Thu Mar 19 15:29:13 2020 +0000

    added --rg_id and --rg_sample to store read group info in bams and vcfs as per issue #795
