### ISSUE TITLE
Genome-guided Trinity does not work with --trimmomatic option

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#8]
User gets error during gsnap alignment: "Paired-end accessions
HiSeq-ATC:2_BC4U97AXXX:BC4U97AXXX:2:1101:10008:28912 and
HiSeq-ATC:2_BC4U97AXXX:BC4U97AXXX:2:1101:10007:74100 do not match".

In April 2014 version this did not cause a pipeline failure but in July 2014 version it does.

**Comment by brianjohnhaas** [comment]
We no longer run any aligner as part of the genome-guided run.  Instead, the user provides a bam file, and it's up to the user to do any pre-processing prior to doing any alignment.
