### ISSUE TITLE
kallisto halts with error message

### ISSUE THREAD

**Issue by aungthurhahein** [trinityrnaseq/trinityrnaseq#80]
I am trying to run allignment free method with kallisto but it halts after building index from trinity.fasta.
According to [kallistio manual](https://pachterlab.github.io/kallisto/manual.html), the command should be 
>kallisto quant -i /home/aung/c01_trinity/c01_Trinity_Out/Trinity.fasta.kallisto_idx -o control_slx_tr_RSEM -l val  -s val --single /home/aung/shrimp_31_10_2013/control_slx_tr.fastq

As for single reads, it is required to provide both fragment length and estimated standard deviation of fragment length.
~~~
CMD: kallisto quant -l  -i /home/aung/c01_trinity/c01_Trinity_Out/Trinity.fasta.kallisto_idx -o control_slx_tr_RSEM  /home/aung/shrimp_31_10_2013/control_slx_tr.fastq

Error: kallisto index file missing

Usage: kallisto quant [arguments] FASTQ-files

Required arguments:
-i, --index=STRING            Filename for the kallisto index to be used for
                              quantification
-o, --output-dir=STRING       Directory to write output to

Optional arguments:
    --bias                    Perform sequence based bias correction
-b, --bootstrap-samples=INT   Number of bootstrap samples (default: 0)
    --seed=INT                Seed for the bootstrap sampling (default: 42)
    --plaintext               Output plaintext instead of HDF5
    --single                  Quantify single-end reads
-l, --fragment-length=DOUBLE  Estimated average fragment length
-s, --sd=DOUBLE               Estimated standard deviation of fragment length
                              (default: value is estimated from the input data)
-t, --threads=INT             Number of threads to use (default: 1)
    --pseudobam               Output pseudoalignments in SAM format to stdout
Error, cmd: kallisto quant -l  -i /home/aung/c01_trinity/c01_Trinity_Out/Trinity.fasta.kallisto_idx -o control_slx_tr_RSEM  /home/aung/shrimp_31_10_2013/control_slx_tr.fastq died with ret: 256 at /home/aung/software/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl line 714.
~~~

**Comment by macmanes** [comment]
Have you asked the @pachterlab people over on the Kallisto page (https://github.com/pachterlab/kallisto)? This seems like the more appropriate place for Kallisto support. 

What I will say is that you seem to be missing the integer after the `-l` argument.

**Comment by aungthurhahein** [comment]
@macmanes  Yes...That's what I already figured it out. That error comes from integration with Trinity at this perl script 
> ~util/align_and_estimate_abundance.pl

The problem is solved after providing value for **-l**, fragment length and **-s**,estimated standard deviation of fragment length arguments.

**Comment by brianjohnhaas** [comment]
This is fully revised for the upcoming release.
