### ISSUE TITLE
Comparing genome guided with de novo assembly

### ISSUE THREAD

**Issue by kopeckyl** [trinityrnaseq/trinityrnaseq#827]
Hello,

Is there any way to compare a trinity genome-guided with a de novo assembly?

Is there any specific metric to say which one was better?

Thank you!

Lucas

**Comment by gringer** [comment]
I would expect that the techniques mentioned [here](https://github.com/trinityrnaseq/trinityrnaseq/wiki/Transcriptome-Assembly-Quality-Assessment) can be used to compare the two assemblies.

I would be surprised if the genome-guided assembly _weren't_ better, given that it's using the same algorithm, but using the reads in a more intelligent fashion. I suppose if the reference genome were incomplete and excluded some reads, that might result in a better _de-novo_ assembly.
