### ISSUE TITLE
Error not recognized read name formatting

### ISSUE THREAD

**Issue by ARW-UBT** [trinityrnaseq/trinityrnaseq#829]
Hello Brian, 
I tried to clean a dataset of metatranscriptome data by mapping reads to the host genome by STAR and take the unmapped reads to perfom a meta-transcriptome assembly using Trinity (I know, Trinity was not made for this, but...). 

Unfortunately, I get the following error message quite early in Trinity: 
Error, not recognizing read name formatting: [NGSNJ-086:273:GW200308494th:1:1107:17707:30530]
(I can provide more of the error, if needed). 

I have tried it with a standalone Trinity on my machine as well as with Trinity implemented in the latest OmicsBox suite. Same error messages. 
I have attached the format of the original fastq sequences (R1 direction) and of the unmapped output from STAR (also R1 direction). There is some differences, but I can't see a problematic format. May be, you can!
Of course, the sequences are different, since some reads mapped to the host genome and are no longer present in the unmapped file.

The unmapped output work just fine with Tadpole assembler (via Geneious). 

 Thanks for any suggestion how to overcome this problem. 
[Fastq-Trinity-unmapped.txt](https://github.com/trinityrnaseq/trinityrnaseq/files/4546455/Fastq-Trinity-unmapped.txt)

**Comment by brianjohnhaas** [comment]
Hi,

It doesn't like the read naming format
"@NGSNJ-086:273:GW200308494th:1:1107:17707:30530 0:N:  00"

If you convert all your reads to fasta format, then you can run Trinity
with --seqType fa --single inputs.fa

Let's see if that works for you.

best,

~brian


On Tue, Apr 28, 2020 at 10:40 AM ARW-UBT <notifications@github.com> wrote:
>
> Hello Brian,
> I tried to clean a dataset of metatranscriptome data by mapping reads to
the host genome by STAR and take the unmapped reads to perfom a
meta-transcriptome assembly using Trinity (I know, Trinity was not made for
this, but...).
>
> Unfortunately, I get the following error message quite early in Trinity:
> Error, not recognizing read name formatting:
[NGSNJ-086:273:GW200308494th:1:1107:17707:30530]
> (I can provide more of the error, if needed).
>
> I have tried it with a standalone Trinity on my machine as well as with
Trinity implemented in the latest OmicsBox suite. Same error messages.
> I have attached the format of the original fastq sequences (R1 direction)
and of the unmapped output from STAR (also R1 direction). There is some
differences, but I can't see a problematic format. May be, you can!
> Of course, the sequences are different, since some reads mapped to the
host genome and are no longer present in the unmapped file.
>
> The unmapped output work just fine with Tadpole assembler (via Geneious).
>
> Thanks for any suggestion how to overcome this problem.
> Fastq-Trinity-unmapped.txt
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
