### ISSUE TITLE
trinityrnaseq-2.1.1 installing error

### ISSUE THREAD

**Issue by ShuChen1986** [trinityrnaseq/trinityrnaseq#83]
Dear all,

I was installing trinityrnaseq-2.1.1, and this is the error info I got from the installation.
Could anyone help me with this?
Thank you!

cd Inchworm && (test -e configure || autoreconf) \
                && sh ./configure --prefix=`pwd`  && make install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for library containing cos... none required
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make[1]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
Making install in src
make[2]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm/src'
make[3]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm/src'
test -z "/home/shu/software/trinityrnaseq-2.1.1/Inchworm/bin" || /bin/mkdir -p "/home/shu/software/trinityrnaseq-2.1.1/Inchworm/bin"
  /usr/bin/install -c inchworm cigar_tweaker pull_reads_with_kmers FastaToDeBruijn fastaToKmerCoverageStats '/home/shu/software/trinityrnaseq-2.1.1/Inchworm/bin'
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm/src'
make[2]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm/src'
make[2]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
make[3]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
make[2]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
make[1]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Inchworm'
cd Chrysalis && make UNSUPPORTED=yes 
make[1]: Entering directory `/home/shu/software/trinityrnaseq-2.1.1/Chrysalis'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/shu/software/trinityrnaseq-2.1.1/Chrysalis'
cd trinity-plugins && make trinity_essentials
/bin/sh: 1: cd: can't cd to trinity-plugins
make: *** [trinity_essentials] Error 2

**Comment by brianjohnhaas** [comment]
not sure, but no other similar problems reported by other users, so likely something user-specific that we cannot address at this time.
