### ISSUE TITLE
Few RSEM Output files empty !!!!!!!!

### ISSUE THREAD

**Issue by AlvZee** [trinityrnaseq/trinityrnaseq#845]
Hi I am using RSEM to estimate expression by trinity pipeline i get following files, image attached

![image](https://user-images.githubusercontent.com/64940303/82590638-06bc5300-9b6c-11ea-8b8c-3c4eb57685a3.png)

Just wondering why bowtie2.bam.ok, bowtie2.csorted.bam.ok, RSEM.isoforms.results.ok are of zero bytes.

Although it did generated rsem.isoform.results and rsem.genes.results of reasonable size, i used both files for edgeR analysis and got reasonable results. 

But just wanna make sure that these empty files are not screwing my analysis???????

**Comment by brianjohnhaas** [comment]
the .ok files are checkpoints set in case the process needs to be rerun and restart from where it left off. You can safely ignore them.
