### ISSUE TITLE
No read partition defined for scaffold

### ISSUE THREAD

**Issue by RubyDrus** [trinityrnaseq/trinityrnaseq#85]
Dear developers, dear community,

I am working with Trinity 2.0.6 and encounter the following problem when using the genome_guided mode: `-Warning - no read partition defined for scaffold: chr1`

Then it loops over all chromosomes. I found this message from the Google groups (https://groups.google.com/forum/#!topic/trinityrnaseq-users/b6G0T3p8_cc) but my files are sorted by coordinates and indexed.

Here my call:
`Trinity --genome_guided_bam 4101316.1000genomes.complete.bam --genome_guided_max_intron 500000 --max_memory 100G --CPU 10 --verbose`

The high intron max length I got from the following paper where they had intron lengths up 494 kB:
Sakharkar, M. K., Chow, V. T. K., & Kangueane, P. (2004, January 1). Distributions of Exons and Introns in the Human Genome. In Silico Biology. IOS Press.

Does anyone have an idea where the problem comes from?

Thanks in advance!

Best regards,
Ruben

**Comment by brianjohnhaas** [comment]
Hi,

It's not clear why this happened. If you're able to share an example bam
file with me, I'll be happy to give it a look.

best,

~b

On Fri, Jan 15, 2016 at 9:34 AM, RubyDrus <notifications@github.com> wrote:

> Dear developers, dear community,
>
> I am working with Trinity 206 and encounter the following problem when
> using the genome_guided mode: -Warning - no read partition defined for
> scaffold: chr1
>
> Then it loops over all chromosomes I found this message from the Google
> groups (
> https://groupsgooglecom/forum/#!topic/trinityrnaseq-users/b6G0T3p8_cc)
> but my files are sorted by coordinates and indexed
>
> Here my call:
> Trinity --genome_guided_bam 41013161000genomescompletebam
> --genome_guided_max_intron 500000 --max_memory 100G --CPU 10 --verbose
>
> The high intron max length I got from the following paper where they had
> intron lengths up 494 kB:
> Sakharkar, M K, Chow, V T K, & Kangueane, P (2004, January 1)
> Distributions of Exons and Introns in the Human Genome In Silico Biology
> IOS Press
>
> Does anyone have an idea where the problem comes from?
>
> Thanks in advance!
>
> Best regards,
> Ruben
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/85>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by RubyDrus** [comment]
Dear Brian-

Yesterday, I updated the Trinity version. It solved the original problem but caused a new problem: It aborts randomly during the writing of reads on chromosome 3.
I will test for reproducability today. Shall I open another issue?

Best regards,
Ruben

**Comment by RubyDrus** [comment]
Dear Brian-

the error could not be reproduced with other samples. It seems to be a sample-specific effect. Trinity now works fine!

Best regards,
Ruben

**Comment by brianjohnhaas** [comment]
Excellent!  Thanks for the update!

~brian


On Wed, Jan 27, 2016 at 3:28 AM, RubyDrus <notifications@github.com> wrote:

> Dear Brian-
>
> the error could not be reproduced with other samples. It seems to be a
> sample-specific effect. Trinity now works fine!
>
> Best regards,
> Ruben
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/85#issuecomment-175478180>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
