### ISSUE TITLE
Problem running align_and_estimate_abundance.pl

### ISSUE THREAD

**Issue by RayanaFeltrin** [trinityrnaseq/trinityrnaseq#856]
Hey there!
I got the following error when running the command `~/tools/Trinityrnaseq-v2.6.6/util/align_and_estimate_abundance.pl --seqType fq --samples_file gpul_adpul_samples.txt --transcripts Gpul_Adpul_trinity.Trinity.fasta --est_method salmon --trinity_mode --prep_reference`:

_[2020-06-11 01:53:08.809] [jointLog] [warning] NOTE: Read Lib [[ /dev/fd/63, /dev/fd/62]] :_

_Detected a potential strand bias > 1% in an unstranded protocol check the file: ADPUL3/lib_format_counts.json for details_

_CMD: /home/curupi/tools/Trinityrnaseq-v2.6.6/util/support_scripts/salmon_trans_to_gene_results.pl ADPUL3/quant.sf /home/curupi/data/pulchella/fastq/trim/Gpul_Adpul_trinity.Trinity.fasta.gene_trans_map > ADPUL3/quant.sf.genes_

strand_mapping_bias: 0.9945332800206606

May anyone help me, please?
Thank you in advance!

_Originally posted by @RayanaFeltrin in https://github.com/trinityrnaseq/trinityrnaseq/issues/684#issuecomment-642638891_

**Comment by brianjohnhaas** [comment]
responded to in forum
