### ISSUE TITLE
Differences between input data formats (FASTQ vs FASTA)

### ISSUE THREAD

**Issue by CarlosMenFer** [trinityrnaseq/trinityrnaseq#858]
I see that Trinity accepts both formats, Fastq and Fasta, as input data. I was wondering if there is any difference between FASTQ and FASTA file processing.

In other words, if I have the same dataset in both formats, and I run Trinity with each of them, should I expect the same results? Or should I expect different results?

I am aware that the FASTQ format contains the Phred quality, in addition to the sequence of each read, but I don't know if this information is used by Trinity at any time.

Thank you in advance. 
Best, 
C.

**Comment by brianjohnhaas** [comment]
Hi,

apologies for the delay in responding.   I didn't see this come through.    Fastq vs. Fasta won't matter unless you decide to include the --trimmomatic parameter, which will invoke trimmomatic quality trimming - leveraging the fastq qual values.  Nothing in Trinity other than this stage of the pipeline uses the quality values.

**Comment by CarlosMenFer** [comment]
Thanks so much for the explanation.
