### ISSUE TITLE
n50 length is too small

### ISSUE THREAD

**Issue by songmm19900210** [trinityrnaseq/trinityrnaseq#86]
I used trinity to assembly, I used default parameters to assemble. the assemble N50 is less than 600, how can i set parameters to increase N50?

**Comment by brianjohnhaas** [comment]
Hi

The n50 isn't such a useful metric.  Try looking into the ExN50
https://github.com/trinityrnaseq/trinityrnaseq/wiki/Transcriptome%20Contig%20Nx%20and%20ExN50%20stats

-Brian
(by iPhone)

**Comment by tiramisutes** [comment]
Yes, the ExN50 is a more  reliable indicator for Transcriptome Contig Statistics. But the  Trinity.fasta file still contains too many genes and transcripts (many isoforms). Therefore this is not better for subsequent analysis. Are there parameters that will 'help' trinity to recover longer transcripts and relative little genes and transcripts in the result file Trinity.fasta?

Follows are my Trinity results: 
200-500bp assembly result contain 584593 relative to Total trinity transcripts 835094
################################
## Counts of transcripts, etc.
################################
Total trinity 'genes':  578793
Total trinity transcripts:      835094
Percent GC: 41.85

########################################
Stats based on ALL transcript contigs:
########################################

        Contig N10: 3448
        Contig N20: 2309
        Contig N30: 1676
        Contig N40: 1223
        Contig N50: 862

        Median contig length: 332
        Average contig: 591.80
        Total assembled bases: 494206515


#####################################################
## Stats based on ONLY LONGEST ISOFORM per 'GENE':
#####################################################

        Contig N10: 3159
        Contig N20: 1939
        Contig N30: 1256
        Contig N40: 815
        Contig N50: 549

        Median contig length: 295
        Average contig: 482.99
        Total assembled bases: 279548419
#######################################################

Thanks!
