### ISSUE TITLE
Error in installing Trinity-v2.5.1

### ISSUE THREAD

**Issue by majie5976** [trinityrnaseq/trinityrnaseq#867]
Hi Dear,
I'm trying to install trinity-v2.5.1 that is tested for one of the software which I want to use for analysis. But there are two errors encountered while installing this version. Error below as, 
g++  -W -Wall -Wno-unused -Wno-deprecated -ansi -pedantic -Wno-long-long -fno-nonansi-builtins -Wctor-dtor-privacy -Wsign-promo -Woverloaded-virtual -Wendif-labels  -O3  -ggdb3 -DMAKE_DATE='"2020年 07月 08日 星期三 12:04:05 CST  "' -DMAKE_OS_RELEASE='"5.3.0-62-generic"' -DMAKE_RELEASE='"3.0"' -DNEW_MAKEFILE -imacros system/BigFileDefines.h -pthread  -ftemplate-depth-30 -fno-strict-aliasing -mieee-fp   -fopenmp        -c ./aligns/KmerAlignCore.cc -o obj/aligns/KmerAlignCore.o
**./aligns/KmerAlignCore.cc:6:10: fatal error: aligns/KmerAlignCore.h: 没有那个文件或目录 (no such file or directory)
 #include "aligns/KmerAlignCore.h**"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:473: recipe for target 'aligns/KmerAlignCore.o' failed
make[1]: *** [aligns/KmerAlignCore.o] Error 1
make[1]: 离开目录“/home/majie/kismat/kism/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/Chrysalis”
Makefile:30: recipe for target 'chrysalis_target' failed
make: *** [chrysalis_target] Error 2
Looking forward for the response.
Thanks
Regards,
Majie

**Comment by zhang144999** [comment]
你应该是想用dnapipeTE吧，只有dnaPipeTE用的这个版本的trinity
