### ISSUE TITLE
path specification for plugins

### ISSUE THREAD

**Issue by brianjohnhaas** [trinityrnaseq/trinityrnaseq#87]
Thanks for the quick response.

Please note:

I'm not suggesting that you stop bundling jellyfish, etc.  With the suggested changes I provided, the default behavior of the Trinity build would be exactly the same as it is now.   All bundled software would still be installed and used by default, even if there are other versions installed elsewhere.

To alter this behavior, someone would have to make deliberate changes to the trinity-plugins Makefile to prevent it from installing a particular plugin.  The difference is that they would only have to patch one Makefile instead of the Makefile + many scripts, which would make creating and maintaining the package much easier.

Package managers take responsibility for ensuring that the correct version of a dependency is installed, so having people install via a package manager would not generate more problems.  For example, the FreeBSD port contains the following dependency listings:

samtools01==0.1.19:/usr/wip/biology/samtools0119
jellyfish==2.1.4:/usr/wip/biology/jellyfish2
etc.

Having a Debian package and a MacPort out there in addition to our FreeBSD port and Pkgsrc package would eliminate a lot of problems for end-users by making deployment trivial on most of the platforms people are likely to use.  Discussions could then focus more on using and improving the software.

Cheers,

```
Jason
```

On 01/22/16 03:15, Brian Haas wrote:
Thanks, Jason.  In general, I agree with this idea, but the problem is that different versions of jellyfish have had different command line interfaces, and some versions of software (eg. Samtools) are more compatible with Trinity than other versions. We try to minimize bundling other packages in, but when we do it's because we really want you to use those versions and not the others installed.

I'm leaning towards eventually just dockerizing the package, so all these issues go away.  But then it requires that users can run docker, which opens another can of worms and security issues...

-Brian
(by iPhone)

On Jan 21, 2016, at 10:44 PM, Jason Bacon <bacon4000@gmail.com <mailto:bacon4000@gmail.com>> wrote:

Hi everyone,

First, thanks for maintaining Trinity!  We have several researchers here who use it extensively.

I'm wondering if you would consider taking a different approach to locating certain plugins and utils from within your scripts.  What I'm suggesting is an approach that you're already using for other things.

Here's an example:

The Trinity script contains the following statements to ensure that certain tools are found at run time:

|
|

$ENV{PATH}=dirname($PARAFLY).":$ENV{PATH}";
|

For other tools, like jellyfish, the absolute path name is used to invoke the command rather than utilizing $PATH:

|
|
|

My suggestion is to utilize $PATH rather than absolute path names for all executable utils and plugins.  In the case of jellyfish, this could be achieved as follows.

First, update the first statement setting PATH as follows:

|
|
|

Then, simply remove the prefix from the invocation of the jellyfish command:

|
|
|

This would still ensure that the bundled jellyfish is utilized if it is present, because $ROOTDIR/trinity-plugins/$JELLYFISH_DIR/bin is ahead of other potential locations of jellyfish in $PATH. However, it would also allow a separately installed jellyfish to be used without modifying the Trinity script if the bundled jellyfish is not installed.

My reasoning for this is that it would eliminate a lot of script patching for those of us who use a separate installation of jellyfish or other tools instead of the one that's bundled with Trinity.

We deploy most of our software using packages managers (currently pkgsrc on our CentOS systems and FreeBSD ports on our FreeBSD systems).  The package manager ensures that correct versions of dependencies like jellyfish are installed and installs them separately so they can be more easily used outside of Trinity.

The changes I suggest above would make it easier for developers using any package manager (Debian packages, FreeBSD Ports, MacPorts, Pkgsrc, Portage, etc.) to develop and maintain a Trinity package.

Thanks,

```
Jason
```

Jason Bacon
bacon4000@gmail.com

**Comment by mr-c** [comment]
This would be great. I just submitted a Debian package for trinity, it is in review. As expected we had to make a lot of patches. I am now opening pull requests for the patches that benefit everyone and are uncontroversial; but several of them we just replaced paths to suite.

http://anonscm.debian.org/cgit/debian-med/trinityrnaseq.git/tree/debian/patches

**Comment by brianjohnhaas** [comment]
In the next release, we'll no longer be bundling in packages such as jellyfish and samtools, instead relying on user installations of these as pre-reqs.
