### ISSUE TITLE
Inchworm CPU option not filling out all files

### ISSUE THREAD

**Issue by benfulton** [trinityrnaseq/trinityrnaseq#9]
User reports requesting 24 CPU but in working directory only 2 files are filled. He was able to work around the issue by setting OpenMP variables on the cluster:

export OMP_NUM_THREADS=28
export OMP_THREAD_LIMIT=29

In IRKE.cpp, the number of files created is equal to the return value of omp_get_max_threads().
This is an upper bound on the number of threads that can be created in a subsequent
parallel region; however, the requested number of threads is not guaranteed to be created unless
unless the dynamic adjustment of threads is disabled, either via the omp_dynamic(false) routine,
or by setting the OMP_DYNAMIC environment variable to "false".

This generally isn't an issue on systems that don't have other concurrent users, but
the OpenMP specification does allow an implementation to create any number of threads
less than or equal to the number of threads requested unless the dynamic adjustment of
threads is disabled.

**Comment by brianjohnhaas** [comment]
Ben - should we change the iworm code to deal with this, or just set ENV{OMP_DYNAMIC} = 'false' in the Trinity wrapper?

**Comment by benfulton** [comment]
I would prefer to change the iworm code. Setting the dynamic would be suboptimal for the system as a whole.

**Comment by brianjohnhaas** [comment]
ok - I added omp_set_dynamic(false) in IRKE_run.cpp
