### ISSUE TITLE
Allow option to point binary paths

### ISSUE THREAD

**Issue by rohitsuratekar** [trinityrnaseq/trinityrnaseq#901]
Currently, Trinity need `samtools`, `bowtie2`, `jellyfish`and `salmon` to be in PATH. It will be great if one can specify custom path to their respective binaries. It will help in construction of custom pipelines. Currently, one need to export all relevant paths before running Trinity. However, having such an option will be great addition!

Maybe something like  `Trinity --samtools 'path/to/samtools' --jellyfish 'path/to/jellyfish' --bowtie2 'path/to/bowtie2' --salmon 'path/to/salmon'`

**Comment by brianjohnhaas** [comment]
updating the PATH so that the proper versions are found as first is how we do it currently
