### ISSUE TITLE
Optimizing parameters

### ISSUE THREAD

**Issue by tomas-pluskal** [trinityrnaseq/trinityrnaseq#92]
Hi.

Would someone with more experience be willing to explain to me the consequences of changing these two parameters in Trinity?

--min_kmer_cov (min count for K-mers to be assembled by Inchworm, default: 1)
--min_glue (min number of reads needed to glue two inchworm contigs together, default: 2)

By intuition, I changed the the min_kmer_cov to 2, because I feld that K-mers detected only once would almost certainly be some sort of noise. I also changed min_glue to 5, hoping it would reduce the number of misassembled  transcripts. But this is just intuition, and unfortunately I don't see any way how to evaluate how good my transcriptome assembly is, other than going through each transcript manually, mapping the raw reads onto it and looking at coverage. With thousands of transcripts, this makes optimization rather difficult.

I would appreciate your advice, especially on the downstream consequences of changing these two parameters.

**Comment by brianjohnhaas** [comment]
Hi,

The --min_kmer_cov default of 1 will provide maximal sensitivity for
reconstructing lowly expressed transcripts.  You can set it higher, but
unless you have high depth of sequencing, it'll lead to increased
fragmentation of lowly expressed transcripts.  Keeping it at 1 could
certainly lead to higher base-level error rates, but Trinity tries to
mitigate this to the extent possible.  I'd suggest you keep it at 1 unless
there's a good reason to go higher (you really want to minimize base errors
and can tolerate higher fragmentation).

--min_glue refers to the minimum number of RNA-Seq reads required by the
Chrysalis step for linking together two inchworm contigs during the contig
clustering phase.  There's a short video that describes this:

http://www.broadinstitute.org/videos/trinity-how-it-works

I also wouldn't change this parameter.  If you set it higher than 2, you'll
again take a toll on lowly expressed transcript isoforms.  If you set it
lower than 2, you'll end up over-aggregating inchworm contigs, which leads
to runtime performance problems.

It's sometimes useful to experiment with the parameters if you have a
specific 'gene' you're working on (given a cluster of reads resulting form
the 1st phase of Trinity), but for the initial Trinity run, I wouldn't
recommend changing the defaults for either of those parameters.

I hope this helps,

~b

On Thu, Jan 28, 2016 at 9:36 AM, Tomáš Pluskal <notifications@github.com>
wrote:

> Hi
>
> Would someone with more experience be willing to explain to me the
> consequences of changing these two parameters in Trinity?
>
> --min_kmer_cov (min count for K-mers to be assembled by Inchworm, default:
> 1)
> --min_glue (min number of reads needed to glue two inchworm contigs
> together, default: 2)
>
> By intuition, I changed the the min_kmer_cov to 2, because I feld that
> K-mers detected only once would almost certainly be some sort of noise I
> also changed min_glue to 5, hoping it would reduce the number of
> misassembled transcripts But this is just intuition, and unfortunately I
> don't see any way how to evaluate how good my transcriptome assembly is,
> other than going through each transcript manually, mapping the raw reads
> onto it and looking at coverage With thousands of transcripts, this makes
> optimization rather difficult
>
> I would appreciate your advice, especially on the downstream consequences
> of changing these two parameters
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trinityrnaseq/trinityrnaseq/issues/92>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by tomas-pluskal** [comment]
Thanks a lot for the explanation!
