### ISSUE TITLE
Trinity assembly assessments

### ISSUE THREAD

**Issue by Genan-blur** [trinityrnaseq/trinityrnaseq#922]
Hi Brian
   I use BUSCO to assess the assembly, but there are many duplicated BUSCOs(maybe too many isoforms), Could you please tell me is this a good assembly?  and do I need to filter these isoforms?

Results from dataset eukaryota_odb10             |
	--------------------------------------------------
	|C:96.8%[S:24.3%,D:72.5%],F:1.6%,M:1.6%,n:255     |
	|247	Complete BUSCOs (C)                       |
	|62	Complete and single-copy BUSCOs (S)       |
	|185	Complete and duplicated BUSCOs (D)        |
	|4	Fragmented BUSCOs (F)                     |
	|4	Missing BUSCOs (M)                        |
	|255	Total BUSCO groups searched

**Comment by brianjohnhaas** [comment]
high duplication rates are normal for transcriptome assemblies and reflect the alternative splicing that's modeled.  This is in contrast to running Busco on a genome assembly.  The 97% completeness looks quite good.

**Comment by Genan-blur** [comment]
got it, thank you!
