### ISSUE TITLE
Trinity Unknown Error

### ISSUE THREAD

**Issue by gaslick** [trinityrnaseq/trinityrnaseq#924]
I have been trying to run Trinity on a set of 3 paired end samples and I am getting multiple errors after phase 1. The input and out are below. I am on the latest version of Trinity and working on a cluster. Any help is greatly appreciated.

**Input:**

Trinity --seqType fq --left 1_unmappedreadsformat,2_unmappedreadsformat.1,3_unmappedreadsformat.1,7_unmappedreadsformat.1,8_unmappedreadsformat.1,9_unmappedreadsformat.1 --right 1_unmappedreadsformat.2,2_unmappedreadsformat.2,3_unmappedreadsformat.2,7_unmappedreadsformat.2,8_unmappedreadsformat.2,9_unmappedreadsformat.2 --max_memory 10G --SS_lib_type RF --output /mnt/home/user/projects/TSE_collaboration/trinity_out_dir/

**Output:**

     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

    Trinity-v2.11.0

Left read files: $VAR1 = [
          '1_unmappedreadsformat',
          '2_unmappedreadsformat.1',
          '3_unmappedreadsformat.1',
          '7_unmappedreadsformat.1',
          '8_unmappedreadsformat.1',
          '9_unmappedreadsformat.1'
        ];
Right read files: $VAR1 = [
          '1_unmappedreadsformat.2',
          '2_unmappedreadsformat.2',
          '3_unmappedreadsformat.2',
          '7_unmappedreadsformat.2',
          '8_unmappedreadsformat.2',
          '9_unmappedreadsformat.2'
        ];
Trinity version: Trinity-v2.11.0
** NOTE: Latest version of Trinity is v2.11.0, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

Thursday, November 5, 2020: 08:46:08	CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/support_scripts/ExitTester.jar 0
Thursday, November 5, 2020: 08:46:08	CMD: java -Xmx4g -XX:ParallelGCThreads=2  -jar /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/support_scripts/ExitTester.jar 1

----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

---------------------------------------------------------------
------------ In silico Read Normalization ---------------------
-- (Removing Excess Reads Beyond 200 Coverage --
---------------------------------------------------------------

# running normalization on reads: $VAR1 = [
          [
            '/mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat',
            '/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.1',
            '/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.1',
            '/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.1',
            '/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.1',
            '/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.1'
          ],
          [
            '/mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat.2',
            '/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.2',
            '/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.2',
            '/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.2',
            '/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.2',
            '/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.2'
          ]
        ];

Thursday, November 5, 2020: 08:46:08	CMD: /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/insilico_read_normalization.pl --seqType fq --JM 10G  --max_cov 200 --min_cov 1 --CPU 2 --output /mnt/home/user/projects/TSE_collaboration/trinity_out_dir/insilico_read_normalization --max_CV 10000  --SS_lib_type RF  --left /mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat,/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.1 --right /mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.2 --pairs_together  --PARALLEL_STATS  
-prepping seqs
Converting input files. (both directions in parallel)left file exists, nothing to doright file exists, nothing to doDone converting input files.-kmer counting.
-generating stats files
-defining normalized reads
CMD: /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/..//util/support_scripts//nbkc_normalize.pl --stats_file pairs.K25.stats --max_cov 200  --min_cov 1 --max_CV 10000 > pairs.K25.stats.C200.maxCV10000.accs
Error, no reads made it to the normalization process...   at /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/..//util/support_scripts//nbkc_normalize.pl line 117.
Error, cmd: /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/..//util/support_scripts//nbkc_normalize.pl --stats_file pairs.K25.stats --max_cov 200  --min_cov 1 --max_CV 10000 > pairs.K25.stats.C200.maxCV10000.accs died with ret 65280 at /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/insilico_read_normalization.pl line 793.
Error, cmd: /mnt/home/user/miniconda3/opt/trinity-2.11.0/util/insilico_read_normalization.pl --seqType fq --JM 10G  --max_cov 200 --min_cov 1 --CPU 2 --output /mnt/home/user/projects/TSE_collaboration/trinity_out_dir/insilico_read_normalization --max_CV 10000  --SS_lib_type RF  --left /mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat,/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.1,/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.1 --right /mnt/home/user/projects/TSE_collaboration/1_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/2_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/3_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/7_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/8_unmappedreadsformat.2,/mnt/home/user/projects/TSE_collaboration/9_unmappedreadsformat.2 --pairs_together  --PARALLEL_STATS   died with ret 512 at /mnt/home/user/miniconda3/bin/Trinity line 2826.
	main::process_cmd("/mnt/home/user/miniconda3/opt/trinity-2.11.0/util/insilico"...) called at /mnt/home/user/miniconda3/bin/Trinity line 3379
	main::normalize("/mnt/home/user/projects/TSE_collaboration/trini"..., 200, ARRAY(0x56323f0afb08), ARRAY(0x56323f0afb38)) called at /mnt/home/user/miniconda3/bin/Trinity line 3319
	main::run_normalization(200, ARRAY(0x56323f0afb08), ARRAY(0x56323f0afb38)) called at /mnt/home/user/miniconda3/bin/Trinity line 1372

**Comment by nutria-tapeworm** [comment]
there are no colleagues on here
