### ISSUE TITLE
collectl usage

### ISSUE THREAD

**Issue by wolfQK** [trinityrnaseq/trinityrnaseq#955]
Hi,
I installed Trinity-2.11.0 via conda, and I run Trinity with parameter “--monitoring”，but I cannot find anything about the output of collectl. How can I use it correctly?
Thank you !

**Comment by brianjohnhaas** [comment]
the only documentation we have on this is here:  https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Runtime-Profiling
