### ISSUE TITLE
How to extract longest unigene?

### ISSUE THREAD

**Issue by Dementieva521** [trinityrnaseq/trinityrnaseq#956]

**Comment by Dementieva521** [comment]
I want to use method of a MBE paper. Their method is ' Total RNA extraction with ZR plant RNA MiniPrep kit and subsequent sequencing by illumina HiSeq2000 and assembling using Trinity (Grabherr et al. 2011) and TGICLv2.1 (Pertea et al. 2003) were performed as described in Huang et al. (2015). Redundant contigs in each transcriptome were removed using CD-HIT 4.6 (Fu et al. 2012) with the threshold of 0.98'. Hence I want to use Trinity to extract longest unigene instead of TGICL.

**Comment by brianjohnhaas** [comment]
we don't work with unigenes, but we have this for filtering:  https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Transcript-Quantification#filtering-transcripts
