### ISSUE TITLE
Another "Error, no TPM value specified for transcript" error

### ISSUE THREAD

**Issue by Jolleboll** [trinityrnaseq/trinityrnaseq#958]
Hello!

Error, no TPM value specified for transcript [TRINITY_DN0_c0_g1_i8] of gene [TRINITY_DN0_c0_g1] for sample HHG_3

I am using/doing the following:

abundance_estimates_to_matrix.pl\
	--est_method RSEM\
	--quant_files matrix.txt\
	--name_sample_by_basedir\
	--gene_trans_map ../allreads_trinity.Trinity.fasta.gene_trans_map

matrix.txt:
HHG/HHG_3/RSEM.isoforms.results
HHG/HHG_2/RSEM.isoforms.results
HHG/HHG_1/RSEM.isoforms.results
HH/HH_1/RSEM.isoforms.results

head -5 allreads_trinity.Trinity.fasta.gene_trans_map:
TRINITY_DN54622_c0_g1   TRINITY_DN54622_c0_g1_i1
TRINITY_DN54622_c2_g1   TRINITY_DN54622_c2_g1_i1
TRINITY_DN54606_c0_g1   TRINITY_DN54606_c0_g1_i1
TRINITY_DN54589_c0_g1   TRINITY_DN54589_c0_g1_i1
TRINITY_DN54670_c0_g1   TRINITY_DN54670_c0_g1_i

grep 'TRINITY_DN0_c0_g1_i8' allreads_trinity.Trinity.fasta.gene_trans_map:
TRINITY_DN0_c0_g1       TRINITY_DN0_c0_g1_i8

grep 'TRINITY_DN0_c0_g1_i8' HHG/HHG_3/RSEM.isoforms.results:
no output (tried it for the other samples too, none of them have it)

Seems to me like the algorithm requires every sample to have all the transcripts accounted for? Is that reasonable? Or am I misunderstanding the issue?

I've been bonking my head for hours, very grateful for help. :+1: 

Joel

**Comment by brianjohnhaas** [comment]
apologies - missed this.  Please let me know if it's still an issue
