### ISSUE TITLE
Mixed single-end/paired-end reads for genome-based assembly? 

### ISSUE THREAD

**Issue by apredeus** [trinityrnaseq/trinityrnaseq#960]
Hello, 

I was wondering if it's OK to use a mix of single-end and paired-end reads in a BAM file for genome-based assembly? 

I've started the run and it seems like it auto-detected the file to be paired-end. Are single-end reads still going to be used? Unfortunately, there's quite a lot of them overall. 

Or, should I just align everything as single-end reads, if I want all the reads to be assembled? 

Thank you in advance.

**Comment by brianjohnhaas** [comment]
sorry, missed this somehow.  We have documentation here: https://github.com/trinityrnaseq/trinityrnaseq/wiki/How-do-I-combine-reads%3F
