### ISSUE TITLE
Transfuse and TrinityStats

### ISSUE THREAD

**Issue by fabianomenegidio** [trinityrnaseq/trinityrnaseq#962]
I did the assembly with Trinity of different tissues and then merged with Transfuse.

I would like to get details of the assembly by TrinityStats, but I notice an error in formatting the FASTA header.

How can I use TrinityStats in a Transfuse output?

**Comment by brianjohnhaas** [comment]
TrinityStats is specific to Trinity in case you're trying to use it on something different.
