### ISSUE TITLE
combining paired end raw reads of different library sizes

### ISSUE THREAD

**Issue by IamAbhishek22** [trinityrnaseq/trinityrnaseq#970]
Hi everyone!!! 
In my trinity assembly, I have two paired end raw read library sets, one with the read size of 75bp and the other with the read size of 150 bp. I want to merge the two library sets together and assemble them in a singl assembly as they are of same plant tissues. Will there be any issues if I do this, or should I asssemble the two paired end library sets separately and then merge the two assembled transcriptomes by CD-HIT for functional annotation?

**Comment by brianjohnhaas** [comment]
running them as combined inputs should be fine
