### ISSUE TITLE
De-novo assembly vs. data amount

### ISSUE THREAD

**Issue by ARW-UBT** [trinityrnaseq/trinityrnaseq#971]
Hi, 
I am wondering whether there is an 'upper' limit of reads that should be used for -de-novo transcriptome assemblies in order to avoid allelic variant and to improve assembly performance. 

The genome of the new assembly is ca. 1.3 GB (as expected from another species of the same genus (Eisenia andrei, earthworm))
The amount of RNA-Seq reads (poly A) available is ca. 1200 million reads (paired end at 150 bp) from 78 independent samples. I assume this is far to much to be used for de-novo assemblies as well as for genome-guided assemblies.

Is there a rule-of-the-thumb, how much amount of sequencing data should be used? 
Or would you recommend to test it with increasing amount of sequencing data as described in https://doi.org/10.1186/s12859-019-3166-x?

And a short technical question: is it possible to provide more than on bam file for genome-guided assemblies? 

Thank you for any comments.

**Comment by brianjohnhaas** [comment]
totally missed this one. apologies!

I'm not sure of the upper limit. We've assembled over a billion reads, but normalization dropped it down to less than 100M reads. Overall, will depend on the complexity of the data more than the total read count.

wrt how much sequencing, it's really organism dependent and also related to sequence complexity.  These help:

https://github.com/trinityrnaseq/trinityrnaseq/wiki/Transcriptome-Contig-Nx-and-ExN50-stats

and

botto of https://github.com/trinityrnaseq/trinityrnaseq/wiki/Counting-Full-Length-Trinity-Transcripts
